const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产法律法规测验',
  quizSynopsis: '本测验涵盖建设工程安全生产法律法规的单选题、多选题和判断题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '9',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '下列建筑施工人员属于特种作业的是（   ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '油漆工',
        '高处作业吊篮安装拆卸工',
        '混凝土工',
        '钢筋工',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，高处作业吊篮安装拆卸工属于特种作业。',
      explanation: '根据《建筑施工特种作业人员管理规定》，高处作业吊篮安装拆卸工需取得特种作业资格证书。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员必须经（   ）考核合格，取得建筑施工特种作业人员操作资格证书，方可上岗从事相应作业。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '省级人民政府',
        '当地人民政府',
        '建设主管部门',
        '行政主管部门',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，建设主管部门负责特种作业人员的考核。',
      explanation: '根据相关法规，建设主管部门负责特种作业人员的资格考核和发证。',
      point: '10',
    },
    {
      question: '下列条件中（   ）是申请从事建筑施工特种作业的人员应当具备的基本条件之一。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '年满18周岁且符合相关工种规定的年龄要求',
        '具有丰富特种作业工作经验',
        '经企业年度安全生产教育培训合格',
        '必须具有高中及以上学历',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，年龄要求是特种作业人员的基本条件之一。',
      explanation: '根据规定，申请特种作业需年满18周岁并符合工种年龄要求。',
      point: '10',
    },
    {
      question: '下列建筑施工人员属于特种作业的是(   )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '建筑电工',
        '建筑起重信号司索工',
        '建筑架子工',
        '建筑起重机械安装拆卸工',
        '经省级以上人民政府建设主管部门认定的其他特种作业',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上选项均为特种作业人员。',
      explanation: '根据《建筑施工特种作业人员管理规定》，列出的工种均需特种作业资格证书。',
      point: '10',
    },
    {
      question: '从事建筑施工特种作业的人员，应当具备下列那些基本条件（   ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '年满18周岁且符合相关工种规定的年龄要求',
        '经医院体检合格且无妨碍从事相应特种作业的疾病和生理缺陷',
        '年满20周岁且符合相关工种规定的年龄要求',
        '高中及以上学历',
        '初中及以上学历',
      ],
      correctAnswer: [1, 2, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查年龄和学历要求。',
      explanation: '根据规定，特种作业人员需年满18周岁、身体健康、初中及以上学历。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员的考核内容应当包括(   )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '安全技术理论',
        '安全思想教育',
        '安全技术措施',
        '实际操作',
        '职业卫生考核',
      ],
      correctAnswer: [1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，考核内容包括安全技术理论和实际操作。',
      explanation: '考核重点为安全技术理论和实际操作能力。',
      point: '10',
    },
    {
      question: '申请从事建筑施工特种作业的人员应当向本人户籍所在地或者从业所在地考核发证机关提出申请，并提交相关证明材料。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，可在户籍地或从业地申请。',
      explanation: '根据《建筑施工特种作业人员管理规定》，申请可灵活选择地点。',
      point: '10',
    },
    {
      question: '特种作业资格证书不可以在全国通用。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，特种作业资格证书全国通用。',
      explanation: '特种作业资格证书在全国范围内有效。',
      point: '10',
    },
    {
      question: '持有特种作业资格证书的人员，应当受聘于建筑施工企业或者建筑起重机械出租单位(用人单位)，方可从事相应的特种作业。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，必须受聘于相关单位。',
      explanation: '根据规定，特种作业人员需受聘于合法单位从事作业。',
      point: '10',
    },
  ],
};

export default quiz;
