const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产基础题库 - 多选题',
  quizSynopsis: '本测验涵盖建设工程安全生产基础题库的多选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '72',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '按照《建筑施工现场标志设置技术规程》安全标志分为下列四种',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、禁止标志',
        'B、警告标志',
        'C、安全标志',
        'D、指令标志',
        'E、提示标志',
      ],
      correctAnswer: [0, 1, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、禁止标志、B、警告标志 、D、指令标志  、E、提示标志。',
      explanation: '',
      point: '2',
    },
    {
      question: '图中存在哪些安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、基坑未采取支护措施',
        'B、临边未防护',
        'C、未配备消防器材',
        'D、基坑边堆载严重',
        'E、未设置电箱',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、基坑未采取支护措施、B、临边未防护、C、未配备消防器材、D、基坑边堆载严重。',
      explanation: '',
      point: '2',
    },
    {
      question: '脚手架搭设过程中会发生哪些事故（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、坍塌',
        'B、高空坠落',
        'C、物体打击',
        'D、机械伤害',
        'E、中毒、窒息',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、坍塌、B、高空坠落 、C、物体打击。',
      explanation: '',
      point: '2',
    },
    {
      question: '按照《生产安全事故应急预案管理办法》规定，应急预案分为（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、综合应急预案',
        'B、现场处置方案',
        'C、专项应急预案',
        'D、单独应急预案',
        'E、专业应急预案',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、综合应急预案、B、现场处置方案、C、专项应急预案。',
      explanation: '',
      point: '2',
    },
    {
      question: '应急演练按照组织形式分为（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、桌面演练',
        'B、现场演练',
        'C、实战演练',
        'D、单项演练',
        'E、综合演练',
      ],
      correctAnswer: [0, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、桌面演练、C、实战演练。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《生产安全事故报告和调查处理条例》，生产安全事故分为哪些等级（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、特别重大事故',
        'B、重大事故',
        'C、较大事故',
        'D、一般事故',
        'E、轻伤事故',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、特别重大事故、B、重大事故、C、较大事故、D、一般事故。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《生产经营单位安全培训规定》，三级安全教育包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、公司级',
        'B、项目级',
        'C、班组级',
        'D、作业队',
        'E、安全监督部门',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、公司级、B、项目级、C、班组级。',
      explanation: '',
      point: '2',
    },
    {
      question: '施工现场个人安全防护用品所需的三证一标志有（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、安全生产许可证',
        'B、生产许可证',
        'C、产品合格证',
        'D、安全鉴定证',
        'E、安全标志',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B、生产许可证、C、产品合格证、D、安全鉴定证、E、安全标志。',
      explanation: '',
      point: '2',
    },
    {
      question: '我国建筑施工行业主要的事故类型为（）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、坍塌',
        'B、高处坠落',
        'C、物体打击',
        'D、机械伤害',
        'E、触电',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、坍塌、B、高处坠落、C、物体打击、D、机械伤害、E、触电。',
      explanation: '',
      point: '2',
    },
    {
      question: '起重吊装作业应采取（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、配备司索指挥',
        'B、设置警戒线',
        'C、设置禁止入内告示牌',
        'D、专职安全员现场监督',
        'E、项目技术负责人带班检查',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、配备司索指挥、B、设置警戒线、C、设置禁止入内告示牌、D、专职安全员现场监督。',
      explanation: '',
      point: '2',
    },
    {
      question: '为保证起重吊装作业安全，应采取下列（）措施',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、司索、指挥应持证上岗且不得无故离岗',
        'B、作业过程中，设置警示标志牌，禁止无关人员入内',
        'C、吊装物料时，可以从作业人员头顶越过',
        'D、起吊前应进行试吊',
      ],
      correctAnswer: [0, 1, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、司索、指挥应持证上岗且不得无故离岗、B、作业过程中，设置警示标志牌，禁止无关人员入内、D、起吊前应进行试吊。',
      explanation: '',
      point: '2',
    },
    {
      question: '国家规定生产经营单位安全教育培训对象，主要包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、生产经营单位主要负责人',
        'B、安全生产管理人员',
        'C、其他从业人员',
        'D、特种作业人员',
        'E、参观人员',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、生产经营单位主要负责人、B、安全生产管理人员、C、其他从业人员、D、特种作业人员。',
      explanation: '',
      point: '2',
    },
    {
      question: '上图所示，可能导致哪些类别的事故发生（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、火灾',
        'B、机械伤害',
        'C、中毒',
        'D、物体打击',
        'E、高空坠落',
      ],
      correctAnswer: [3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：D、物体打击、E、高空坠落。',
      explanation: '',
      point: '2',
    },
    {
      question: '焊接作业时，作业人员应穿戴（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、绝缘鞋',
        'B、电焊手套',
        'C、防护面罩',
        'D、护目镜',
        'E、安全带',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、绝缘鞋、B、电焊手套、C、防护面罩、D、护目镜。',
      explanation: '',
      point: '2',
    },
    {
      question: '施工现场临时用电必须符合（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、三级配电',
        'B、两级保护',
        'C、TN-S接零保护系统',
        'D、一闸、一机、一漏、一箱',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、三级配电、B、两级保护、C、TN-S接零保护系统、D、一闸、一机、一漏、一箱。',
      explanation: '',
      point: '2',
    },
    {
      question: '发生伤亡事故后，事故报告应包括的内容（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、事故发生的原因',
        'B、事故发生的时间、地点及事故现场情况',
        'C、事故发生后造成的人员伤亡和直接经济损失',
        'D、事故发生后采取的主要措施',
        'E、事故发生的简要经过',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B、事故发生的时间、地点及事故现场情况、C、事故发生后造成的人员伤亡和直接经济损失、D、事故发生后采取的主要措施、E、事故发生的简要经过。',
      explanation: '',
      point: '2',
    },
    {
      question: '三级开关箱中存在哪些安全隐患',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、电箱内设置活动插头',
        'B、电箱门与箱体连接的编织软铜线断开',
        'C、漏电保护器的额定漏电动作电流参数不正确',
        'D、电箱未设置重复接地',
        'E、用电设备电缆无PE线',
      ],
      correctAnswer: [0, 1, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、电箱内设置活动插头、B、电箱门与箱体连接的编织软铜线断开、D、电箱未设置重复接地、E、用电设备电缆无PE线。',
      explanation: '',
      point: '2',
    },
    {
      question: '临时用电在（）情况下需要编制临时用电组织设计。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、5台及5台以上用电设备',
        'B、4台及4台以上用电设备',
        'C、设备总容量50KW以上',
        'D、设备总容量40KW以上',
        'E、3台及3台以上或设备总容量50KW以上',
      ],
      correctAnswer: [0, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、5台及5台以上用电设备、C、设备总容量50KW以上。',
      explanation: '',
      point: '2',
    },
    {
      question: '依据《建设工程安全生产管理条例》规定，（）工程 （ ）工程、地下暗挖工程的专项施工方案，施工单位应当组织专家论证审查。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、高大模板',
        'B、深基坑',
        'C、起重吊装',
        'D、拆除、爆破',
        'E、人工挖孔桩',
      ],
      correctAnswer: [0, 1],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、高大模板、B、深基坑。',
      explanation: '',
      point: '2',
    },
    {
      question: '脚手架在搭设过程中会发生哪些事故（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、坍塌',
        'B、高空坠落',
        'C、物体打击',
        'D、火灾',
        'E、中毒、窒息',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、坍塌、B、高空坠落 、C、物体打击。',
      explanation: '',
      point: '2',
    },
    {
      question: '脚手架搭设过程中，作业人员应佩戴哪些安全防护用品（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、安全帽',
        'B、安全带',
        'C、安全网',
        'D、安全绳',
        'E、防滑鞋',
      ],
      correctAnswer: [0, 1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、安全帽、B、安全带、E、防滑鞋。',
      explanation: '',
      point: '2',
    },
    {
      question: '《安全生产法》中规定,( )单位应当设置安全生产管理机构或者配备专职安全生产管理人员。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、矿山',
        'B、金属冶炼',
        'C、建筑施工',
        'D、运输单位和危险物品的生产、经营、储存、装卸',
        'E、烟花爆竹',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、矿山、B、金属冶炼、C、建筑施工、D、运输单位和危险物品的生产、经营、储存、装卸。',
      explanation: '',
      point: '2',
    },
    {
      question: '发生氨水泄漏事故进行抢修时，作业人员必须穿戴好（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、防化服',
        'B、橡胶手套',
        'C、橡胶雨靴',
        'D、正压式空气呼吸器',
        'E、防护眼镜',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、防化服、B、橡胶手套、C、橡胶雨靴、D、正压式空气呼吸器、E、防护眼镜。',
      explanation: '',
      point: '2',
    },
    {
      question: '安全技术交底应包含（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、岗位存在的危险因素',
        'B、危险因素的具体预防措施',
        'C、安全操作规定',
        'D、文明施工要求',
        'E、避难与急救措施',
      ],
      correctAnswer: [0, 1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、岗位存在的危险因素 、B、危险因素的具体预防措施、C、安全操作规定、E、避难与急救措施。',
      explanation: '',
      point: '2',
    },
    {
      question: '生产经营单位主要负责人对本单位安全生产工作负有下列职责（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、建立健全并落实本单位安全生产责任制',
        'B、组织制定并实施本单位安全规章制度和操作规程',
        'C、组织制定并实施本单位安全生产教育和培训计划',
        'D、保证本单位安全生产投入的有效实施',
        'E、制止和纠正违章指挥、强令冒险作业、违反操作规程的行为',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、建立健全并落实本单位安全生产责任制、B、组织制定并实施本单位安全规章制度和操作规程、C、组织制定并实施本单位安全生产教育和培训计划、D、保证本单位安全生产投入的有效实施。',
      explanation: '',
      point: '2',
    },
    {
      question: '建筑起重机械有以下（）情形之一的，出租单位或者自购建筑起重机械的使用单位应当予以报废，并向原备案机关办理注销手续',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、没有齐全有效的安全保护装置的',
        'B、没有完整安全技术档案的',
        'C、经检验达到安全技术标准规定的',
        'D、超过安全技术标准或者制造厂家规定的使用年限',
        'E、属国家淘汰或者禁止使用的',
      ],
      correctAnswer: [0, 1, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、没有齐全有效的安全保护装置的、B、没有完整安全技术档案的、D、超过安全技术标准或者制造厂家规定的使用年限、E、属国家淘汰或者禁止使用的。',
      explanation: '',
      point: '2',
    },
    {
      question: '出租单位出租的建筑起重机械和使用单位购置、租赁、使用的建筑起重机械应当具有（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、特种设备制造许可证',
        'B．产品合格证',
        'C．制造监督检验证明',
        'D．监理单位证明',
        'E．使用记录',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、特种设备制造许可证、B．产品合格证、C．制造监督检验证明。',
      explanation: '',
      point: '2',
    },
    {
      question: '生产经营单位主要负责人安全培训应当包括下列（）内容',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、国家安全生产方针、政策和有关安全生产的法律、法规',
        'B、安全生产管理基本知识、安全生产技术、安全生产专业知识',
        'C、重大危险源管理、重大事故防范、应急管理和救援组织以及事故调查处理的有关规定',
        'D、职业危害及其预防措施',
        'E、国内外先进的安全生产管理经验',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、国家安全生产方针、政策和有关安全生产的法律、法规、B、安全生产管理基本知识、安全生产技术、安全生产专业知识、C、重大危险源管理、重大事故防范、应急管理和救援组织以及事故调查处理的有关规定、D、职业危害及其预防措施、E、国内外先进的安全生产管理经验。',
      explanation: '',
      point: '2',
    },
    {
      question: '安全生产制度体系应包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、安全生产会议制度',
        'B、安全生产教育培训制度',
        'C、安全生产考核和奖惩制度',
        'D、安全生产事故隐患排查治理制度',
        'E、生产安全生产事故报告和调查处理制度',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、安全生产会议制度、B、安全生产教育培训制度、C、安全生产考核和奖惩制度、D、安全生产事故隐患排查治理制度、E、生产安全生产事故报告和调查处理制度。',
      explanation: '',
      point: '2',
    },
    {
      question: '有限空间作业应坚持（）原则',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、先通风',
        'B、后检测',
        'C、再作业',
        'D、不通风',
        'E、先作业',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、先通风、B、后检测、C、再作业。',
      explanation: '',
      point: '2',
    },
    {
      question: '有限空间作业前应采用气体检测仪对（）进行检测',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、氧气含量',
        'B、一氧化碳',
        'C、硫化氢',
        'D、甲烷',
        'E、二氧化碳',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、氧气含量、B、一氧化碳、C、硫化氢、D、甲烷。',
      explanation: '',
      point: '2',
    },
    {
      question: '新《安全生产法》中落实“三个必须”分别为',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、管行业必须管安全',
        'B、管业务必须管安全',
        'C、管生产经营必须管安全',
        'D、管专业必须管安全',
        'E、管生产计划必须管安全',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、管行业必须管安全、B、管业务必须管安全、C、管生产经营必须管安全。',
      explanation: '',
      point: '2',
    },
    {
      question: '“四新”分别包括',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、新技术',
        'B、新工艺',
        'C、新材料',
        'D、新设备',
        'E、新装备',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、新技术、B、新工艺、C、新材料、D、新设备。',
      explanation: '',
      point: '2',
    },
    {
      question: '上图中存在的安全隐患应如何整改（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、易燃品分类存放',
        'B、配备消防器材',
        'C、存放在易燃易爆品库房中',
        'D、靠近总配电室存放',
        'E、避免暴晒',
      ],
      correctAnswer: [0, 1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、易燃品分类存放、B、配备消防器材、C、存放在易燃易爆品库房中、E、避免暴晒。',
      explanation: '',
      point: '2',
    },
    {
      question: '经常性安全生产检查通常包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、交接班检查',
        'B、班中检查',
        'C、月末检查',
        'D、特殊检查',
        'E、定期检查',
      ],
      correctAnswer: [0, 1, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、交接班检查、B、班中检查、D、特殊检查。',
      explanation: '',
      point: '2',
    },
    {
      question: '重大事故隐患治理方案应包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、治理的目标及任务',
        'B、采取的方法和措施',
        'C、经费和物资的落实',
        'D、治理的时限和要求',
        'E、静态处理',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、治理的目标及任务、B、采取的方法和措施、C、经费和物资的落实、D、治理的时限和要求。',
      explanation: '',
      point: '2',
    },
    {
      question: '依据《危险性较大的分部分项工程安全管理规定》，施工单位应当在施工现场显著位置公告',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、危大工程名称',
        'B、项目名称',
        'C、责任人员',
        'D、工作量',
        'E、施工时间',
      ],
      correctAnswer: [0, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、危大工程名称、C、责任人员、E、施工时间。',
      explanation: '',
      point: '2',
    },
    {
      question: '对于需要验收的危大工程，（）应当组织相关人员进行验收',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、施工单位',
        'B、建设单位',
        'C、设计单位',
        'D、勘察单位',
        'E、监理单位',
      ],
      correctAnswer: [0, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、施工单位、E、监理单位。',
      explanation: '',
      point: '2',
    },
    {
      question: '高处作业吊篮作为外墙施工最主要、最常用的机械，施工过程中应防止哪些事故的发生（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、高空坠落',
        'B、坍塌',
        'C、物体打击',
        'D、触电',
        'E、机械伤害',
      ],
      correctAnswer: [0, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、高空坠落、C、物体打击、D、触电。',
      explanation: '',
      point: '2',
    },
    {
      question: '基坑开挖顺序应遵循（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、先挖后撑',
        'B、分层、分块、分段',
        'C、严禁超挖',
        'D、开槽支撑',
        'E、垂直开挖',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B、分层、分块、分段、C、严禁超挖、D、开槽支撑 。',
      explanation: '',
      point: '2',
    },
    {
      question: '落地式脚手架存在哪些危险因素？（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、高空坠落',
        'B、坍塌',
        'C、触电',
        'D、机械伤害',
        'E、物体打击',
      ],
      correctAnswer: [0, 1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、高空坠落、B、坍塌、E、物体打击。',
      explanation: '',
      point: '2',
    },
    {
      question: '建筑施工企业对工程项目安全检查的方式主要包括',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、综合性检查',
        'B、定期检查',
        'C、经常性检查',
        'D、季节性检查',
        'E、不定期检查',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、综合性检查 、B、定期检查 、C、经常性检查、D、季节性检查、E、不定期检查。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、电焊机未采取接零保护',
        'B、私自焊接悬挑架使用的型钢',
        'C、焊接作业未配备消防器材',
        'D、焊把线破损',
        'E、易燃易爆品未分类存放',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、电焊机未采取接零保护、B、私自焊接悬挑架使用的型钢、C、焊接作业未配备消防器材。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、配电箱无箱门',
        'B、配电箱未设置重复接地',
        'C、配电箱内接线混乱',
        'D、配电箱内无漏电保护器',
        'E、配电箱未安装隔离开关或断路器',
      ],
      correctAnswer: [0, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、配电箱无箱门、C、配电箱内接线混乱、E、配电箱未安装隔离开关或断路器。',
      explanation: '',
      point: '2',
    },
    {
      question: '“三宝”是指（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、安全帽',
        'B、安全带',
        'C、安全网',
        'D、密目网',
        'E、安全绳',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、安全帽 、B、安全带、C、安全网。',
      explanation: '',
      point: '2',
    },
    {
      question: '“四口”是指（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、电梯口',
        'B、通道口',
        'C、预留洞口',
        'D、楼梯口',
        'E、烟道口',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、电梯口、B、通道口、C、预留洞口、D、楼梯口。',
      explanation: '',
      point: '2',
    },
    {
      question: '4“五临边”是指（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、楼梯边',
        'B、基坑边',
        'C、阳台边',
        'D、屋面边',
        'E、楼层边',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、楼梯边、B、基坑边、C、阳台边、D、屋面边、E、楼层边。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、作业人员未佩戴安全带',
        'B、高空作业未履行审批手续',
        'C、电缆私拉乱接',
        'D、移动脚手架无防倾覆措施',
        'E、未配备消防器材',
      ],
      correctAnswer: [0, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、作业人员未佩戴安全带、C、电缆私拉乱接、D、移动脚手架无防倾覆措施。',
      explanation: '',
      point: '2',
    },
    {
      question: '在生产安全事故调查处理中，坚持的四不放过原则是指（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、事故原因没有查清不放过',
        'B、责任人员没有受到处理不放过',
        'C、职工群众没有受到教育不放过',
        'D、防范措施没有落实不放过',
        'E、事故单位未受到处理不放过',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、事故原因没有查清不放过 、B、责任人员没有受到处理不放过、C、职工群众没有受到教育不放过、D、防范措施没有落实不放过。',
      explanation: '',
      point: '2',
    },
    {
      question: '危大工程验收合格后，施工单位应当在施工现场明显位置设置验收标识牌，公示（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、验收时间',
        'B、验收人员',
        'C、验收结论',
        'D、项目名称',
        'E、验收部位',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、验收时间、B、验收人员、C、验收结论、D、项目名称、E、验收部位。',
      explanation: '',
      point: '2',
    },
    {
      question: '安全色分别为（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、红',
        'B、黄',
        'C、蓝',
        'D、绿',
        'E、黑',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、红、B、黄、C、蓝、D、绿 。',
      explanation: '',
      point: '2',
    },
    {
      question: '依据《建设工程安全生产管理条例》，施工现场应在（）设置明显的安全警示标志',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、楼梯口',
        'B、配电箱',
        'C、塔吊',
        'D、基坑底部',
        'E、办公区',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、楼梯口、B、配电箱、C、塔吊。',
      explanation: '',
      point: '2',
    },
    {
      question: '脚手架所用钢管使用时，应注意()',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、φ48×3.5与φ51×3的钢管不得混用',
        'B、φ48×3.5与φ51×3的钢管可以混用',
        'C、φ51×3与φ32×2的钢管可以混用',
        'D、钢管上严禁打孔',
        'E、开孔不影响钢管的使用',
      ],
      correctAnswer: [0, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、φ48×3.5与φ51×3的钢管不得混用、D、钢管上严禁打孔。',
      explanation: '',
      point: '2',
    },
    {
      question: '塔式起重机安装完毕的四方验收分别包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、建设单位',
        'B、使用单位',
        'C、监理单位',
        'D、安装单位',
        'E、租赁单位',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B、使用单位、C、监理单位、D、安装单位、E、租赁单位。',
      explanation: '',
      point: '2',
    },
    {
      question: '建设单位应当在拆除工程施工15日前，将下列资料报送建设工程所在地的县级以上地方人民政府建设行主管部门或者其他有关部门备案（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、堆放、清除废弃物的措施',
        'B、施工单位资质等级证明',
        'C、拟拆除工程地下管线资料',
        'D、拟拆除建筑物、构筑物及可能危及毗邻建筑的说明',
        'E、拆除施工组织方案',
      ],
      correctAnswer: [0, 1, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、堆放、清除废弃物的措施、B、施工单位资质等级证明、D、拟拆除建筑物、构筑物及可能危及毗邻建筑的说明、E、拆除施工组织方案。',
      explanation: '',
      point: '2',
    },
    {
      question: '施工单位应当在施工现场建立消防安全责任制度，确定消防安全责任人，制定用火、用电、使用易燃易爆材料等各项消防安全管理制度、操作规程，()，并在施工现场人口处设置明显标志',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、设置消防通道',
        'B、配备消防水源',
        'C、配备消防设施',
        'D、配备灭火器材',
        'E、请消防队员驻防',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、设置消防通道、B、配备消防水源、C、配备消防设施、D、配备灭火器材。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、楼层反坎断开',
        'B、悬挑工字钢锚固段长度不足',
        'C、锚固螺栓设置不合理',
        'D、卸料平台与楼层间的间隙未封闭',
        'E、纵向扫地杆距钢管底端大于200mm',
      ],
      correctAnswer: [3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：D、卸料平台与楼层间的间隙未封闭、E、纵向扫地杆距钢管底端大于200mm。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、电箱内接线不规范',
        'B、电箱内漏电保护器额定动作电流参数不符合要求',
        'C、电箱内设置活动插头',
        'D、箱体与箱门未采用编织软铜线连接',
        'E、电箱PE零线未设置重复接地',
      ],
      correctAnswer: [0, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、电箱内接线不规范、C、电箱内设置活动插头、D、箱体与箱门未采用编织软铜线连接。',
      explanation: '',
      point: '2',
    },
    {
      question: '消防柜中应配备哪些消防器材（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、消防铲',
        'B、消防斧',
        'C、消防桶',
        'D、灭火器',
        'E、消防钩',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、消防铲、B、消防斧 、C、消防桶、D、灭火器、E、消防钩。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、箱体与箱门未采用编织软铜线连接',
        'B、设备电源线未经过漏电保护器',
        'C、电箱内设置活动插头',
        'D、动力与照明未分箱设置',
        'E、未做分路标记',
      ],
      correctAnswer: [0, 1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、箱体与箱门未采用编织软铜线连接、B、设备电源线未经过漏电保护器、C、电箱内设置活动插头、E、未做分路标记。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全事故隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、锚固螺栓未采用双螺母',
        'B、螺母未拧紧',
        'C、锚固段长度不足',
        'D、建筑材料未清理',
        'E、压板与工字钢间未设置木楔',
      ],
      correctAnswer: [0, 1],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、锚固螺栓未采用双螺母、B、螺母未拧紧。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、未配备消防器材',
        'B、用电设备外漏可导电部位采用保护接地装置',
        'C、钢筋调直机端头未设置防护罩',
        'D、接地装置采用圆钢',
        'E、传动部位防护门损坏',
      ],
      correctAnswer: [1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B、用电设备外漏可导电部位采用保护接地装置、C、钢筋调直机端头未设置防护罩、E、传动部位防护门损坏。',
      explanation: '',
      point: '2',
    },
    {
      question: '专职安全生产管理人员负责对安全生产进行现场监督检查。对于()的，应当立即制止',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、影响工程造价',
        'B、违章指挥',
        'C、违章操作',
        'D、不戴安全帽',
        'E、违反劳动记律',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B、违章指挥、C、违章操作、D、不戴安全帽、E、违反劳动记律。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、作业人员高空作业未佩戴安全带',
        'B、移动脚手架未设置防倾覆措施',
        'C、移动脚手架未采取防滑措施',
        'D、移动脚手架钢管未涂刷油漆',
        'E、移动脚手架未设置临边防护措施',
      ],
      correctAnswer: [0, 1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、作业人员高空作业未佩戴安全带、B、移动脚手架未设置防倾覆措施、E、移动脚手架未设置临边防护措施。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、圆盘锯刀盘未防护',
        'B、锯末未及时清理',
        'C、未悬挂安全警示标志牌',
        'D、圆盘锯未设置接零保护',
        'E、未配备消防器材',
      ],
      correctAnswer: [0, 1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、圆盘锯刀盘未防护、B、锯末未及时清理、E、未配备消防器材。',
      explanation: '',
      point: '2',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、剪刀撑未按要求搭设',
        'B、防护栏杆高度不足',
        'C、立柱底端离地面间距过大',
        'D、立柱间距过大',
        'E、上下爬梯不符合要求',
      ],
      correctAnswer: [0, 1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、剪刀撑未按要求搭设、B、防护栏杆高度不足、C、立柱底端离地面间距过大、E、上下爬梯不符合要求。',
      explanation: '',
      point: '2',
    },
    {
      question: '施工单位应当建立健全( )，制定安全生产规章制度和操作规程，保证本单位安全生产条件所需资金的投入，对所承担的建设工程进行定期和专项安全检查，并做好安全检查记录',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、安全生产教育培训制度',
        'B、生产组织机构',
        'C、安全生产责任制度',
        'D、质量技术交底',
        'E、质量检查制度',
      ],
      correctAnswer: [0, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、安全生产教育培训制度、C、安全生产责任制度。',
      explanation: '',
      point: '2',
    },
    {
      question: '施工单位应当在施工组织设计中编制有关安全的( )',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、安全技术措施',
        'B、施工现场临时用电方案',
        'C、售楼方案',
        'D、施工经济技术措施',
        'E、作业材料选购方案',
      ],
      correctAnswer: [0, 1],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、安全技术措施、B、施工现场临时用电方案。',
      explanation: '',
      point: '2',
    },
    {
      question: '安全技术交底必须()',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、具体',
        'B、明确',
        'C、针对性强',
        'D、含混',
        'E、不需要具体',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、具体、B、明确、C、针对性强。',
      explanation: '',
      point: '2',
    },
    {
      question: '安全生产检查的内容主要有（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、查思想',
        'B、查管理',
        'C、查隐患',
        'D、查整改',
        'E、查事故处理',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、查思想、B、查管理、C、查隐患、D、查整改、E、查事故处理。',
      explanation: '',
      point: '2',
    },
    {
      question: '安全生产检查时对查出的安全隐患要做到“五定”措施，其中包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、定整改责任人',
        'B、定整改措施',
        'C、定整改完成时间',
        'D、定整改完成人',
        'E、定整改验收人',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、定整改责任人、B、定整改措施、C、定整改完成时间、D、定整改完成人、E、定整改验收人。',
      explanation: '',
      point: '2',
    },
    {
      question: '生产经营单位应当进行安全培训的从业人员包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、主要负责人',
        'B、安全生产管理人员',
        'C、特种作业人员',
        'D、其他从业人员',
        'E、来机关办事人员',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、主要负责人、B、安全生产管理人员、C、特种作业人员、D、其他从业人员。',
      explanation: '根据相关规范',
      point: '2',
    },
  ],
};

export default quiz;
