const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产基础题库 - 判断题',
  quizSynopsis: '本测验涵盖建设工程安全生产基础题库的判断题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '192',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '依据《建筑施工高处作业安全技术规程》，高处作业前应按类别对安全防护设施进行检查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '“违章操作，作业时未挂安全绳，工人未系安全带”属于高空坠落事故发生的不安全因素之—',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '特殊情况下，经负责事故调查的人民政府批准，提交事故调查报告的期限可以延长，但延长的期限最长不超过60日',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《特种作业人员目录》，电工是否属于特种作业人员',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、是',
        'B、否',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '项目负责人带班生产时，要全面掌握工程项目质量安全生产状况，加强对重点部位、关键环节的控制，及时消除隐患。要认真做好带班生产记录并签字存档备查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '《安全生产法》规定，生产经营单位必须为从业人员提供符合国家标准或者行业标准的劳动防护用品，并监督、教育从业人员按照使用规则佩戴、使用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工单位应当制定本单位生产安全事故应急救援预案，建立应急救援组织或者配备应急救援人员，配备必要的应急救援器材、设备，并定期组织演练。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '实行施工总承包的建设工程，由总承包单位负责上报事故（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中，作业人员的做法是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中的作业人员是否需要持证上岗（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、需要',
        'B、不需要',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '“十不吊”是吊装作业必须遵守的原则（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中说法是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中说法是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中吊装作业绑扎的方式是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '进行起重吊装作业时，不需要疏散其余无关人员（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '进入施工现场的从业人员不需要掌握本岗位存在的危险因素（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '从事高处作业的人员要定期进行身体健康检查。凡患有高血压病，心脏病、贫血病、癫痫病者不得安排从事高处作业（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '动火前必须清除周围的可燃物。当有固定装置等无法清除时，应采用“接火盘”等防止火星乱溅的措施（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场临时用电采用的设备设施费用是否纳入安全文明措施费用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、是',
        'B、不是',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场临时用电应实行动力与照明分设（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '临时用电工程定期检查应按分部、分项工程进行，对安全隐患必须及时处理，并应履行复查验收手续（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '发生无人员伤亡的一般事故，县级人民政府可委托事故发生单位进行事故调查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '乙炔瓶在储存或使用时可以水平放置（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80要求，图中水平预留洞口防护设置是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '生产经营单位不得以任何形式与从业人员订立协议，免除或者减轻其对从业人员因生产安全事故伤亡依法应承担的责任。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '生产经营单位发生生产安全事故时，单位的主要负责人应当立即组织抢救，并不得在事故调查处理期间擅离职守',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '进入有限空间作业前不需要办理审批手续（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '有限空间作业可以采用纯氧进行通风换气（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '实施有限空间作业时，应安排专人监督值守（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中作业人员的做法是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '搅拌机作业中，当料斗升起时，严禁任何人在料斗下停留或通过（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮是否属于危险性较大的分部分项工程（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、属于',
        'B、不属于',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮可以不设置前支腿，安装在女儿墙上（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '用人单位应当保障职业病防治所需的资金投入，不得挤占、挪用，并对因资金投入不足导致的后果承担责任',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '劳动者离岗前60日内的在岗期间的职业健康检查可以视为离岗时的职业健康检查（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '脚手架拆除作业应设专人指挥，当有多人同时操作时，应明确分工、统一行动，且应具有足够的操作面，卸料时各构配件严禁抛掷至地面',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '生产经营单位应定期组织从事职业病危害的从业人员进行健康体检',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '生产经营单位应当为从事职业病危害的从业人员配备相应的防护用品',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '有限空间是指封闭或部分封闭，进出口较为狭窄有限，未被设计为固定工作场所，自然通风不良，易造成硫化氢、一氧化碳、二氧化硫、甲烷、氰化氢等有害气体中毒、爆炸危险或氧含量不足（低于19.5%）的空间',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中说法是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '采取“四新技术”时，对已经接受安全教育培训和安全技术交底的从业人员，不需要重新进行安全教育培训和安全技术交底。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，该人员做法是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '情况紧急下，事故单位负责人可以越级上报事故情况（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '因抢救人员、防止事故扩大以及疏通交通等原因，需要移动事故现场物件，可以随便移动，不采取任何措施',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '危险性较大工程施工期间，对于有分公司（非独立法人）的企业集团，集团负责人因故不能到现场的，可打电话通知工程所在地的分公司负责人对现场进行带班检查（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '发生触电事故时，营救人员可以在不切断电源的情况下营救（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑架子工属于特种作业人员（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '配电箱前不得堆放杂物，保持通道畅通且设置防雨防砸措施（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工单位在施工过程中遇到突发状况，可以擅自修改专项施工方案。（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '因规划调整、设计变更等原因确需调整的，修改后的专项施工方案应当重新审核和论证（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '塔式起重机尾部与周围建筑物及其他外围施工设施之间的安全操作距离不应小于0.8m（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '采用的移动式操作平台搭设是否符合要求？（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、符合',
        'B、不符合',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '移动式操作平台搭设不需要经过计算，搭设完成后即可投入使用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '移动式操作平台移动时，人员仍可以站在操作平台上作业，不需要下来（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '灭火器设置点的位置和数量应根据灭火器的最大保护距离确定，并应保证最不利点至少在灭火器的保护范围内（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '现场电工有其他事情不能及时接线时，作业人员可私自进行接线（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '事故发生后，现场人员应立即报告本单位负责人，单位负责人接到报告后，应当于2小时内向事故发生地县级以上人民政府安全生产监督管理部门和负有安全生产监督管理职责的有关部门报告（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '事故发生后，有关单位和人员应当妥善保护事故现场以及相关证据，任何单位和个人不得破坏事故现场、毁灭相关证据（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '专项施工方案只能由总承包单位编制，专业分包单位不得编制（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '脚手架搭设过程中，因人员不停的走动，故不需要佩戴安全带（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '作业人员站在有防护栏杆的吊篮内，不需要再佩戴安全带（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮不仅可以运送人员上下，还可以运输材料（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全锁必须在有效期内使用 超期必须由专业厂检测合格后方可使用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '因高处坠落事故为我国高发事故，故图片中存在的隐患为重大事故隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '塔式起重机安装完成后，不要安装单位自检，只需进行联合验收即可（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '塔式起重机顶升、加节、附着完成后不需要验收即可投入使用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '检测检验机构对检测合格的施工起重机械应当出具安全合格证明文件，并对检测结果负责（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '工程开工后，只需要向从事危险性较大的分部分项工程作业人员交底，对一般性工作的不需要进行交底（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '搭设高度超过8m的模板支撑体系在搭设完成后，施工单位、监理单位应当组织相关人员进行验收。验收合格的，经施工单位项目技术负责人及总监理工程师签字确认后，方可进入下一道工序。（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑架子工不属于特种作业人员（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《施工现场临时用电安全技术规范》JGJ46要求，配电室的建筑物和构筑物的耐火等级不低于3级（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '总配电室门应朝外开，室内应配置挡鼠板、消防器材、绝缘橡胶垫、应急照明（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '配电室应远离电源，并设置在灰尘少、潮气少、无腐蚀介质及道路通畅的地方（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '有限空间作业应坚持“先通风、后检测、再作业”的原则（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '有限空间作业应严格坚持审批制度，未经审批不得进行作业（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '有限空间作业属于超过一定规模的危险性较大的分部分项工程（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '大型拆除作业必须编制施工方案，必要情况下应当组织专家进行论证（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '生产经营单位均应当建立应急救援队伍（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工单位以及宾馆、商场、娱乐场所、旅游景区等人员密集场所经营单位，应当建立应急救援队伍（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '小型企业或者微型企业等规模较小的生产经营单位，可以不建立应急救援队伍，但应当指定兼职的应急救援人员，并且可以与邻近的应急救援队伍签订应急救援协议。（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '企业安全生产管理制度的核心是安全生产责任制（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全生产责任制是根据我国安全生产方针“安全第一、预防为主、综合治理”和安全生产法规建立的各级领导、职能部门、工程技术人员、岗位操作人员在劳动生产过程中对安全生产层层负责的制度。（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '企业负责人的安全生产责任制不包括督促、检查本单位的安全生产工作，及时消除生产安全事故隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中易燃易爆品库房，除配备灭火器外，还需配备消防砂箱等（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，箱体与箱门采用的连接线符合规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '配电箱的重复接地设置符合规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '悬挑脚手架与卸料平台的悬挑梁锚固螺栓均应采用双螺母（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，钢丝绳卡扣设置满足规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '钢丝绳采用卡扣进行紧固时，钢丝绳卡扣可以在钢丝绳上交替布置（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '采用高处作业吊篮进行高空作业时，人员可以从吊篮内翻出进入楼内（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '采用高处作业吊篮进行高空作业时，可以在吊篮内使用人字梯登高作业（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工现场临时用电必须满足TN-S接零保护系统要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中总配电柜的布设满足规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，消防器材配备不足，只缺少消防铲（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '灭火器应每月检查一次，若存在过期失效，应立即更换（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场“五临边”中包括楼梯边（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中卸料平台钢丝绳卡扣数量满足规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '在临空一侧除设置防护栏杆外，还应采用密目式安全立网进行封闭（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '三级开关箱内可以存放手套、帽子等易燃品（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '卸料平台锚固螺栓应采用单螺母，外露丝扣不少于3个丝扣（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中采用的登高设施是否满足规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '室内进行2.5米的高空作业可以不用佩戴安全带（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '采用梯子进行登高作业长度不足时，可以接长使用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场“五临边”包括沟、坑，槽和深基础周边（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '每台用电设备必须有各自专用的开关箱，严禁用同一个开关箱直接控制2台及2台以上用电设备（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '开关箱内的电器应先安装在金属或非木质阻燃绝缘电器安装板上（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中水处理池模板支撑体系属于超过一定规模的危险性较大的分部分项工程（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '本工程水处理池模板支撑体系专项施工方案进行专家论证时，可以邀请本单位总工程师以专家身份参加论证（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工过程中因外部因素发生变化，修改专项施工方案后，不用再重新执行审批手续（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中做法是否正确？（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '处于起重机臂架回转范围内的通道，应搭设安全防护棚（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮的安全锁应完好有效，严禁使用超过有效标定期限的安全锁（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《安全生产法》规定，生产经营单位可以不为从业人员配备相应的安全防护用品，安全防护用品应由从业人员自行配备（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: 'PE零线处在配电室或总配电箱处做重复接地外，还必须在配电系统的中间处和末端处做重复接地（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '电梯井口应设置防护门，其高度不小于1.5m，防护门地段距地面高度不应大于50mm，并应设挡脚板（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '电梯井道内应每隔2层且不大于10m加一道安全平网（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '附着式升降脚手架专项施工方案可以不经总监理工程师签字，只需专业监理工程师签字即可（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '监理单位发现施工单位未按照专项施工方案施工的，应当要求其进行整改；情节严重的，应当要求其暂停施工（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工单位未按规定编制危大工程专项施工方案的，依照《建设工程安全生产管理条例》对单位进行处罚，并暂扣安全生产许可证30日（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮上限位挡板与悬挂机构的间距不小于900mm（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中电梯井道口防护设置是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '电梯井除设置固定式临边防护栏外，还需在电梯井井道内设置安全水平网（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中临边防护设置是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '防护栏杆的立杆和横杆的设置、固定及连接，应确保防护栏杆在上下横杆和立杆任何部位处，均能承受任何方向1KN的外力作用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮的悬挂装置可以不加设前支腿，放置在女儿墙上（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '电工应每天对现场电箱和用电设备进行巡检（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中PE线接法是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '在TN接零保护系统中，PE零线应单独敷设。重复接地线必须与PE线相连接，严禁与N线相连接（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中箱体与箱门采用的连接线是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '在高处作业吊篮的安全锁上应固定清晰的标定铭牌。铭牌中应有标定机构、装置编号和有效日期等信息（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '可燃材料堆场及其加工场、易燃易爆品库房不应布置在架空电力线下（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中钢丝绳应及时报废进行更换（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场电工应每天对现场配电系统及用电设备进行检查（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '“电工安装、巡检、维修、拆除”工作记录可指定电工代管，每周由项目经理审核认可，并应在临时用电工程拆除后统一归档（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中采用的登高设备符合《建筑施工高处作业安全技术规范》JGJ80规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80规范要求，当登高高度超过8m时，应设置梯间平台（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，吊篮上钢丝绳夹得数量满足规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '钢丝绳夹设置时，应把夹座扣在钢丝绳的工作段上，U型螺栓扣在钢丝绳的尾端上。钢丝绳夹不得在钢丝绳上交替布置（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中作业人员未佩戴安全帽可以进入施工现场从事简单的工作（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全防护用品购买费用可纳入安全文明施工措施费用中（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '超过一定规模的危险性较大的分部分项工程组织专家论证后，结果显示未通过，则根据专家意见修改专项施工方案后，可不在重新组织专家论证（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '专家论证会后，应当形成论证报告，对专项施工方案提出通过、修改后通过或者不通过的一致意见。专家对论证报告负责并签字确认（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中电箱内设置活动插头是否符合规范要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、符合',
        'B、不符合',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示电箱中用电设备接线是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: 'PE线上严禁装设开关或熔断器，严禁通过工作电流，且严禁断线（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中为高处作业吊篮安全钢丝绳下端安装的重砣是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '附着式升降脚手架提升过程中可以将材料放置在走道板上（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建设工程施工现场消防安全技术规范》GB50720规范要求，临时用房建筑面积之和大于1000m2或在建工程单体体积大于10000m³时，应设置临时室外消防给水系统（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '室外消火栓应沿在建工程、临时用房和可燃材料堆场及其加工场均匀布置，与在建工程、临时用房和可燃材料堆场及其加工场的外边线的距离不应小于5m（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场人员进出的通道口可以不设置安全防护棚（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '当建筑高度大于24m并采用木质板搭设时，应搭设双层安全防护棚。两层防护的间距不应小于700mm（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全通道防护棚的长度与建筑物高度及可能坠落半径无关（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '进入施工现场应正确佩戴安全防护用品（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '企业负责人、项目经理、其他管理人员在施工现场发现作业人员未佩戴安全帽，均有权要求其正确佩戴后再进行作业（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '基坑开挖时只需要在基坑外设置排水沟和挡水坎即可，基坑内无需设置排水沟（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中落地式脚手架剪刀撑设置是否正确（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《职业病防治法》，生产经营单位应对从事接触职业危害因素作业的劳动者上岗前、在岗期间、离岗时必须进行职业健康检查（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '项目专职安全生产管理人员应当对专项施工方案实施情况进行现场监督，对未按照专项施工方案施工的，应当要求立即整改，并及时报告项目负责人，项目负责人应当及时组织限期整改（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工单位应当按照规定对危大工程进行施工监测和安全巡视，发现危及人身安全的紧急情况，应当立即组织作业人员撤离危险区域（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '操作平台应通过设计计算，并应编制专项施工方案（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场三级开关箱应满足“一机、一闸、一漏、一箱”要求（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '配电箱、开关箱周围应有足够2人同时工作的空间和通道（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '离开特种作业岗位达半年以上的特种作业人员，应当重新进行实际操作考核，经确认合格后方可上岗作业（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '工作时间前后在工作场所内，从事与工作有关的预备性或者收尾性工作受到事故伤害，不属于工伤（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '吊篮两端应设保险绳，作业人员要挂安全带，安全带不得挂在吊篮升降用的钢丝绳上（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '吊篮第一次组装后要经荷载试验合格后，方可投入使用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '基坑开挖出的土方，不得堆于基坑边，以免引起地面堆载超负荷（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '作业人员高空作业时要有安全立足点，垂直作业要进行隔离防护，光线不足的地方要设置照明灯（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '现浇混凝土的梁、板模板支撑的立柱，要经过设计计算确定其间距和纵、横向水平杆及横向斜撑、剪刀撑的设置（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '模板支撑系统必须形成一个整体，用同一种材料搭设，立杆底部要固定，必须加底座或垫板（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '模板支撑体系搭设过程中，可以在顶部集中堆放物料（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '在建工程（含脚手架）的外侧边缘与外电架空线路的边线间小于安全操作距离时，在建工程要设置防护措施（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '在建工程不得在外电架空线路正下方施工、搭设作业棚、建造生活设施堆放物料器材（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '外电架空线路架设防护设施时，必须经过有关部门批准，采用线路暂时停电或其他可靠的安全技术措施，并应有电气工程技术人员和专职安全人员监护（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工现场临时用电必须符合现行行业标准《施工现场临时用电安全技术规范》JGJ46规定，采用电源中性点直接接地，工作零线与保护零线分开设置，不得混接（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '在TN接零保护系统中，通过总漏电保护器的工作零线与保护零线之间不得再做电气连接（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '照明灯具的金属外壳必须与PE线相连接，照明开关箱内必须装设隔离开关、短路与过载保护器和漏电保护器（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '电缆线路不得拖地及拖地穿过道路敷设，不得直接架空缠绕穿越脚手架敷设，不得缠绕树木敷设（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '现场配电线路可使用架空线路或电缆线路，架空线路必须使用绝缘导线（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '配电箱内电器、规格参数与设备容量匹配，按规定位置紧固在电器安装板上，严禁用其他金属丝代替熔丝（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '凡用电设备在5台及以上或总容量在50KW及以上着，都要单独编制用电施工组织设计（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '临时用电组织设计变更时，可以不履行“编制、审核、批准”程序（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '一旦有人触电，应立即切断电源进行急救，电气设备着火，也应立即切断电源，使用可用于扑来电气火灾的灭火器或干砂灭火（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '道路交通及火灾事故自发生之日起7日内，事故造成的伤亡人数发生变化的，应当及时补报.（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '发生触电（电击）应在现场立即组织抢救，同时向医院紧急求救（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '搭设龙门架（井字架）时，要设置缆风绳来保持架体稳定，缆风绳要使用钢丝绳，并用地锚在地面固定（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '龙门架（井字架）超过30m时，也应采用缆风绳固定（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '卷扬机用的钢丝绳应是合格产品，并符合设计的安全系数的要求，不得有磨损、锈蚀、缺油、断丝。超过标准要立即更换，绳卡应是合格产品并与钢丝绳匹配，钢丝绳要有过路保护，运行时不得拖地（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '龙门架与楼层间应设置卸料平台，平台跳板要满铺，两侧应有1.2m高的防护栏杆，并用密目式安全网全封闭（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '物料提升机安装完成，必须经相关单位、人员验收合格，并签字后方可投入使用（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '电梯司机要经过专门的培训学习，经考核发证后方可上岗作业，每班作业前都要按规定进行试车检查，交接班时要做好记录。（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '为确保安装拆除过程中的安全，必须预先制定安装、拆卸工程专项施工方案，并由经过专门培训且取得相应操作资格证书的人员操作（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '根据相关规范',
      point: '1',
    },
  ],
};

export default quiz;
