const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产基础题库 - 单选题',
  quizSynopsis: '本测验涵盖建设工程安全生产基础题库的单选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '241',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '按照《建筑施工现场标志设置技术规程》，上图所示安全标志为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、禁止标志',
        'B、警告标志',
        'C、指令标志',
        'D、提示标志',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、警告标志。',
      explanation: '',
      point: '1',
    },
    {
      question: '黄颜色背景的安全标志属于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、禁止标志',
        'B、警告标志',
        'C、指令标志',
        'D、提示标志',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、警告标志。',
      explanation: '',
      point: '1',
    },
    {
      question: '按照《建筑施工高处作业安全技术规程》要求，安全带正确使用的方法是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、低挂高用',
        'B、高挂低用',
        'C、高挂高用',
        'D、低挂低用',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、高挂低用 。',
      explanation: '',
      point: '1',
    },
    {
      question: '按《危险性较大的分部分项工程安全管理规定》住建部31号文规定，基坑开挖深度超过（）米，专项施工方案应组织专家论证。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、5',
        'B、6',
        'C、7',
        'D、8',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、5。',
      explanation: '',
      point: '1',
    },
    {
      question: '基坑边（）范围内，严禁堆放超过设计荷载的材料',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、0.8米',
        'B、1米',
        'C、1.5米',
        'D、2米',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、1.5米。',
      explanation: '',
      point: '1',
    },
    {
      question: '按照《施工脚手架通用规范》要求，上图所示为哪种形式的模板支架',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、碗扣式钢管脚手架',
        'B、盘扣式钢管脚手架',
        'C、扣件式钢管脚手架',
        'D、门式钢管脚手架',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、扣件式钢管脚手架。',
      explanation: '',
      point: '1',
    },
    {
      question: '发生模板支架倒塌事故后,组织调查处理按照( )的原则,严肃处理事故',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、四不放过',
        'B、教育与惩罚相结合',
        'C、领导责任制',
        'D、过错性',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、四不放过。',
      explanation: '',
      point: '1',
    },
    {
      question: '满堂脚手架自由端长度为立杆伸出顶层水平杆中心线至中心点的距离不应超过（）mm',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、400',
        'B、500',
        'C、600',
        'D、700',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、500。',
      explanation: '',
      point: '1',
    },
    {
      question: '按《危险性较大的分部分项工程安全管理规定》，悬挑式脚手架的专项施工方案应由（）主持编制',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、项目负责人',
        'B、项目技术负责人',
        'C、企业负责人',
        'D、施工单位技术负责人',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、项目负责人。',
      explanation: '',
      point: '1',
    },
    {
      question: '张某在脚手架上施工时，发现部分扣件松动可能发生倒塌，随立即停止作业，撤离到安全区域，这属于从业人员行使的（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．知情权',
        'B．拒绝权',
        'C．紧急避险权',
        'D．检举权',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C．紧急避险权。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《生产安全事故报告和调查处理条例》，事故发生后，单位负责人接到报告后，应当于（ ）内向事故发生地县级以上人民政府安全生产监督管理部门和负有安全生产监督管理职责的有关部门报告。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、立即',
        'B、1小时',
        'C、2小时',
        'D、3小时',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、1小时。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《施工现场临时用电安全技术规范》要求，临时用电施工组织设计由（）编制',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、土建技术负责人',
        'B、电气工程技术人员',
        'C、项目负责人',
        'D、企业负责人',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、电气工程技术人员。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《建筑施工企业负责人及项目负责人施工现场带班暂行办法》规定，项目负责人每月带班时间不少于施工时间的',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、70%',
        'B、80%',
        'C、90%',
        'D、100%',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、80%。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《建筑施工企业负责人及项目负责人施工现场带班暂行办法》规定，企业负责人要定期带班检查，每月检查时间不少于工作日',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、20%',
        'B、25%',
        'C、30%',
        'D、35%',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、25%。',
      explanation: '',
      point: '1',
    },
    {
      question: '《安全生产法》规定，生产经营单位必须为从业人员提供符合国家标准或行业标准的',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、劳动防护用品',
        'B、劳动工具',
        'C、福利待遇',
        'D、工作服',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、劳动防护用品 。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《中华人民共和国消防法》规定，我国消防工作执行（）的方针',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、预防为主、防消结合',
        'B、以防为主、以消为主',
        'C、安全第一、预防为主、综合治理',
        'D、谁主管、谁负责、谁在岗、谁负责',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、预防为主、防消结合。',
      explanation: '',
      point: '1',
    },
    {
      question: '火灾事故发生后（ ）内，若伤亡人数发生变化应及时补报',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、7天',
        'B、10天',
        'C、15天',
        'D、30天',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、7天。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工五大伤亡事故类别中，（）事故的发生率最高、危险性极大。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、坍塌',
        'B、高处坠落',
        'C、物体打击',
        'D、机械伤害',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、高处坠落。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，导致安全事故发生最主要的因素是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、人的不安全行为',
        'B、物的不安全状态',
        'C、管理缺陷',
        'D、物的不安全因素',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、人的不安全行为。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，此次事故属于（）事故。（只考虑人员死亡，不考虑重伤和直接经济损失）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、一般事故',
        'B、较大事故',
        'C、重大事故',
        'D、特别重大事故',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、一般事故。',
      explanation: '',
      point: '1',
    },
    {
      question: '作业人员在吊篮内施工应佩戴（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全绳',
        'B、安全带',
        'C、安全网',
        'D、安全帽',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、安全带。',
      explanation: '',
      point: '1',
    },
    {
      question: '动火作业前应办理（）手续，审批后方可进行作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、动火证',
        'B、作业证',
        'C、使用证',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、动火证。',
      explanation: '',
      point: '1',
    },
    {
      question: '乙炔瓶压力表处应安装（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、止回阀',
        'B、截止阀',
        'C、减压阀',
        'D、回火阀',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、回火阀。',
      explanation: '',
      point: '1',
    },
    {
      question: '使用灭火器进行灭火时，灭火器喷射口应对准火焰（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、上空',
        'B、上部',
        'C、中部',
        'D、根部',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、根部。',
      explanation: '',
      point: '1',
    },
    {
      question: '危险性较大的分部分项工程施工时，（）应在现场进行监督检查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、项目负责人',
        'B、技术负责人',
        'C、专职安全员',
        'D、施工员',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、专职安全员。',
      explanation: '',
      point: '1',
    },
    {
      question: '发生伤亡事故应（）报告本单位负责人，本单位负责人（）报告事故发生地县级以上人民政府安全生产监督管理部门和负有安全生产监督管理职责的有关部门。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、立即，1小时',
        'B、1小时，1小时',
        'C、立即，2小时',
        'D、1小时，立即',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、立即，1小时 。',
      explanation: '',
      point: '1',
    },
    {
      question: '发生伤亡事故后，事故现场的有关人员应当首先（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、抢救受伤人员',
        'B、保护事故现场',
        'C、抢救生产设备、物资',
        'D、保护财产',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、抢救受伤人员 。',
      explanation: '',
      point: '1',
    },
    {
      question: '管理人员和作业人员每年至少进行（）次安全生产教育培训，其教育培训情况记入个人工作档案。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1',
        'B、2',
        'C、3',
        'D、4',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1 。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，作业人员还需要佩戴哪种安全防护用品（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全帽',
        'B、安全网',
        'C、安全带',
        'D、密目网',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、安全带。',
      explanation: '',
      point: '1',
    },
    {
      question: '临边防护高度不低于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、0.8米',
        'B、1.0米',
        'C、1.2米',
        'D、1.5米',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、1.2米。',
      explanation: '',
      point: '1',
    },
    {
      question: '依上图所示，针对该工人行为应设置哪种安全警示标志牌（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、禁止',
        'B、警告',
        'C、指示',
        'D、指令',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、禁止。',
      explanation: '',
      point: '1',
    },
    {
      question: '电焊工接触到的主要职业危害为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、高温',
        'B、噪声',
        'C、振动',
        'D、电焊烟尘',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、电焊烟尘。',
      explanation: '',
      point: '1',
    },
    {
      question: '建设工程项目应当配备专职安全生产管理人员，其中1万-5万m2的建筑工程总承包单位至少应配备()专职安全生产管理人员',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1名',
        'B、2名',
        'C、3名',
        'D、4名',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、2名。',
      explanation: '',
      point: '1',
    },
    {
      question: '事故造成17人死亡，1人重伤，该事故等级为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、一般事故',
        'B、较大事故',
        'C、重大事故',
        'D、特别重大事故',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、重大事故。',
      explanation: '',
      point: '1',
    },
    {
      question: '本次事故由（）组织事故调查组进行调查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、国务院或者国务院授权有关部门',
        'B、省、自治区、直辖市人民政府',
        'C、设区的市人民政府',
        'D、县级人民政府',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、省、自治区、直辖市人民政府。',
      explanation: '',
      point: '1',
    },
    {
      question: '下列预防触电的措施正确的是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、加强用电管理，建立健全管理制度、安全操作规程，并严格执行',
        'B、使用、维护、检修电气设备，不必按照安全操作规程进行',
        'C、未取得特种作业操作资格证，依然可以进行接电作业',
        'D、电气设备除进场进行验收检查外，其余时间不用检查',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、加强用电管理，建立健全管理制度、安全操作规程，并严格执行。',
      explanation: '',
      point: '1',
    },
    {
      question: '氧气与乙炔在使用过程中应间隔（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、5米',
        'B、6米',
        'C、7米',
        'D、8米',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、5米。',
      explanation: '',
      point: '1',
    },
    {
      question: '氧气、乙炔距离明火应保持（）以上安全距离',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、5米',
        'B、8米',
        'C、10米',
        'D、15米',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、10米。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80要求，电梯井内水平防护应每隔（）层且不大于（）米',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3，15',
        'B、2,10',
        'C、4,20',
        'D、5,25',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、2,10。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80要求，电梯井口防护门高度不小于（）米',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1.5',
        'B、1.8',
        'C、2.0',
        'D、2.5',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1.5。',
      explanation: '',
      point: '1',
    },
    {
      question: '钢丝绳在（）状况下还可继续使用。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、扭结',
        'B、钢丝绳直径局部增大',
        'C、钢丝绳内部的绳股突出',
        'D、集中断丝两根以上',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、集中断丝两根以上。',
      explanation: '',
      point: '1',
    },
    {
      question: '当水平洞口短边边长大于或等于1500mm时，除在洞口侧设置高度不小于（）米的防护栏杆外，还应采用安全平网封闭',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1.2',
        'B、1.5',
        'C、1.8',
        'D、2.0',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1.2。',
      explanation: '',
      point: '1',
    },
    {
      question: '防护栏杆应能承受任何方向（）KN的外力作用',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1',
        'B、2',
        'C、3',
        'D、4',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1 。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80要求，借助梯子登高作业时，梯子与地面的夹角不得小于',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、45°',
        'B、60°',
        'C、65°',
        'D、75°',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、75°。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80要求，以下说法错误的有（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、梯子与地面的夹角不得小于75°',
        'B、踏步之间的距离不得大于300mm',
        'C、梯子高度不够时，可接长使用',
        'D、同一梯子上不得两人同时作业',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、梯子高度不够时，可接长使用。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80要求，悬挑式卸料平台悬挑长度不得大于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3米',
        'B、4米',
        'C、5米',
        'D、6米',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、5米。',
      explanation: '',
      point: '1',
    },
    {
      question: 'U型锚固螺栓距离悬挑梁端部不小于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、100mm',
        'B、150mm',
        'C、200mm',
        'D、250mm',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、200mm。',
      explanation: '',
      point: '1',
    },
    {
      question: '悬挑式卸料平台应均匀对称的设置（）道钢丝绳',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2',
        'B、3',
        'C、4',
        'D、5',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、4。',
      explanation: '',
      point: '1',
    },
    {
      question: '新工人入场三级安全教育培训为哪三级（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、公司、项目部、班组',
        'B、公司、分公司、项目部',
        'C、公司、安全部门、班组',
        'D、公司、监理公司、项目部',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、公司、项目部、班组。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《生产经营单位安全培训规定》，高危行业的从业人员入场安全教育培训时间不得少于（）学时。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、32',
        'B、48',
        'C、50',
        'D、72',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、72。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《安全生产法》，生产经营单位主要负责人不依照规定保证安全生产所必需的资金投入，导致发生生产安全事故的，对生产经营单位的主要负责人给予（），对个人经营的投资人处（）罚款',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、警告，一万元以上五万元以下',
        'B、撤职，二万元以上十万元以下',
        'C、警告，二万元以上二十万元以下',
        'D、撤职，二万元以上二十万元以下',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、撤职，二万元以上二十万元以下。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《安全生产法》，生产经营单位发生重大事故，且影响特别恶劣，最高可处（）罚款',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、500万',
        'B、1000万',
        'C、5000万',
        'D、10000万',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、5000万。',
      explanation: '',
      point: '1',
    },
    {
      question: '生产经营单位（）是本单位安全生产第一责任人。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、主要负责人',
        'B、项目经理',
        'C、副总经理',
        'D、班组长',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、主要负责人。',
      explanation: '',
      point: '1',
    },
    {
      question: '压力容器、压力管道发生爆炸事故后，为防止事故扩大，压力容器所属管道阀门应（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、迅速关闭',
        'B、迅速打开',
        'C、缓慢打开',
        'D、缓慢关闭',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、迅速关闭。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工人员进入现场作业前应由（）进行书面交底，并由双方和项目专职安全生产管理人员共同签字确认，存档备查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、项目负责人',
        'B、技术负责人',
        'C、生产经理',
        'D、施工管理人员',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、施工管理人员。',
      explanation: '',
      point: '1',
    },
    {
      question: '实行施工总承包的建设工程，发生生产安全事故由（）负责上报',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、施工单位',
        'B、施工总承包单位',
        'C、业主方',
        'D、分包单位',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、施工总承包单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '总承包单位和分包单位应当在施工合同中明确安全管理范围，承担各自相应的安全管理责任，分包单位不服从总承包单位管理，发生生产安全事故，由（）承担主要责任',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、分包单位',
        'B、施工总承包单位',
        'C、施工班组',
        'D、业主单位',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、分包单位 。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工中发生事故时，()应当采取紧急措施减少人员伤亡和事故损失，并按照国家有关规定及时向有关部门报告',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、建设单位',
        'B、监理单位',
        'C、相关责任人员',
        'D、建筑施工企业',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、建筑施工企业。',
      explanation: '',
      point: '1',
    },
    {
      question: '从业人员超过（）人，应当设置安全生产管理机构或配备专职安全生产管理人员',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、100',
        'B、150',
        'C、200',
        'D、250',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、100。',
      explanation: '',
      point: '1',
    },
    {
      question: '国家对严重危及生产安全的工艺、设备实行（）制度',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、限制使用',
        'B、淘汰',
        'C、报废',
        'D、 翻新',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、淘汰 。',
      explanation: '',
      point: '1',
    },
    {
      question: '有限空间作业前应进行气体检查，氧气含氧量应为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、16% -22%',
        'B、17%-23%',
        'C、18%-22%',
        'D、18%-23%',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、18%-22%。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业应当建立健全( )制度，加强对职工安全生产的教育培训；未经安全生产教育培训的人员，不得上岗作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全生产教育培训',
        'B、安全技能学习激励',
        'C、劳保用品和学习资料统一配发',
        'D、岗位责任',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、安全生产教育培训 。',
      explanation: '',
      point: '1',
    },
    {
      question: '生产经营单位应当制定本单位应急预案演练计划，根据本单位的事故风险特点，每年组织（）综合应急演练和专项应急演练',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、一次',
        'B、两次',
        'C、三次',
        'D、四次',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、一次。',
      explanation: '',
      point: '1',
    },
    {
      question: '消防安全重点单位的应急预案，至少（）进行一次演练',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、每季度',
        'B、每半年',
        'C、每年',
        'D、每月',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、每半年。',
      explanation: '',
      point: '1',
    },
    {
      question: '消防工作的方针（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、预防为主、防消结合',
        'B、政府统一领导、部门依法监管',
        'C、公民积极参与、单位方面负责',
        'D、消灭为主，防消结合',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、预防为主、防消结合。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《生产经营单位安全培训规定》，生产经营单位负责（）从业人员的培训工作。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全培训机构',
        'B、政府主管部门',
        'C、本单位',
        'D、其他单位',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、本单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《安全生产法》，特种作业人员必须经专门的安全技术培训，取得（）后，方可上岗作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、合格证',
        'B、上岗证',
        'C、特种作业操作资格证',
        'D、安全资格证',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、特种作业操作资格证。',
      explanation: '',
      point: '1',
    },
    {
      question: '对职工进行安全生产、劳动保护方面的法律、法规的宣传教育，从法制角度认识安全生产的重要性，要通过学法、知法来守法，这种教育形式属于()',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全知识教育',
        'B、安全法制教育',
        'C、三级安全教育',
        'D、遵章守纪、自我保护能力教育',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、安全法制教育。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮内作业人员不应超过（）人',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1人',
        'B、2人',
        'C、3人',
        'D、4人',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、2人。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮安全锁（）标定一次',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、每半年',
        'B、每一年',
        'C、每两年',
        'D、每五年',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、每一年。',
      explanation: '',
      point: '1',
    },
    {
      question: '（）是我国建筑施工行业五大伤害之首',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、高处坠落',
        'B、坍塌',
        'C、物体打击',
        'D、触电',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、高处坠落。',
      explanation: '',
      point: '1',
    },
    {
      question: '职业病防治工作坚持（）方针',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、预防为主、安全第一',
        'B、预防为主、防治结合',
        'C、分类管理、综合治理',
        'D、预防为主、综合治理',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、预防为主、防治结合。',
      explanation: '',
      point: '1',
    },
    {
      question: '用人单位应当按照国务院安全生产监督管理部门的规定，定期对工作场所进行职业病（）检测、评价',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、危害因素',
        'B、风险源',
        'C、危险因素',
        'D、隐患',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、危害因素。',
      explanation: '',
      point: '1',
    },
    {
      question: '单、双排脚手架拆除作业必须（）逐层进行',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、由上而下',
        'B、由下而上',
        'C、同时拆除',
        'D、由内向外',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、由上而下 。',
      explanation: '',
      point: '1',
    },
    {
      question: '事故发生后，事故单位负责人应当于（）内向事故发生地县级以上安全生产监督管理部门和负有安全生产监督管理职责的有关部门报告',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、半小时',
        'B、1小时',
        'C、2小时',
        'D、3小时',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、1小时。',
      explanation: '',
      point: '1',
    },
    {
      question: '建设项目的职业病防护设施应当与主体工程（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、同时设计，同时投入生产',
        'B、同时设计、同时施工',
        'C、同时设计、同时施工、同时投入生产和使用',
        'D、同时投入生产、同时使用',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、同时设计、同时施工、同时投入生产和使用。',
      explanation: '',
      point: '1',
    },
    {
      question: '特种作业人员应年满（）岁，且不超过国家法定退休年龄',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、14',
        'B、16',
        'C、18',
        'D、20',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、18。',
      explanation: '',
      point: '1',
    },
    {
      question: '特种作业人员必须经专门的安全技术培训并考核合格，取得（）后，方可上岗作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、特种作业合格证',
        'B、特种作业上岗证',
        'C、特种作业操作证',
        'D、特种作业资格证',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、特种作业操作证。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全生产管理制度体系的建立应贯彻（）的方针',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全第一、预防为主、综合治理',
        'B、预防为主、综合治理',
        'C、防消结合、预防为主',
        'D、预防为主、防治结合',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、安全第一、预防为主、综合治理。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全生产制度体系中最根本、最核心的制度是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全生产教育培训制度',
        'B、安全生产检查制度',
        'C、安全生产责任制',
        'D、安全生产例会制度',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、安全生产责任制。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《生产安全事故报告和调查处理条例》，事故发生单位负责人接到事故报告后，应当立即（），或采取有效措施，组织抢救，防止事故扩大，减少人员伤亡和财产损失',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、上报事故',
        'B、保护财产',
        'C、组织转移贵重物品',
        'D、启动事故应急预案',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、启动事故应急预案。',
      explanation: '',
      point: '1',
    },
    {
      question: '采取“四新技术”时，安全技术交底应分（）级',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1',
        'B、2',
        'C、3',
        'D、4',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、2 。',
      explanation: '',
      point: '1',
    },
    {
      question: '违反《建设工程安全生产管理条例》，施工单位未按照国家有关规定在施工现场设置消防水源的，责令限期整改；逾期未整改的，（）按照安全生产法的有关规定处以罚款',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、暂扣资质证书',
        'B、责令停业整顿',
        'C、吊销营业执照',
        'D、追究刑事责任',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、责令停业整顿。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据建筑企业资质分类，施工总承包特级资质企业安全生产管理机构应配备专职安全生产管理人员不少于（）人。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、4',
        'B、5',
        'C、6',
        'D、7',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、6。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据建筑企业资质分类，施工专业承包一级资质企业安全生产管理机构应配备专职安全生产管理人员不少于（ ）人。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、4',
        'B、3',
        'C、2',
        'D、5',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、3。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据建筑企业资质分类，劳务分包企业安全生产管理机构应配备专职安全生产管理人员不少于（ ）人。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、4',
        'B、5',
        'C、3',
        'D、2',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、2。',
      explanation: '',
      point: '1',
    },
    {
      question: '危险性较大的分部分项工程专项施工方案由（）主持编制',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、项目技术负责人',
        'B、项目经理',
        'C、生产经理',
        'D、安全员',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、项目经理。',
      explanation: '',
      point: '1',
    },
    {
      question: '对于超过一定规模的危险性较大的分部分项工程，（）组织专家论证',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、施工单位',
        'B、建设单位',
        'C、监理单位',
        'D、专业分包',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、施工单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '对于专家论证所邀请的专家应符合专业要求，人数不得少于（）人',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、4',
        'B、5',
        'C、6',
        'D、7',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、5。',
      explanation: '',
      point: '1',
    },
    {
      question: '事故隐患分为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、一般隐患与重大隐患',
        'B、一般隐患与较大隐患',
        'C、较大隐患与重大隐患',
        'D、重大隐患与特大隐患',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、一般隐患与重大隐患。',
      explanation: '',
      point: '1',
    },
    {
      question: '基坑开挖深度超过（）米为危险性较大的分部分项工程，开挖深度超过（）米为超过一定规模的危险性较大的分部分项工程',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3，5',
        'B、4，5',
        'C、5、3',
        'D、5、4',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、3，5。',
      explanation: '',
      point: '1',
    },
    {
      question: '危大工程实施过程中（）应当在现场监督方案的实施',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、项目经理',
        'B、项目技术负责人',
        'C、专职安全生产管理人员',
        'D、单位主要负责人',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、专职安全生产管理人员。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工单位的负责人在事故发生后应及时组织抢险，消除安全事故隐患，（）报告生产安全事故',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、及时、如实',
        'B、调查清楚',
        'C、准时、真实',
        'D、及时、全面',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、及时、如实。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，吊篮存在哪方面的问题（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、限位器损坏',
        'B、无限位挡板',
        'C、钢丝绳断裂',
        'D、报警器损坏',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、限位器损坏。',
      explanation: '',
      point: '1',
    },
    {
      question: '项目进场时，由（）主持编制危险源辨识及风险评价结果；',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、项目技术负责人',
        'B、项目安全负责人',
        'C、项目生产经理',
        'D、项目负责人',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、项目负责人。',
      explanation: '',
      point: '1',
    },
    {
      question: '项目部一般在（）部位设置施工现场重大危险源公示牌',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、大门口',
        'B、办公区',
        'C、施工现场',
        'D、主通道',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、主通道。',
      explanation: '',
      point: '1',
    },
    {
      question: '较大事故由事故发生地（）负责调查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、国务院',
        'B、省级政府',
        'C、设区的市级政府',
        'D、县级人员政府',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、设区的市级政府。',
      explanation: '',
      point: '1',
    },
    {
      question: '超过一定规模的危险性较大的分部分项工程施工期间，（）应到施工现场进行带班检查。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、企业技术部门负责人',
        'B、企业负责人',
        'C、总工程师',
        'D、安全总监',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、企业负责人。',
      explanation: '',
      point: '1',
    },
    {
      question: '落地式脚手架超过（）米属于危险性较大的分部分项工程；',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、20',
        'B、24',
        'C、30',
        'D、35',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、24。',
      explanation: '',
      point: '1',
    },
    {
      question: '双排脚手架剪刀撑的搭接长度不应小于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、0.8米',
        'B、1米',
        'C、1.5米',
        'D、2米',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、1米 。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、脚手架内立杆与建筑物间未采取防护措施',
        'B、连墙件设置不规范',
        'C、未设置剪刀撑',
        'D、未设置水平的安全网',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、脚手架内立杆与建筑物间未采取防护措施。',
      explanation: '',
      point: '1',
    },
    {
      question: '双排脚手架内立杆与建筑物距离大于（）时必须进行封闭；',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、100mm',
        'B、150mm',
        'C、200mm',
        'D、250mm',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、150mm 。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《施工现场临时用电安全管理规定》JGJ46，施工现场临时用电应采用（）接零保护系统。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、TN',
        'B、TN-S',
        'C、TN-C',
        'D、TT',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、TN-S。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、未接保护零线',
        'B、箱体与箱门未采用编制软铜线连接',
        'C、电箱内存在“一闸多机”',
        'D、无漏电保护器',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、电箱内存在“一闸多机”。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场临时用电设备在（）台及以上或设备总容量在（）KW及以上者，应编制用电组织设计',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、5,50',
        'B、10,50',
        'C、50,5',
        'D、50,10',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、5,50。',
      explanation: '',
      point: '1',
    },
    {
      question: '发生触电事故后，首先要使触电者（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、做人工呼吸',
        'B、打强心剂',
        'C、迅速脱离电源',
        'D、人工体外心脏挤压',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、迅速脱离电源。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、作业人员未佩戴安全带',
        'B、作业人员未佩戴安全帽',
        'C、作业人员未佩戴护目镜',
        'D、未设置防倾覆措施',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、作业人员未佩戴安全带。',
      explanation: '',
      point: '1',
    },
    {
      question: '坠落高度基准面（）米及以上有可能坠落的高处进行的作业为高处作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3',
        'B、4',
        'C、2',
        'D、5',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、2。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、脚手架未设置扫地杆',
        'B、配电箱放置位置不合理',
        'C、未配备消防器材',
        'D、配电箱无标识标牌',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、配电箱放置位置不合理。',
      explanation: '',
      point: '1',
    },
    {
      question: '三级开关箱与用电设备的距离不得大于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1',
        'B、2',
        'C、3',
        'D、4',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、3。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、未做到工完料清',
        'B、洞口未设置防护措施',
        'C、后浇带接茬未清理',
        'D、钢筋无保护措施',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、洞口未设置防护措施。',
      explanation: '',
      point: '1',
    },
    {
      question: '上图所示，存在的安全隐患容易发生（）事故',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、高空坠落',
        'B、物体打击',
        'C、触电',
        'D、坍塌',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、物体打击。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《建设工程安全生产管理条例》，（）应当为施工现场从事危险作业人员办理意外伤害保险',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、建设行政主管部门',
        'B、施工单位',
        'C、市级以上人民政府',
        'D、建设单位',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、施工单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《施工现场临时用电安全技术规范》JGJ46规范要求，现场配电必须符合（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、三级配电，两级保护',
        'B、三级配电，三级保护',
        'C、TN系统',
        'D、三项四线制',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、三级配电，两级保护 。',
      explanation: '',
      point: '1',
    },
    {
      question: '临时用电组织设计应由（）组织编制',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、项目技术负责人',
        'B、电气工程技术人员',
        'C、项目负责人',
        'D、施工员',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、电气工程技术人员。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、楼梯边未进行防护',
        'B、洞口未进行防护',
        'C、台阶高度不符合要求',
        'D、台阶棱角未采取保护措施',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、楼梯边未进行防护 。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、材料未下垫',
        'B、未配备消防器材',
        'C、未入库存放',
        'D、无防雨措施',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、未配备消防器材。',
      explanation: '',
      point: '1',
    },
    {
      question: '火灾事故自发生之日起（）日内，事故造成的伤亡人数发生变化的，应当及时补报',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、14',
        'B、30',
        'C、8',
        'D、7',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、7。',
      explanation: '',
      point: '1',
    },
    {
      question: '《消防法》规定，禁止在具有火灾、爆炸危险的场所使用明火，因特殊情况需要使用明火作业的，应当按照规定事先办理（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、审批手续',
        'B、许可手续',
        'C、保险手续',
        'D、备案手续',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、审批手续。',
      explanation: '',
      point: '1',
    },
    {
      question: '我国安全生产月为每年（）月份',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、5',
        'B、6',
        'C、8',
        'D、9',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、6。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全生产月开始于（）年',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1990',
        'B、1991',
        'C、1992',
        'D、1993',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1990。',
      explanation: '',
      point: '1',
    },
    {
      question: '全国消防日一般为每年（）月份',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、9',
        'B、10',
        'C、11',
        'D、12',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、11。',
      explanation: '',
      point: '1',
    },
    {
      question: '《建设工程安全生产管理条例》规定，施工单位应当向作业人员提供（），并书面告知危险岗位的操作规程和违章操作的危害',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、劳动防护用品',
        'B、安全防护用具和安全防护服装',
        'C、安全防护用品',
        'D、个人防护用品',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、安全防护用具和安全防护服装。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工单位应当对管理人员和作业人员每年至少进行（）次安全生产教育培训',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1',
        'B、2',
        'C、3',
        'D、4',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、楼梯边未进行防护',
        'B、洞口未进行防护',
        'C、台阶高度不符合要求',
        'D、台阶棱角未采取保护措施',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、楼梯边未进行防护 。',
      explanation: '',
      point: '1',
    },
    {
      question: '楼梯边临边防护的高度不低于（）米。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1.2',
        'B、1.5',
        'C、1.8',
        'D、2.0',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1.2。',
      explanation: '',
      point: '1',
    },
    {
      question: '下列哪些属于危大工程？（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、搭设20m高度的落地式脚手架',
        'B、悬挑式脚手架',
        'C、超过2M的深基坑',
        'D、搭设高度超3米的满堂架',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、悬挑式脚手架。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工升降机地面防护栏杆高度不低于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1.2米',
        'B、1.5米',
        'C、1.8米',
        'D、2.0米',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、1.8米。',
      explanation: '',
      point: '1',
    },
    {
      question: '两台塔机之间的最小架设距离应保证处于低位的塔机的起重臂端部与另一台塔机的塔身之间至少有（）米的距离',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1.5',
        'B、2',
        'C、2.5',
        'D、3',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、2。',
      explanation: '',
      point: '1',
    },
    {
      question: '塔式起重机高度大于（）米且高于周围建筑的塔机，应在塔顶和臂架端部安装红色障碍指示灯。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、20',
        'B、30',
        'C、40',
        'D、50',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、30。',
      explanation: '',
      point: '1',
    },
    {
      question: '当安全防护棚为非机动车辆通行时，棚底至地面高度不应小于（）米。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3',
        'B、4',
        'C、5',
        'D、6',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、3 。',
      explanation: '',
      point: '1',
    },
    {
      question: '当建筑高度大于24m并采用木质板搭设时，应搭设双层安全防护棚，两层防护的间距不应小于（）毫米。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、600',
        'B、650',
        'C、700',
        'D、750',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、700 。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80规范要求，建筑高度大于30米时，安全防护棚搭设长度应不小于（）米。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3',
        'B、4',
        'C、5',
        'D、6',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、6。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中安全警示标志牌为哪一类安全标志（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、禁止标志',
        'B、警告标志',
        'C、指令标志',
        'D、提示标志',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、禁止标志。',
      explanation: '',
      point: '1',
    },
    {
      question: '我国安全色分为几类？（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3',
        'B、4',
        'C、5',
        'D、6',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、4 。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80规范要求，移动式操作平台搭设高度不得超过（）米',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、4',
        'B、5',
        'C、6',
        'D、7',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、5 。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、材料堆放杂乱',
        'B、木材堆放区无消防器材',
        'C、模板未下垫',
        'D、模板未进行覆盖',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、木材堆放区无消防器材。',
      explanation: '',
      point: '1',
    },
    {
      question: '一个计算单元内配置的灭火器数量不得少于（）具',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2',
        'B、3',
        'C、4',
        'D、5',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、2。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、配电箱内未设置漏电保护器',
        'B、配电箱内设置插座做活动连接',
        'C、配电箱内未设置断路器',
        'D、箱体与箱门未采用编织软铜线连接',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、配电箱内设置插座做活动连接。',
      explanation: '',
      point: '1',
    },
    {
      question: '开关箱中漏电保护器的额定漏电动作电流不应大于（）mA，额定动作时间不应大于（）S。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、100，0.1',
        'B、30,0.2',
        'C、30,0.1',
        'D、100,0.2',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、30,0.1。',
      explanation: '',
      point: '1',
    },
    {
      question: '室外220V灯具距地面不得低于（）米',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2.5',
        'B、3.5',
        'C、3',
        'D、4',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、3。',
      explanation: '',
      point: '1',
    },
    {
      question: '哪些生产经营单位应建立应急救援队伍？( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、互联网单位',
        'B、建筑施工单位',
        'C、工业园区',
        'D、制造单位',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、建筑施工单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '基坑开挖超过（ ）米，应编制专项施工方案',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2',
        'B、3',
        'C、4',
        'D、5',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、3。',
      explanation: '',
      point: '1',
    },
    {
      question: '危大工程实行分包并由分包单位编制专项施工方案时，专项施工方案应由（）及分包单位技术负责人共同审核签字并加盖单位公章',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、施工单位',
        'B、建设单位',
        'C、监理单位',
        'D、总承包单位',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、总承包单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '悬挑式脚手架搭设高度超过（）米，属于超过一定规模的危险性较大的分部分项工程',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、15',
        'B、20',
        'C、25',
        'D、30',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、20。',
      explanation: '',
      point: '1',
    },
    {
      question: '悬挑式脚手架固定端长度不应小于悬挑段长度的（）倍',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1.1',
        'B、1.2',
        'C、1.25',
        'D、1.3',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、1.25。',
      explanation: '',
      point: '1',
    },
    {
      question: '悬空作业所用的索具、脚手板、吊篮、吊笼、平台等设备，均需经过()或验证方可使用。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全员检查',
        'B、施工人员验收',
        'C、先试用',
        'D、技术鉴定',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、技术鉴定。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、临边未设置防护',
        'B、未安装照明设备',
        'C、材料未及时清理',
        'D、直梯未加设护笼',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、临边未设置防护。',
      explanation: '',
      point: '1',
    },
    {
      question: '使用固定式直梯攀登作业时，当攀登高度超过（）米时，宜加设护笼',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3',
        'B、4',
        'C、5',
        'D、6',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、3。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工事故中，所占比例最高的是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、高处坠落事故',
        'B、坍塌事故',
        'C、触电事故',
        'D、物体打击事故',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、高处坠落事故。',
      explanation: '',
      point: '1',
    },
    {
      question: '塔机在安装前应当向工程所在地的建设主管部门进行（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、产权备案',
        'B、安装告知',
        'C、使用登记',
        'D、检测申请',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、安装告知。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工企业安全生产许可证管理规定》，暂扣、吊销安全生产许可证的行政处罚，由（）决定',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、建设行政主管部门',
        'B、工商管理部门',
        'C、安全生产许可证颁发机关',
        'D、税务部门',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、安全生产许可证颁发机关。',
      explanation: '',
      point: '1',
    },
    {
      question: '下列( )选项不属于企业取得安全生产许可证所应当具备的安全生产条件',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、建立、健全安全生产责任制，制定完备的安全生产规章制度和操作规程',
        'B、安全投入符合安全生产要求',
        'C、设置安全生产管理机构，配备专职安全生产管理人员',
        'D、企业负责人学历要求为本科以上',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、企业负责人学历要求为本科以上。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑业企业安全生产许可证的有效期为()年',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2',
        'B、3',
        'C、4',
        'D、5',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、3。',
      explanation: '',
      point: '1',
    },
    {
      question: '违反《建筑施工企业安全生产可证管理规定》，建筑施工企业转让安全生产许可证的，没收违法所得，处10万元以上50万元以下的罚款，并（）安全生产许可证',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、撤销',
        'B、扣留',
        'C、注销',
        'D、吊销',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、吊销。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑业企业资质证书有效期为（）年',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3',
        'B、4',
        'C、5',
        'D、6',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、5。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工企业转让、出借资质证书或者以其他方式允许他人以本企业的名义承揽工程的，对因该项承揽工程不符合规定的质量标准造成的损失，( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、由建筑施工企业独自负责',
        'B、承包单位与接受转包或者分包的单位各自独立承担相应责任',
        'C、由建筑施工企业与使用本企业名义的单位或者个人各自独立承担赔偿责任',
        'D、由建筑施工企业与使用本企业名义的单位或者个人承担连带赔偿责任',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、由建筑施工企业与使用本企业名义的单位或者个人承担连带赔偿责任。',
      explanation: '',
      point: '1',
    },
    {
      question: '依照建筑法规定被吊销资质证书的，由( )吊销其营业执照',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、建设行政主管部门',
        'B、中国建筑业协会',
        'C、工商行政管理部门',
        'D、各地人民政府',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、工商行政管理部门。',
      explanation: '',
      point: '1',
    },
    {
      question: '《建筑法》规定，建筑工程实行直接发包的，发包单位( )将建筑工程发包给具有相应资质条件的承包单位',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、可以',
        'B、应当',
        'C、可以不',
        'D、应当不',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、应当 。',
      explanation: '',
      point: '1',
    },
    {
      question: '（）负责向所管理的作业班组进行安全技术交底，并组织实施安全措施；（ ）参与安全技术交底，监督检查安全技术措施的落实情况',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、技术负责人；安全员',
        'B、技术负责人；施工员',
        'C、施工员；安全员',
        'D、安全员；施工员',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、施工员；安全员。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全技术交底应有书面材料，有( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、三方的签字',
        'B、交底日期',
        'C、A和B',
        'D、安全员签字和交底日期',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、A和B。',
      explanation: '',
      point: '1',
    },
    {
      question: '吊索编结固接时长度不应小于钢丝绳直径的（）倍，且不应小于（）mm',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、15,200',
        'B、20、300',
        'C、15,300',
        'D、20,200',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、20、300。',
      explanation: '',
      point: '1',
    },
    {
      question: '钢丝绳末端用绳夹固定时绳夹数量不得少于( )，且应根据绳径增加。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2个',
        'B、3个',
        'C、4个',
        'D、5个',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、3个。',
      explanation: '',
      point: '1',
    },
    {
      question: '钢丝绳在一定范围内集中断丝超过( )根应及时更换。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2',
        'B、3',
        'C、4',
        'D、5',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、3。',
      explanation: '',
      point: '1',
    },
    {
      question: '多次弯曲造成的() 是钢丝绳破坏的主要原因之一',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、拉伸',
        'B、扭转',
        'C、弯曲疲劳',
        'D、变形',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、弯曲疲劳。',
      explanation: '',
      point: '1',
    },
    {
      question: '钢丝绳在破断前一般有() 等预兆，容易检查、便于预防事故',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、表面光亮',
        'B、生锈',
        'C、断丝．断股',
        'D、表面有泥',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、断丝．断股。',
      explanation: '',
      point: '1',
    },
    {
      question: '模板支撑体系搭设高度超过（）属于危险性较大的分部分项工程',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、4米',
        'B、5米',
        'C、6米',
        'D、8米',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、5米。',
      explanation: '',
      point: '1',
    },
    {
      question: '满堂脚手架除满足承载能力、刚度外，还应满足（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、稳定性',
        'B、挠度',
        'C、平整性',
        'D、整体性',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、稳定性。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑拆除工程的施工方法有人工拆除、机械拆除、( )三种',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、人力拆除',
        'B、工具拆除',
        'C、爆炸拆除',
        'D、爆破拆除',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、爆破拆除。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑拆除工程必须由具备爆破与拆除专业承包资质的单位施工，严禁将工程（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、劳务分包',
        'B、总承包',
        'C、整体转包',
        'D、专业分包',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、整体转包。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑物内发生火灾，应该首先( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、立即停止工作，通过指定的最近的安全通道离开',
        'B、乘坐电梯离开',
        'C、向高处逃生',
        'D、就地等候救援',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、立即停止工作，通过指定的最近的安全通道离开。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《建设工程安全生产管理条例》，违反消防安全管理规定的行为，由()依法处罚',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、人民法院',
        'B、检察机关',
        'C、安全监督机构',
        'D、公安消防机构',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、公安消防机构。',
      explanation: '',
      point: '1',
    },
    {
      question: '易燃易爆品库房处对于火源控制，一般悬挂哪种安全标志（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、禁止标志',
        'B、警告标志',
        'C、指令标志',
        'D、指示标志',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、禁止标志 。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、脚手架步距不满足要求',
        'B、扣件未拧紧',
        'C、未设置水平、纵、横向剪刀撑',
        'D、扣件未清理',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、未设置水平、纵、横向剪刀撑。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、楼梯边临边防护缺失',
        'B、场地未做到工完料清',
        'C、未设置踢脚板',
        'D、楼层临边防护高度不足',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、楼梯边临边防护缺失。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、密目网损坏未更换',
        'B、楼层边未设置临边防护',
        'C、混凝土观感质量差',
        'D、材料未及时清理',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、楼层边未设置临边防护。',
      explanation: '',
      point: '1',
    },
    {
      question: '临边防护由（）部分组成',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2',
        'B、4',
        'C、6',
        'D、8',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、4 。',
      explanation: '',
      point: '1',
    },
    {
      question: '卸料平台钢丝绳才绳夹固定时，绳夹数量不应少于（）个。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、3',
        'B、4',
        'C、5',
        'D、6',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、4。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、开关箱未设置重复接地线',
        'B、电缆线磨破漏电',
        'C、电箱设置在积水处',
        'D、漏电保护器设置不合理',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、开关箱未设置重复接地线。',
      explanation: '',
      point: '1',
    },
    {
      question: '按照《施工现场临时用电安全技术规范》JGJ46要求，绿黄双色芯线必须用作（）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、火线',
        'B、零线',
        'C、PE线',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、PE线。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、楼层积水未及时清理',
        'B、楼层临边防护缺失',
        'C、楼层边铁丝未及时清理',
        'D、混凝土地面未凿平',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、楼层临边防护缺失。',
      explanation: '',
      point: '1',
    },
    {
      question: '卸料平台悬挑梁锚固段端部应设置不少于（）处锚固螺栓，且间距不得小于（）mm',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1,200',
        'B、2,200',
        'C、3,200',
        'D、4,200',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、2,200。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、塔吊基础内积水',
        'B、方木未及时清理',
        'C、地脚螺栓松动',
        'D、临边防护不到位',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、塔吊基础内积水。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、基坑内土方未压实',
        'B、基坑边未设置排水沟',
        'C、基坑临边防护缺失',
        'D、防水卷材未设置保护措施',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、基坑临边防护缺失。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、箱体内接线混乱',
        'B、用电设备未经过漏电保护器',
        'C、一闸多机',
        'D、箱体结构不满足规范要求',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、一闸多机。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、电缆受水浸泡',
        'B、材料未及时清理',
        'C、未设置重复接地线',
        'D、电箱未采取垫高措施',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、电缆受水浸泡。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、满堂脚手架内堆放材料',
        'B、脚手架连接方式不正确',
        'C、未设置水平、纵、横向剪刀撑',
        'D、未设置密目式安全网',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、未设置水平、纵、横向剪刀撑。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《建筑施工扣件式钢管脚手架安全技术规范》JGJ130要求，满堂脚手架应在架体外侧四周及内部纵、横向（）米，由底至顶设置连续竖向剪刀撑。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、4-5',
        'B、5-6',
        'C、6-7',
        'D、6-8',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、5-6。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、电箱设置位置不合理',
        'B、套丝机轮子损坏',
        'C、小型机具作业区域未设置防护棚',
        'D、钢管未涂刷醒目油漆',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、小型机具作业区域未设置防护棚。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、作业现场未配备消防器材',
        'B、作业人员未佩戴安全带',
        'C、作业人员未佩戴安全帽',
        'D、钢筋丝头未采取保护措施',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、作业人员未佩戴安全帽。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、人员上下塔式起重机未使用防坠器',
        'B、塔吊标准节之间未填充',
        'C、标准节锈蚀',
        'D、人员未佩戴安全帽',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、人员上下塔式起重机未使用防坠器。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮的安全锁应（）年标定一次',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1',
        'B、2',
        'C、3',
        'D、4',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1 。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、作业人员未佩戴安全帽',
        'B、作业人员未佩戴防护手套',
        'C、作业人员未穿工作服',
        'D、作业人员未佩戴防尘口罩',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、作业人员未佩戴安全帽。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、附着式升降脚手架主框架变形',
        'B、临边防护缺失',
        'C、附着式升降脚手架提升不到位',
        'D、材料未及时清理',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、临边防护缺失。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、材料未分类存放',
        'B、未配备消防器材',
        'C、材料堆放不整齐',
        'D、无材料标识标牌',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、未配备消防器材。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、吊篮主框架污染未及时清理',
        'B、吊篮限位器损坏',
        'C、钢丝绳达到报废要求',
        'D、吊篮主框架变形',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、吊篮限位器损坏。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中标记处的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、悬挂臂杆污染物未及时清理',
        'B、钢丝绳弯曲',
        'C、螺栓松动',
        'D、钢丝绳滑轮组缺失',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、钢丝绳滑轮组缺失。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、电路图缺失',
        'B、箱体与箱门未采用编织软铜线做连接',
        'C、电箱门生锈、变形',
        'D、电箱巡检记录缺失',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、箱体与箱门未采用编织软铜线做连接。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、材料堆放杂乱',
        'B、未配备消防器材',
        'C、材料堆放未下垫',
        'D、材料未覆盖',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、未配备消防器材。',
      explanation: '',
      point: '1',
    },
    {
      question: '木材堆放区及木工加工车间每（）㎡配备一组灭火器',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、20',
        'B、25',
        'C、30',
        'D、35',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、25。',
      explanation: '',
      point: '1',
    },
    {
      question: 'PE线应接入配电箱的（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、保护零线端子板',
        'B、零线端子板',
        'C、箱体螺栓',
        'B、漏电保护器',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、保护零线端子板。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、吊篮限位器缺失',
        'B、螺栓松动',
        'C、安全锁标识牌缺失',
        'D、钢丝绳磨损',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、吊篮限位器缺失。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、作业人员未佩戴安全帽',
        'B、作业人员未穿衣服',
        'C、临边防护缺失',
        'D、未配备消防器材',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、作业人员未佩戴安全帽 。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全帽的作用是保护( )，防止落物或碰撞突出物而受伤害',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、面部',
        'B、头部',
        'C、颈部',
        'D、耳部',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、头部。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、材料未分类存放',
        'B、材料堆放不整齐',
        'C、材料未覆盖',
        'D、未配备消防器材',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、未配备消防器材。',
      explanation: '',
      point: '1',
    },
    {
      question: '起吊设备时，电动卷扬机卷筒上钢丝绳余留圈数应不少于( )圈',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、2',
        'B、3',
        'C、4',
        'D、5',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、3。',
      explanation: '',
      point: '1',
    },
    {
      question: '使用单梯时梯面应与水平面成（）度夹角',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、60',
        'B、65',
        'C、70',
        'D、75',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、75。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、材料未分类存放',
        'B、材料未上覆下垫',
        'C、无标识标牌',
        'D、未配备消防器材',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、未配备消防器材。',
      explanation: '',
      point: '1',
    },
    {
      question: '《建筑灭火器配置设计规范》GB50140规定经计算确定，且每个场所的灭火器数量不应少于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1',
        'B、2',
        'C、3',
        'D、4',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、2 。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、作业人员未正确佩戴安全帽',
        'B、作业人员未穿工作服',
        'C、作业人员未穿防护鞋',
        'D、作业现场未配备灭火器',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、作业人员未正确佩戴安全帽。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、混凝土未打磨',
        'B、临边未进行防护',
        'C、保温板未采取保护措施',
        'D、未配备消防器材',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、临边未进行防护。',
      explanation: '',
      point: '1',
    },
    {
      question: '图中为吊篮（）部位损坏',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、悬挂机构',
        'B、安全锁',
        'C、动力系统',
        'D、手动滑降手柄',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、手动滑降手柄。',
      explanation: '',
      point: '1',
    },
    {
      question: '手动滑降手柄主要作用：在停电失去电源动力时平稳下降，属于（）装置',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全',
        'B、悬挂',
        'C、电气系统',
        'D、动力系统',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、安全。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮的安全钢丝绳下端应安装重砣，重砣底部至地面高度宜为（）mm。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、200-300',
        'B、100-200',
        'C、100-300',
        'D、150-250',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、100-200。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、钢丝绳缠绕',
        'B、悬挂机构外伸长度不满足要求',
        'C、未安装限位器',
        'D、钢丝绳弯曲',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、未安装限位器。',
      explanation: '',
      point: '1',
    },
    {
      question: '高处作业吊篮上限位挡板与悬挂机构的间距不小于（）mm',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、600',
        'B、700',
        'C、800',
        'D、900',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、900。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、附着式升降脚手架主框架杆件变形',
        'B、附着式升降脚手架上堆放材料未及时清理',
        'C、附着式升降脚手架与楼层间未防护',
        'D、附着式升降脚手架主框架杆件上螺栓缺失',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、附着式升降脚手架上堆放材料未及时清理。',
      explanation: '',
      point: '1',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、库房标示标牌缺失',
        'B、库房封堵不严密',
        'C、库房未配备消防器材',
        'D、库房未张贴管理制度',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、库房未配备消防器材。',
      explanation: '',
      point: '1',
    },
    {
      question: '基坑发生涌水涌沙事故，项目负责人应立即（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、带队现场检查',
        'B、转移现场值钱的材料',
        'C、启动应急预案',
        'D、不采取任何措施',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、启动应急预案。',
      explanation: '',
      point: '1',
    },
    {
      question: '对于安全等级一级的基坑工程，施工前应由（）单位委托具有相应资质的第三方监测公司对基坑进行现场监测',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、勘察',
        'B、设计',
        'C、施工',
        'D、建设',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、建设。',
      explanation: '',
      point: '1',
    },
    {
      question: '落地式脚手架剪刀撑搭设应满足（）要求',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、从下而上连续搭设',
        'B、从上而下连续搭设',
        'C、从左到右连续搭设',
        'D、从右到左连续搭设',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、从下而上连续搭设。',
      explanation: '',
      point: '1',
    },
    {
      question: '生产经营单位应为从事引起尘肺病职业危害的作业人员配备相应的（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、防毒面具',
        'B、防尘口罩',
        'C、安全帽',
        'D、手套',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、防尘口罩。',
      explanation: '',
      point: '1',
    },
    {
      question: '水泥易引起（）类职业病',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、粉尘',
        'B、噪声',
        'C、震动类',
        'D、高温',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、粉尘。',
      explanation: '',
      point: '1',
    },
    {
      question: '附着式升降脚手架提升高度（）米及以上的，属于超过一定规模的危险性较大的分部分项工程',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、100',
        'B、150',
        'C、200',
        'D、250',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、150 。',
      explanation: '',
      point: '1',
    },
    {
      question: '制定安全生产责任制的目的是( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、增强员工安全意识',
        'B、增强领导安全意识',
        'C、明确岗位安全责任',
        'D、明确领导安全责任',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、明确岗位安全责任。',
      explanation: '',
      point: '1',
    },
    {
      question: '企业或项目要实施（），制定伤亡事故控制目标、安全达标和文明施工目标',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全目标管理',
        'B、安全责任考核',
        'C、安全目标分解',
        'D、安全保证措施制定',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、安全目标管理 。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场还要制定工期内的总目标和分阶段，即基础、主体、屋面、装修等安全目标，并将责任制分解，依据不同阶段不同责任人和不同的安全目标进行（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、考查',
        'B、考核',
        'C、考试',
        'D、评价',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、考核 。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工企业在编制施工组织设计时，应当根据( )制定相应的安全技术措施',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、建筑工程的特点',
        'B、建设单位的要求',
        'C、本单位的特点',
        'D、主管部门的要求',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、建筑工程的特点。',
      explanation: '',
      point: '1',
    },
    {
      question: '对所有作业人员都应严格执行施工管理人员的()',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、安全技术交底',
        'B、安全教育',
        'C、现场示范',
        'D、逐级布置工作',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、安全技术交底。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全教育和培训按等级、层次和工作性质分别进行，对管理人员培训的重点是()',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、遵章守纪',
        'B、安全生产意识和安全管理水平',
        'C、自我保护',
        'D、提高防范事故的能力',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、安全生产意识和安全管理水平。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工班组的每天班前安全活动要由（）主持',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、班组长',
        'B、项目经理',
        'C、施工员',
        'D、技术负责人',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、班组长。',
      explanation: '',
      point: '1',
    },
    {
      question: '班前安全活动属于（）教育',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、新工人入场',
        'B、经常性',
        'C、定期性',
        'D、偶然性',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、经常性。',
      explanation: '',
      point: '1',
    },
    {
      question: '垂直运输机械作业人员、安装拆卸工、爆破作业人员、起重信号工、登高架设作业人员等特种作业人员，必须按照国家有关规定经过()，并取得特种作业操作资格证书后，方可上岗作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、三级教育',
        'B、专门的安全作业培训',
        'C、安全常识培训',
        'D、安全技术交底',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、专门的安全作业培训。',
      explanation: '',
      point: '1',
    },
    {
      question: '职工认为属于工伤，而用人单位认为不属于工伤的，由（）承担举证责任',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、用人单位',
        'B、职工本人',
        'C、同事',
        'D、近亲属',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、用人单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '劳务派遣人员的工伤由（）承担',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、用人单位',
        'B、劳务派遣单位',
        'C、员工个人',
        'D、工伤保险机构',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、劳务派遣单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '扣件式钢管模板支架的立杆间距应由计算确定，但间距最大不应大于()',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、1.5m',
        'B、1.2m',
        'C、1.8m',
        'D、2.0m',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、1.5m 。',
      explanation: '',
      point: '1',
    },
    {
      question: '模板支撑拆除应遵循（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、先支先拆',
        'B、后支后拆',
        'C、先支后拆',
        'D、同时拆除',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、先支后拆。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场临时用电实行“三级配电、两级保护”，其中三级配电分别指（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、总配电箱、二级配电箱、三级配电箱',
        'B、一级配电箱、二级配电箱、三级配电箱',
        'C、一级配电箱、二级配电箱、三级开关箱',
        'D、总配电箱、分配电箱、开关箱',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D、总配电箱、分配电箱、开关箱。',
      explanation: '',
      point: '1',
    },
    {
      question: '配电箱、开关箱的停电操作顺序为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、总-分-开',
        'B、总-开-分',
        'C、开-分-总',
        'D、开-总-分',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、开-分-总。',
      explanation: '',
      point: '1',
    },
    {
      question: '配电箱、开关箱的送电操作顺序为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、总-分-开',
        'B、总-开-分',
        'C、开-分-总',
        'D、开-总-分',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、总-分-开。',
      explanation: '',
      point: '1',
    },
    {
      question: '隧道、人防工程、高温、有导电灰尘、比较潮湿或灯具离地面高度低于2.5m等场所的照明，电源电压不应大于（）v',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、24',
        'B、36',
        'C、72',
        'D、220',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、36。',
      explanation: '根据相关规范',
      point: '1',
    },
  ],
};

export default quiz;
