const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产单选题测验',
  quizSynopsis: '本测验涵盖建设工程安全生产相关的单选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '51',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '按照《建筑施工现场标志设置技术规程》，上图所示安全标志为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '禁止标志',
        '警告标志',
        '指令标志',
        '提示标志',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是警告标志。',
      explanation: '根据《建筑施工现场标志设置技术规程》，黄色背景的安全标志为警告标志。',
      point: '10',
    },
    {
      question: '黄颜色背景的安全标志属于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '禁止标志',
        '警告标志',
        '指令标志',
        '提示标志',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，黄色背景的安全标志属于警告标志。',
      explanation: '根据《建筑施工现场标志设置技术规程》，黄颜色背景的安全标志为警告标志。',
      point: '10',
    },
    {
      question: '按照《建筑施工高处作业安全技术规程》要求，安全带正确使用的方法是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '低挂高用',
        '高挂低用',
        '高挂高用',
        '低挂低用',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全带应高挂低用。',
      explanation: '根据《建筑施工高处作业安全技术规程》，安全带应高挂低用以确保安全。',
      point: '10',
    },
    {
      question: '按《危险性较大的分部分项工程安全管理规定》住建部31号文规定，基坑开挖深度超过（）米，专项施工方案应组织专家论证。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '5',
        '6',
        '7',
        '8',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，基坑开挖深度超过5米需专家论证。',
      explanation: '根据《危险性较大的分部分项工程安全管理规定》，基坑开挖深度超过5米需组织专家论证。',
      point: '10',
    },
    {
      question: '基坑边（）范围内，严禁堆放超过设计荷载的材料',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '0.8米',
        '1米',
        '1.5米',
        '2米',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，基坑边1.5米范围内禁止堆放超载材料。',
      explanation: '根据相关安全规范，基坑边1.5米范围内不得堆放超过设计荷载的材料。',
      point: '10',
    },
    {
      question: '按照《施工脚手架通用规范》要求，上图所示为哪种形式的模板支架',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '碗扣式钢管脚手架',
        '盘扣式钢管脚手架',
        '扣件式钢管脚手架',
        '门式钢管脚手架',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是扣件式钢管脚手架。',
      explanation: '根据《施工脚手架通用规范》，图示为扣件式钢管脚手架。',
      point: '10',
    },
    {
      question: '发生模板支架倒塌事故后，组织调查处理按照（）的原则，严肃处理事故',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '四不放过',
        '教育与惩罚相结合',
        '领导责任制',
        '过错性',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，事故处理应遵循四不放过原则。',
      explanation: '四不放过原则包括事故原因未查清不放过、责任人员未处理不放过、整改措施未落实不放过、有关人员未受到教育不放过。',
      point: '10',
    },
    {
      question: '满堂脚手架自由端长度为立杆伸出顶层水平杆中心线至中心点的距离不应超过（）mm',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '400',
        '500',
        '600',
        '700',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，自由端长度不应超过500mm。',
      explanation: '根据《施工脚手架通用规范》，满堂脚手架自由端长度不得超过500mm。',
      point: '10',
    },
    {
      question: '按《危险性较大的分部分项工程安全管理规定》，悬挑式脚手架的专项施工方案应由（）主持编制',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '项目负责人',
        '项目技术负责人',
        '企业负责人',
        '施工单位技术负责人',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，悬挑式脚手架专项施工方案由项目负责人主持编制。',
      explanation: '根据《危险性较大的分部分项工程安全管理规定》，项目负责人负责主持编制专项施工方案。',
      point: '10',
    },
    {
      question: '张某在脚手架上施工时，发现部分扣件松动可能发生倒塌，随立即停止作业，撤离到安全区域，这属于从业人员行使的（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '知情权',
        '拒绝权',
        '紧急避险权',
        '检举权',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，这是紧急避险权。',
      explanation: '从业人员在发现安全隐患时有权采取紧急避险措施以保护自身安全。',
      point: '10',
    },
    {
      question: '根据《生产安全事故报告和调查处理条例》，事故发生后，单位负责人接到报告后，应当于（）内向事故发生地县级以上人民政府安全生产监督管理部门和负有安全生产监督管理职责的有关部门报告。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '立即',
        '1小时',
        '2小时',
        '3小时',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应在1小时内报告。',
      explanation: '根据《生产安全事故报告和调查处理条例》，事故需在1小时内报告相关部门。',
      point: '10',
    },
    {
      question: '根据《施工现场临时用电安全技术规范》要求，临时用电施工组织设计由（）编制',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '土建技术负责人',
        '电气工程技术人员',
        '项目负责人',
        '企业负责人',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，临时用电施工组织设计由电气工程技术人员编制。',
      explanation: '根据《施工现场临时用电安全技术规范》，临时用电施工组织设计需由专业电气工程技术人员编制。',
      point: '10',
    },
    {
      question: '根据《建筑施工企业负责人及项目负责人施工现场带班暂行办法》规定，项目负责人每月带班时间不少于施工时间的',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '70%',
        '80%',
        '90%',
        '100%',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，项目负责人每月带班时间不少于施工时间的80%。',
      explanation: '根据规定，项目负责人需保证每月带班时间不少于施工时间的80%。',
      point: '10',
    },
    {
      question: '根据《建筑施工企业负责人及项目负责人施工现场带班暂行办法》规定，企业负责人要定期带班检查，每月检查时间不少于工作日',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '20%',
        '25%',
        '30%',
        '35%',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，企业负责人每月检查时间不少于工作日的25%。',
      explanation: '根据规定，企业负责人每月带班检查时间不少于工作日的25%。',
      point: '10',
    },
    {
      question: '《安全生产法》规定，生产经营单位必须为从业人员提供符合国家标准或行业标准的',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '劳动防护用品',
        '劳动工具',
        '福利待遇',
        '工作服',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，必须提供劳动防护用品。',
      explanation: '根据《安全生产法》，生产经营单位需为从业人员提供符合标准的劳动防护用品。',
      point: '10',
    },
    {
      question: '根据《中华人民共和国消防法》规定，我国消防工作执行（）的方针',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '预防为主、防消结合',
        '以防为主、以消为主',
        '安全第一、预防为主、综合治理',
        '谁主管、谁负责、谁在岗、谁负责',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，消防工作执行预防为主、防消结合的方针。',
      explanation: '根据《中华人民共和国消防法》，消防工作遵循预防为主、防消结合的方针。',
      point: '10',
    },
    {
      question: '火灾事故发生后（）内，若伤亡人数发生变化应及时补报',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '7天',
        '10天',
        '15天',
        '30天',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，火灾事故后7天内需补报伤亡变化。',
      explanation: '根据相关规定，火灾事故后7天内若伤亡人数变化需及时补报。',
      point: '10',
    },
    {
      question: '建筑施工五大伤亡事故类别中，（）事故的发生率最高、危险性极大。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '坍塌',
        '高处坠落',
        '物体打击',
        '机械伤害',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，高处坠落事故发生率最高。',
      explanation: '高处坠落是建筑施工中发生率最高、危险性最大的事故类型。',
      point: '10',
    },
    {
      question: '上图所示，导致安全事故发生最主要的因素是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '人的不安全行为',
        '物的不安全状态',
        '管理缺陷',
        '物的不安全因素',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，人的不安全行为是主要因素。',
      explanation: '人的不安全行为是导致安全事故的主要原因之一。',
      point: '10',
    },
    {
      question: '此次事故属于（）事故。（只考虑人员死亡，不考虑重伤和直接经济损失）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '一般事故',
        '较大事故',
        '重大事故',
        '特别重大事故',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，此事故属于一般事故。',
      explanation: '根据事故分级标准，仅考虑人员死亡的情况属于一般事故。',
      point: '10',
    },
    {
      question: '作业人员在吊篮内施工应佩戴（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安全绳',
        '安全带',
        '安全网',
        '安全帽',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，吊篮内施工应佩戴安全带。',
      explanation: '吊篮作业人员必须佩戴安全带以确保高处作业安全。',
      point: '10',
    },
    {
      question: '动火作业前应办理（）手续，审批后方可进行作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '动火证',
        '作业证',
        '使用证',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，动火作业需办理动火证。',
      explanation: '动火作业需办理动火证以确保安全管理。',
      point: '10',
    },
    {
      question: '乙炔瓶压力表处应安装（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '止回阀',
        '截止阀',
        '减压阀',
        '回火阀',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，乙炔瓶压力表处应安装回火阀。',
      explanation: '回火阀用于防止乙炔瓶回火，确保安全使用。',
      point: '10',
    },
    {
      question: '使用灭火器进行灭火时，灭火器喷射口应对准火焰（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '上空',
        '上部',
        '中部',
        '根部',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，灭火器喷射口应对准火焰根部。',
      explanation: '灭火时应对准火焰根部以有效扑灭火源。',
      point: '10',
    },
    {
      question: '危险性较大的分部分项工程施工时，（）应在现场进行监督检查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '带队现场检查',
        '转移现场值钱的材料',
        '启动应急预案',
        '不采取任何措施',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应由专职安全员进行现场监督检查。',
      explanation: '危险性较大的分部分项工程施工需专职安全员现场监督检查。',
      point: '10',
    },
    {
      question: '对于安全等级一级的基坑工程，施工前应由（）单位委托具有相应资质的第三方监测公司对基坑进行现场监测',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '勘察',
        '设计',
        '施工',
        '建设',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应由建设单位委托第三方监测。',
      explanation: '安全等级一级的基坑工程需由建设单位委托第三方进行监测。',
      point: '10',
    },
    {
      question: '落地式脚手架剪刀撑搭设应满足（）要求',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '从下而上连续搭设',
        '从上而下连续搭设',
        '从左到右连续搭设',
        '从右到左连续搭设',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，剪刀撑应从下而上连续搭设。',
      explanation: '根据规范，落地式脚手架剪刀撑需从下而上连续搭设以确保稳定性。',
      point: '10',
    },
    {
      question: '生产经营单位应为从事引起尘肺病职业危害的作业人员配备相应的（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '防毒面具',
        '防尘口罩',
        '安全帽',
        '手套',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应配备防尘口罩。',
      explanation: '防尘口罩是防止尘肺病的必要防护用品。',
      point: '10',
    },
    {
      question: '水泥易引起（）类职业病',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '粉尘',
        '噪声',
        '震动类',
        '高温',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，水泥易引起粉尘类职业病。',
      explanation: '水泥作业中产生的粉尘可能导致尘肺病等职业病。',
      point: '10',
    },
    {
      question: '附着式升降脚手架提升高度（）米及以上的，属于超过一定规模的危险性较大的分部分项工程',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '100',
        '150',
        '200',
        '250',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，提升高度150米及以上属于危险性较大的工程。',
      explanation: '根据规范，附着式升降脚手架提升高度150米及以上需特殊管理。',
      point: '10',
    },
    {
      question: '制定安全生产责任制的目的是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '增强员工安全意识',
        '增强领导安全意识',
        '明确岗位安全责任',
        '明确领导安全责任',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全生产责任制旨在明确岗位安全责任。',
      explanation: '安全生产责任制通过明确各岗位职责确保安全管理落实。',
      point: '10',
    },
    {
      question: '企业或项目要实施（），制定伤亡事故控制目标、安全达标和文明施工目标',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安全目标管理',
        '安全责任考核',
        '安全目标分解',
        '安全保证措施制定',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应实施安全目标管理。',
      explanation: '安全目标管理是制定事故控制和文明施工目标的基础。',
      point: '10',
    },
    {
      question: '施工现场还要制定工期内的总目标和分阶段，即基础、主体、屋面、装修等安全目标，并将责任制分解，依据不同阶段不同责任人和不同的安全目标进行（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '考查',
        '考核',
        '考试',
        '评价',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应进行考核。',
      explanation: '安全目标需通过考核确保分阶段落实。',
      point: '10',
    },
    {
      question: '建筑施工企业在编制施工组织设计时，应当根据（）制定相应的安全技术措施',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '建筑工程的特点',
        '建设单位的要求',
        '本单位的特点',
        '主管部门的要求',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应根据建筑工程的特点制定措施。',
      explanation: '安全技术措施需根据工程特点量身定制。',
      point: '10',
    },
    {
      question: '对所有作业人员都应严格执行施工管理人员的（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安全技术交底',
        '安全教育',
        '现场示范',
        '逐级布置工作',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应执行安全技术交底。',
      explanation: '安全技术交底是确保作业人员了解安全要求的重要环节。',
      point: '10',
    },
    {
      question: '安全教育和培训按等级、层次和工作性质分别进行，对管理人员培训的重点是（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '遵章守纪',
        '安全生产意识和安全管理水平',
        '自我保护',
        '提高防范事故的能力',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，管理人员培训重点是安全生产意识和管理水平。',
      explanation: '管理人员需重点提升安全生产意识和管理能力。',
      point: '10',
    },
    {
      question: '施工班组的每天班前安全活动要由（）主持',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '班组长',
        '项目经理',
        '施工员',
        '技术负责人',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，班前安全活动由班组长主持。',
      explanation: '班组长负责主持班前安全活动以确保每日安全教育。',
      point: '10',
    },
    {
      question: '班前安全活动属于（）教育',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '新工人入场',
        '经常性',
        '定期性',
        '偶然性',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，班前安全活动属于经常性教育。',
      explanation: '班前安全活动是经常性安全教育的一部分。',
      point: '10',
    },
    {
      question: '垂直运输机械作业人员、安装拆卸工、爆破作业人员、起重信号工、登高架设作业人员等特种作业人员，必须按照国家有关规定经过（），并取得特种作业操作资格证书后，方可上岗作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '三级教育',
        '专门的安全作业培训',
        '安全常识培训',
        '安全技术交底',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，特种作业人员需经过专门培训。',
      explanation: '特种作业人员需经过专门的安全作业培训并取得资格证书。',
      point: '10',
    },
    {
      question: '职工认为属于工伤，而用人单位认为不属于工伤的，由（）承担举证责任',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '用人单位',
        '职工本人',
        '同事',
        '近亲属',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，用人单位承担举证责任。',
      explanation: '根据规定，用人单位需对工伤认定争议承担举证责任。',
      point: '10',
    },
    {
      question: '劳务派遣人员的工伤由（）承担',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '用人单位',
        '劳务派遣单位',
        '员工个人',
        '工伤保险机构',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，劳务派遣人员的工伤由劳务派遣单位承担。',
      explanation: '劳务派遣人员的工伤责任由劳务派遣单位承担。',
      point: '10',
    },
    {
      question: '扣件式钢管模板支架的立杆间距应由计算确定，但间距最大不应大于（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '1.5m',
        '1.2m',
        '1.8m',
        '2.0m',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，立杆间距最大不应大于1.5m。',
      explanation: '根据规范，扣件式钢管模板支架立杆间距最大为1.5m。',
      point: '10',
    },
    {
      question: '模板支撑拆除应遵循（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '先支先拆',
        '后支后拆',
        '先支后拆',
        '同时拆除',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，模板支撑拆除应先支后拆。',
      explanation: '模板支撑拆除需遵循先支后拆的原则以确保安全。',
      point: '10',
    },
    {
      question: '施工现场临时用电实行“三级配电、两级保护”，其中三级配电分别指（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '总配电箱、二级配电箱、三级配电箱',
        '一级配电箱、二级配电箱、三级配电箱',
        '一级配电箱、二级配电箱、三级开关箱',
        '总配电箱、分配电箱、开关箱',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，三级配电指总配电箱、分配电箱、开关箱。',
      explanation: '根据《施工现场临时用电安全技术规范》，三级配电为总配电箱、分配电箱、开关箱。',
      point: '10',
    },
    {
      question: '配电箱、开关箱的停电操作顺序为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '总-分-开',
        '总-开-分',
        '开-分-总',
        '开-总-分',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，停电操作顺序为开-分-总。',
      explanation: '停电操作需先断开开关箱，再断开分配电箱，最后断开总配电箱。',
      point: '10',
    },
    {
      question: '配电箱、开关箱的送电操作顺序为（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '总-分-开',
        '总-开-分',
        '开-分-总',
        '开-总-分',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，送电操作顺序为总-分-开。',
      explanation: '送电操作需先接通总配电箱，再接通分配电箱，最后接通开关箱。',
      point: '10',
    },
    {
      question: '隧道、人防工程、高温、有导电灰尘、比较潮湿或灯具离地面高度低于2.5m等场所的照明，电源电压不应大于（）v',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '24',
        '36',
        '72',
        '220',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，电源电压不应大于36v。',
      explanation: '根据安全规范，特殊场所照明电源电压不得超过36v。',
      point: '10',
    },
  ],
};

export default quiz;
