const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产多选题测验',
  quizSynopsis: '本测验涵盖建设工程安全生产相关的多选题，旨在帮助用户深入理解相关知识点。',
  nrOfQuestions: '28',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '按照《建筑施工现场标志设置技术规程》安全标志分为下列四种',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '禁止标志',
        '警告标志',
        '安全标志',
        '指令标志',
        '提示标志',
      ],
      correctAnswer: [1, 2, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全标志包括禁止标志、警告标志、指令标志和提示标志。',
      explanation: '根据《建筑施工现场标志设置技术规程》，安全标志分为禁止、警告、指令和提示四种。',
      point: '10',
    },
    {
      question: '图中存在哪些安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '基坑未采取支护措施',
        '临边未防护',
        '未配备消防器材',
        '基坑边堆载严重',
        '未设置电箱',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，图中安全隐患包括基坑未支护、临边未防护、未配备消防器材和基坑边堆载严重。',
      explanation: '基坑施工需采取支护措施、临边防护、配备消防器材，并避免堆载超标。',
      point: '10',
    },
    {
      question: '脚手架搭设过程中会发生哪些事故（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '坍塌',
        '高空坠落',
        '物体打击',
        '机械伤害',
        '中毒、窒息',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，脚手架搭设中可能发生坍塌、高空坠落和物体打击事故。',
      explanation: '脚手架搭设过程中，坍塌、高空坠落和物体打击是常见事故类型。',
      point: '10',
    },
    {
      question: '按照《生产安全事故应急预案管理办法》规定，应急预案分为（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '综合应急预案',
        '现场处置方案',
        '专项应急预案',
        '单独应急预案',
        '专业应急预案',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应急预案包括综合应急预案、现场处置方案和专项应急预案。',
      explanation: '根据《生产安全事故应急预案管理办法》，应急预案分为综合、现场处置和专项三种。',
      point: '10',
    },
    {
      question: '应急演练按照组织形式分为（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '桌面演练',
        '现场演练',
        '实战演练',
        '单项演练',
        '综合演练',
      ],
      correctAnswer: [1, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应急演练形式包括桌面演练和实战演练。',
      explanation: '应急演练按组织形式分为桌面演练和实战演练两种。',
      point: '10',
    },
    {
      question: '根据《生产安全事故报告和调查处理条例》，生产安全事故分为哪些等级（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '特别重大事故',
        '重大事故',
        '较大事故',
        '一般事故',
        '轻伤事故',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，事故等级包括特别重大、重大、较大和一般事故。',
      explanation: '根据《生产安全事故报告和调查处理条例》，事故分为特别重大、重大、较大和一般四级。',
      point: '10',
    },
    {
      question: '根据《生产经营单位安全培训规定》，三级安全教育包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '公司级',
        '项目级',
        '班组级',
        '作业队',
        '安全监督部门',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，三级安全教育包括公司级、项目级和班组级。',
      explanation: '三级安全教育包括公司级、项目级和班组级教育。',
      point: '10',
    },
    {
      question: '施工现场个人安全防护用品所需的三证一标志有（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '安全生产许可证',
        '生产许可证',
        '产品合格证',
        '安全鉴定证',
        '安全标志',
      ],
      correctAnswer: [2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，个人安全防护用品需生产许可证、产品合格证、安全鉴定证和安全标志。',
      explanation: '安全防护用品需具备生产许可证、产品合格证、安全鉴定证和安全标志。',
      point: '10',
    },
    {
      question: '我国建筑施工行业主要的事故类型为（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '坍塌',
        '高处坠落',
        '物体打击',
        '机械伤害',
        '触电',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，建筑施工主要事故类型包括坍塌、高处坠落、物体打击、机械伤害和触电。',
      explanation: '建筑施工行业主要事故类型涵盖坍塌、高处坠落、物体打击、机械伤害和触电。',
      point: '10',
    },
    {
      question: '起重吊装作业应采取（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '配备司索指挥',
        '设置警戒线',
        '设置禁止入内告示牌',
        '专职安全员现场监督',
        '项目技术负责人带班检查',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，起重吊装作业需配备司索指挥、设置警戒线、告示牌和专职安全员监督。',
      explanation: '起重吊装作业需采取多重安全措施以确保安全。',
      point: '10',
    },
    {
      question: '国家规定生产经营单位安全教育培训对象，主要包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '生产经营单位主要负责人',
        '安全生产管理人员',
        '其他从业人员',
        '特种作业人员',
        '参观人员',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全教育培训对象包括主要负责人、安全管理人员、其他从业人员和特种作业人员。',
      explanation: '根据规定，安全教育培训需覆盖主要负责人、安全管理人员、从业人员和特种作业人员。',
      point: '10',
    },
    {
      question: '上图所示，可能导致哪些类别的事故发生（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '火灾',
        '机械伤害',
        '中毒',
        '物体打击',
        '高空坠落',
      ],
      correctAnswer: [4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，可能导致物体打击和高空坠落事故。',
      explanation: '图示场景可能导致物体打击和高空坠落事故。',
      point: '10',
    },
    {
      question: '焊接作业时，作业人员应穿戴（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '绝缘鞋',
        '电焊手套',
        '防护面罩',
        '护目镜',
        '安全带',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，焊接作业需穿戴绝缘鞋、电焊手套、防护面罩和护目镜。',
      explanation: '焊接作业需穿戴多种防护用品以确保安全。',
      point: '10',
    },
    {
      question: '施工现场临时用电必须符合（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '三级配电',
        '两级保护',
        'TN-S接零保护系统',
        '一闸、一机、一漏、一箱',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，临时用电需符合三级配电、两级保护、TN-S接零保护系统及一闸一机一漏一箱要求。',
      explanation: '施工现场临时用电需严格遵守相关安全技术规范。',
      point: '10',
    },
    {
      question: '发生伤亡事故后，事故报告应包括的内容（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '事故发生的原因',
        '事故发生的时间、地点及事故现场情况',
        '事故发生后造成的人员伤亡和直接经济损失',
        '事故发生后采取的主要措施',
        '事故发生的简要经过',
      ],
      correctAnswer: [2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，事故报告需包括时间地点、伤亡损失、采取措施和简要经过。',
      explanation: '根据规定，事故报告需详细记录时间地点、伤亡情况、措施和经过。',
      point: '10',
    },
    {
      question: '三级开关箱中存在哪些安全隐患',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '电箱内设置活动插头',
        '电箱门与箱体连接的编织软铜线断开',
        '漏电保护器的额定漏电动作电流参数不正确',
        '电箱未设置重复接地',
        '用电设备电缆无PE线',
      ],
      correctAnswer: [1, 2, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全隐患包括活动插头、软铜线断开、未重复接地和无PE线。',
      explanation: '三级开关箱需避免活动插头、确保接地完整性和PE线连接。',
      point: '10',
    },
    {
      question: '临时用电在（）情况下需要编制临时用电组织设计。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '5台及5台以上用电设备',
        '4台及4台以上用电设备',
        '设备总容量50KW以上',
        '设备总容量40KW以上',
        '3台及3台以上或设备总容量50KW以上',
      ],
      correctAnswer: [1, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需在5台及以上或总容量50KW以上时编制组织设计。',
      explanation: '根据规范，5台及以上或总容量50KW以上需编制临时用电组织设计。',
      point: '10',
    },
    {
      question: '依据《建设工程安全生产管理条例》规定，（）工程、（）工程、地下暗挖工程的专项施工方案，施工单位应当组织专家论证审查。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '高大模板',
        '深基坑',
        '起重吊装',
        '拆除、爆破',
        '人工挖孔桩',
      ],
      correctAnswer: [1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，高大模板和深基坑工程需专家论证。',
      explanation: '高大模板和深基坑工程属于危险性较大的工程，需专家论证审查。',
      point: '10',
    },
    {
      question: '脚手架在搭设过程中会发生哪些事故（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '坍塌',
        '高空坠落',
        '物体打击',
        '火灾',
        '中毒、窒息',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，脚手架搭设中可能发生坍塌、高空坠落和物体打击事故。',
      explanation: '脚手架搭设过程中，坍塌、高空坠落和物体打击是主要事故类型。',
      point: '10',
    },
    {
      question: '脚手架搭设过程中，作业人员应佩戴哪些安全防护用品（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '安全帽',
        '安全带',
        '安全网',
        '安全鞋',
        '防护眼镜',
      ],
      correctAnswer: [1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，作业人员需佩戴安全帽和安全带。',
      explanation: '脚手架搭设中，安全帽和安全带是必备防护用品。',
      point: '10',
    },
    {
      question: '塔式起重机安装完毕的四方验收分别包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '建设单位',
        '使用单位',
        '监理单位',
        '安装单位',
        '租赁单位',
      ],
      correctAnswer: [2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，四方验收包括使用单位、监理单位、安装单位和租赁单位。',
      explanation: '塔式起重机验收需由使用单位、监理单位、安装单位和租赁单位共同参与。',
      point: '10',
    },
    {
      question: '建设单位应当在拆除工程施工15日前，将下列资料报送建设工程所在地的县级以上地方人民政府建设行主管部门或者其他有关部门备案（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '堆放、清除废弃物的措施',
        '施工单位资质等级证明',
        '拟拆除工程地下管线资料',
        '拟拆除建筑物、构筑物及可能危及毗邻建筑的说明',
        '拆除施工组织方案',
      ],
      correctAnswer: [1, 2, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需报送废弃物措施、资质证明、建筑物说明和施工方案。',
      explanation: '拆除工程需提前报送相关资料以确保安全管理。',
      point: '10',
    },
    {
      question: '施工单位应当在施工现场建立消防安全责任制度，确定消防安全责任人，制定用火、用电、使用易燃易爆材料等各项消防安全管理制度、操作规程，并（），并在施工现场人口处设置明显标志',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '设置消防通道',
        '配备消防水源',
        '配备消防设施',
        '配备灭火器材',
        '请消防队员驻防',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需设置消防通道、水源、设施和灭火器材。',
      explanation: '施工现场消防安全需设置通道、水源、设施和器材。',
      point: '10',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '楼层反坎断开',
        '悬挑工字钢锚固段长度不足',
        '锚固螺栓设置不合理',
        '卸料平台与楼层间的间隙未封闭',
        '纵向扫地杆距钢管底端大于200mm',
      ],
      correctAnswer: [4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全隐患包括间隙未封闭和扫地杆高度超标。',
      explanation: '卸料平台间隙需封闭，扫地杆距底端不得大于200mm。',
      point: '10',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '电箱内接线不规范',
        '电箱内漏电保护器额定动作电流参数不符合要求',
        '电箱内设置活动插头',
        '箱体与箱门未采用编织软铜线连接',
        '电箱PE零线未设置重复接地',
      ],
      correctAnswer: [1, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全隐患包括接线不规范、活动插头和未用软铜线连接。',
      explanation: '电箱需规范接线、避免活动插头并确保软铜线连接。',
      point: '10',
    },
    {
      question: '消防柜中应配备哪些消防器材（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '消防铲',
        '消防斧',
        '消防桶',
        '灭火器',
        '消防钩',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，消防柜需配备消防铲、斧、桶、灭火器和钩。',
      explanation: '消防柜需配备多种消防器材以应对紧急情况。',
      point: '10',
    },
    {
      question: '请找出图中存在的安全隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '箱体与箱门未采用编织软铜线连接',
        '设备电源线未经过漏电保护器',
        '电箱内设置活动插头',
        '动力与照明未分箱设置',
        '未做分路标记',
      ],
      correctAnswer: [1, 2, 3, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全隐患包括未用软铜线连接、电源线未过漏电保护器、活动插头和未做分路标记。',
      explanation: '电箱需确保软铜线连接、电源线过漏电保护器、无活动插头并做好分路标记。',
      point: '10',
    },
    {
      question: '请找出图中存在的安全事故隐患（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '锚固螺栓未采用双螺母',
        '螺母未拧紧',
        '锚固段长度不足',
        '建筑材料未清理',
        '压板与工字钢间未设置木楔',
      ],
      correctAnswer: [1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安全隐患包括锚固螺栓未用双螺母和螺母未拧紧。',
      explanation: '锚固螺栓需采用双螺母并确保螺母拧紧以保证稳定性。',
      point: '10',
    },
  ],
};

export default quiz;
