const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产判断题测验',
  quizSynopsis: '本测验涵盖建设工程安全生产相关的判断题，旨在帮助用户巩固相关知识点。',
  nrOfQuestions: '64',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '依据《建筑施工高处作业安全技术规程》，高处作业前应按类别对安全防护设施进行检查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，高处作业前需按类别检查安全防护设施。',
      explanation: '根据《建筑施工高处作业安全技术规程》，高处作业前必须检查安全防护设施。',
      point: '10',
    },
    {
      question: '“违章操作，作业时未挂安全绳，工人未系安全带”属于高空坠落事故发生的不安全因素之一',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，违章操作和未系安全带是高空坠落的主要因素。',
      explanation: '未挂安全绳和未系安全带是导致高空坠落事故的常见不安全因素。',
      point: '10',
    },
    {
      question: '特殊情况下，经负责事故调查的人民政府批准，提交事故调查报告的期限可以延长，但延长的期限最长不超过60日',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，事故调查报告延期最长不超过60日。',
      explanation: '根据规定，特殊情况下事故调查报告可延期，最长60日。',
      point: '10',
    },
    {
      question: '根据《特种作业人员目录》，电工属于特种作业人员',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '是',
        '否',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，电工属于特种作业人员。',
      explanation: '根据《特种作业人员目录》，电工需取得特种作业资格证书。',
      point: '10',
    },
    {
      question: '项目负责人带班生产时，要全面掌握工程项目质量安全生产状况，加强对重点部位、关键环节的控制，及时消除隐患。要认真做好带班生产记录并签字存档备查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，项目负责人需做好带班记录并签字存档。',
      explanation: '项目负责人带班需全面掌握安全生产状况并记录存档。',
      point: '10',
    },
    {
      question: '《安全生产法》规定，生产经营单位必须为从业人员提供符合国家标准或者行业标准的劳动防护用品，并监督、教育从业人员按照使用规则佩戴、使用',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，生产经营单位必须提供符合标准的劳动防护用品。',
      explanation: '《安全生产法》要求提供符合标准的劳动防护用品并监督使用。',
      point: '10',
    },
    {
      question: '施工单位应当制定本单位生产安全事故应急救援预案，建立应急救援组织或者配备应急救援人员，配备必要的应急救援器材、设备，并定期组织演练。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，施工单位需制定应急救援预案并定期演练。',
      explanation: '施工单位需建立应急救援体系并定期组织演练。',
      point: '10',
    },
    {
      question: '实行施工总承包的建设工程，由总承包单位负责上报事故',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，总承包单位负责上报事故。',
      explanation: '总承包单位在施工总承包工程中负责事故上报。',
      point: '10',
    },
    {
      question: '图中，作业人员的做法是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，图中作业人员做法存在安全隐患。',
      explanation: '图中作业人员的做法不符合安全规范。',
      point: '10',
    },
    {
      question: '图中的作业人员是否需要持证上岗',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '需要',
        '不需要',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，图中作业人员无需持证上岗。',
      explanation: '根据作业类型，图中作业人员无需特种作业资格证书。',
      point: '10',
    },
    {
      question: '“十不吊”是吊装作业必须遵守的原则',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，十不吊是吊装作业的基本原则。',
      explanation: '“十不吊”是确保吊装作业安全的重要原则。',
      point: '10',
    },
    {
      question: '图中说法是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，图中说法不正确。',
      explanation: '图中描述的安全措施或做法不符合规范要求。',
      point: '10',
    },
    {
      question: '图中说法是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，图中说法不正确。',
      explanation: '图中描述的安全措施或做法存在错误。',
      point: '10',
    },
    {
      question: '图中吊装作业绑扎的方式是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，吊装作业绑扎方式不正确。',
      explanation: '图中吊装作业的绑扎方式不符合安全规范。',
      point: '10',
    },
    {
      question: '进行起重吊装作业时，不需要疏散其余无关人员',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，起重吊装作业需疏散无关人员。',
      explanation: '起重吊装作业时必须疏散无关人员以确保安全。',
      point: '10',
    },
    {
      question: '进入施工现场的从业人员不需要掌握本岗位存在的危险因素',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，从业人员需掌握岗位危险因素。',
      explanation: '从业人员必须了解岗位存在的危险因素以确保安全作业。',
      point: '10',
    },
    {
      question: '从事高处作业的人员要定期进行身体健康检查。凡患有高血压病、心脏病、贫血病、癫痫病者不得安排从事高处作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，高处作业人员需定期体检，特定疾病患者不得从事高处作业。',
      explanation: '高处作业人员需定期体检，患特定疾病者不得从事高处作业。',
      point: '10',
    },
    {
      question: '动火前必须清除周围的可燃物。当有固定装置等无法清除时，应采用“接火盘”等防止火星乱溅的措施',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，动火前需清除可燃物或采取防火星措施。',
      explanation: '动火作业需清除可燃物或使用接火盘防止火星溅射。',
      point: '10',
    },
    {
      question: '施工现场临时用电采用的设备设施费用是否纳入安全文明措施费用',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '是',
        '不是',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，临时用电设备设施费用需纳入安全文明措施费用。',
      explanation: '临时用电设备设施费用属于安全文明措施费用的一部分。',
      point: '10',
    },
    {
      question: '施工现场临时用电应实行动力与照明分设',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，临时用电需动力与照明分设。',
      explanation: '施工现场临时用电需将动力与照明分开设置以确保安全。',
      point: '10',
    },
    {
      question: '临时用电工程定期检查应按分部、分项工程进行，对安全隐患必须及时处理，并应履行复查验收手续',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，临时用电需定期检查并及时处理隐患。',
      explanation: '临时用电工程需按分部、分项检查并履行复查验收手续。',
      point: '10',
    },
    {
      question: '发生无人员伤亡的一般事故，县级人民政府可委托事故发生单位进行事故调查',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，无人员伤亡的一般事故可由县级人民政府委托调查。',
      explanation: '无人员伤亡的一般事故可由县级人民政府委托单位调查。',
      point: '10',
    },
    {
      question: '乙炔瓶在储存或使用时可以水平放置',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，乙炔瓶不得水平放置。',
      explanation: '乙炔瓶储存或使用时必须直立放置以确保安全。',
      point: '10',
    },
    {
      question: '依据《建筑施工高处作业安全技术规范》JGJ80要求，图中水平预留洞口防护设置是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，水平预留洞口防护设置不正确。',
      explanation: '水平预留洞口防护需符合《建筑施工高处作业安全技术规范》要求，图中设置不符合标准。',
      point: '10',
    },
    {
      question: '生产经营单位不得以任何形式与从业人员订立协议，免除或者减轻其对从业人员因生产安全事故伤亡依法应承担的责任。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，生产经营单位不得免除事故责任。',
      explanation: '《安全生产法》禁止生产经营单位通过协议免除事故责任。',
      point: '10',
    },
    {
      question: '生产经营单位发生生产安全事故时，单位的主要负责人应当立即组织抢救，并不得在事故调查处理期间擅离职守',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，主要负责人需立即组织抢救且不得擅离职守。',
      explanation: '主要负责人需在事故发生后立即组织抢救并留守处理。',
      point: '10',
    },
    {
      question: '进入有限空间作业前不需要办理审批手续',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，有限空间作业需办理审批手续。',
      explanation: '有限空间作业需办理审批手续以确保安全。',
      point: '10',
    },
    {
      question: '有限空间作业可以采用纯氧进行通风换气',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，有限空间作业不得使用纯氧通风。',
      explanation: '纯氧通风可能引发爆炸等危险，需使用安全通风方式。',
      point: '10',
    },
    {
      question: '实施有限空间作业时，应安排专人监督值守',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，有限空间作业需专人监督值守。',
      explanation: '有限空间作业需安排专人监督以确保安全。',
      point: '10',
    },
    {
      question: '图中作业人员的做法是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，图中作业人员做法不正确。',
      explanation: '图中作业人员的做法存在安全隐患，不符合规范。',
      point: '10',
    },
    {
      question: '搅拌机作业中，当料斗升起时，严禁任何人在料斗下停留或通过',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，料斗升起时禁止人员在下方停留或通过。',
      explanation: '搅拌机作业时，料斗下方禁止人员停留或通过以防事故。',
      point: '10',
    },
    {
      question: '高处作业吊篮是否属于危险性较大的分部分项工程',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '属于',
        '不属于',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，高处作业吊篮属于危险性较大的工程。',
      explanation: '高处作业吊篮属于危险性较大的分部分项工程，需特殊管理。',
      point: '10',
    },
    {
      question: '高处作业吊篮可以不设置前支腿，安装在女儿墙上',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，吊篮需设置前支腿，不得仅安装在女儿墙上。',
      explanation: '吊篮需设置前支腿以确保稳定性，不得仅靠女儿墙支撑。',
      point: '10',
    },
    {
      question: '用人单位应当保障职业病防治所需的资金投入，不得挤占、挪用，并对因资金投入不足导致的后果承担责任',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，用人单位需保障职业病防治资金并承担责任。',
      explanation: '用人单位需确保职业病防治资金充足并承担相关责任。',
      point: '10',
    },
    {
      question: '离开特种作业岗位达半年以上的特种作业人员，应当重新进行实际操作考核，经确认合格后方可上岗作业',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，离开半年以上需重新考核。',
      explanation: '特种作业人员离岗半年以上需重新进行实际操作考核。',
      point: '10',
    },
    {
      question: '工作时间前后在工作场所内，从事与工作有关的预备性或者收尾性工作受到事故伤害，不属于工伤',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，预备性或收尾性工作受伤属于工伤。',
      explanation: '与工作相关的预备性或收尾性工作受伤属于工伤范围。',
      point: '10',
    },
    {
      question: '吊篮两端应设保险绳，作业人员要挂安全带，安全带不得挂在吊篮升降用的钢丝绳上',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，吊篮需设保险绳，安全带不得挂在升降钢丝绳上。',
      explanation: '吊篮作业需设置保险绳，安全带需挂在专用固定点。',
      point: '10',
    },
    {
      question: '吊篮第一次组装后要经荷载试验合格后，方可投入使用',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，吊篮首次组装需经荷载试验合格。',
      explanation: '吊篮首次组装后需进行荷载试验以确保安全使用。',
      point: '10',
    },
    {
      question: '基坑开挖出的土方，不得堆于基坑边，以免引起地面堆载超负荷',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，基坑边不得堆放土方以防超载。',
      explanation: '基坑边堆放土方可能导致地面超载，引发安全事故。',
      point: '10',
    },
    {
      question: '作业人员高空作业时要有安全立足点，垂直作业要进行隔离防护，光线不足的地方要设置照明灯',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，高空作业需安全立足点、隔离防护和照明。',
      explanation: '高空作业需确保安全立足点、隔离防护和足够照明。',
      point: '10',
    },
    {
      question: '现浇混凝土的梁、板模板支撑的立柱，要经过设计计算确定其间距和纵、横向水平杆及横向斜撑、剪刀撑的设置',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，模板支撑立柱需经设计计算。',
      explanation: '模板支撑立柱的间距和支撑设置需经过设计计算以确保安全。',
      point: '10',
    },
    {
      question: '模板支撑系统必须形成一个整体，用同一种材料搭设，立杆底部要固定，必须加底座或垫板',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，模板支撑需整体搭设并固定底部。',
      explanation: '模板支撑系统需形成整体，立杆底部需加底座或垫板固定。',
      point: '10',
    },
    {
      question: '模板支撑体系搭设过程中，可以在顶部集中堆放物料',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，模板支撑顶部不得集中堆放物料。',
      explanation: '模板支撑顶部集中堆放物料可能导致结构不稳定。',
      point: '10',
    },
    {
      question: '在建工程（含脚手架）的外侧边缘与外电架空线路的边线间小于安全操作距离时，在建工程要设置防护措施',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需设置防护措施以确保安全距离。',
      explanation: '在建工程与外电线路距离不足时需设置防护措施。',
      point: '10',
    },
    {
      question: '在建工程不得在外电架空线路正下方施工、搭设作业棚、建造生活设施堆放物料器材',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，不得在外电线路正下方施工或堆放物料。',
      explanation: '外电线路正下方禁止施工或堆放物料以防触电事故。',
      point: '10',
    },
    {
      question: '外电架空线路架设防护设施时，必须经过有关部门批准，采用线路暂时停电或其他可靠的安全技术措施，并应有电气工程技术人员和专职安全人员监护',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，外电线路防护需批准并有专业人员监护。',
      explanation: '外电线路防护设施需经批准并由专业人员监护。',
      point: '10',
    },
    {
      question: '建筑施工现场临时用电必须符合现行行业标准《施工现场临时用电安全技术规范》JGJ46规定，采用电源中性点直接接地，工作零线与保护零线分开设置，不得混接',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，临时用电需符合JGJ46规范，零线分开设置。',
      explanation: '临时用电需采用中性点接地，工作零线与保护零线分开。',
      point: '10',
    },
    {
      question: '在TN接零保护系统中，通过总漏电保护器的工作零线与保护零线之间不得再做电气连接',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，TN系统中零线不得再次电气连接。',
      explanation: 'TN接零保护系统中，工作零线与保护零线不得再次连接。',
      point: '10',
    },
    {
      question: '照明灯具的金属外壳必须与PE线相连接，照明开关箱内必须装设隔离开关、短路与过载保护器和漏电保护器',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，照明灯具金属外壳需接PE线，开关箱需装设保护器。',
      explanation: '照明灯具金属外壳需接PE线，开关箱需配备多种保护装置。',
      point: '10',
    },
    {
      question: '电缆线路不得拖地及拖地穿过道路敷设，不得直接架空缠绕穿越脚手架敷设，不得缠绕树木敷设',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，电缆线路不得拖地或缠绕敷设。',
      explanation: '电缆线路需规范敷设，避免拖地或缠绕以确保安全。',
      point: '10',
    },
    {
      question: '现场配电线路可使用架空线路或电缆线路，架空线路必须使用绝缘导线',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，架空线路必须使用绝缘导线。',
      explanation: '现场配电架空线路需使用绝缘导线以确保安全。',
      point: '10',
    },
    {
      question: '配电箱内电器、规格参数与设备容量匹配，按规定位置紧固在电器安装板上，严禁用其他金属丝代替熔丝',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，配电箱电器需匹配并禁用金属丝代替熔丝。',
      explanation: '配电箱内电器需匹配设备容量，严禁使用金属丝代替熔丝。',
      point: '10',
    },
    {
      question: '凡用电设备在5台及以上或总容量在50KW及以上者，都要单独编制用电施工组织设计',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，5台及以上或50KW及以上需编制用电组织设计。',
      explanation: '用电设备达5台或总容量50KW以上需单独编制施工组织设计。',
      point: '10',
    },
    {
      question: '临时用电组织设计变更时，可以不履行“编制、审核、批准”程序',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，临时用电组织设计变更需履行程序。',
      explanation: '临时用电组织设计变更必须经过编制、审核、批准程序。',
      point: '10',
    },
    {
      question: '一旦有人触电，应立即切断电源进行急救，电气设备着火，也应立即切断电源，使用可用于扑灭电气火灾的灭火器或干砂灭火',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，触电或电气火灾需立即切断电源并正确灭火。',
      explanation: '触电或电气火灾时需立即切断电源并使用适合的灭火方式。',
      point: '10',
    },
    {
      question: '道路交通及火灾事故自发生之日起7日内，事故造成的伤亡人数发生变化的，应当及时补报',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，伤亡人数变化需在7日内补报。',
      explanation: '事故发生后7日内伤亡人数变化需及时补报。',
      point: '10',
    },
    {
      question: '发生触电（电击）应在现场立即组织抢救，同时向医院紧急求救',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，触电需立即抢救并求助医院。',
      explanation: '触电事故需立即组织现场抢救并联系医院。',
      point: '10',
    },
    {
      question: '搭设龙门架（井字架）时，要设置缆风绳来保持架体稳定，缆风绳要使用钢丝绳，并用地锚在地面固定',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，龙门架需用钢丝绳缆风绳固定。',
      explanation: '龙门架需使用钢丝绳缆风绳并用地锚固定以确保稳定。',
      point: '10',
    },
    {
      question: '龙门架（井字架）超过30m时，也应采用缆风绳固定',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，龙门架超过30m需按规范确定是否用缆风绳。',
      explanation: '龙门架超过30m时需根据设计确定是否使用缆风绳。',
      point: '10',
    },
    {
      question: '卷扬机用的钢丝绳应是合格产品，并符合设计的安全系数的要求，不得有磨损、锈蚀、缺油、断丝。超过标准要立即更换，绳卡应是合格产品并与钢丝绳匹配，钢丝绳要有过路保护，运行时不得拖地',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，卷扬机钢丝绳需符合安全要求并有保护措施。',
      explanation: '卷扬机钢丝绳需合格、符合安全系数并有保护措施。',
      point: '10',
    },
    {
      question: '龙门架与楼层间应设置卸料平台，平台跳板要满铺，两侧应有1.2m高的防护栏杆，并用密目式安全网全封闭',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，龙门架卸料平台需满铺并全封闭。',
      explanation: '卸料平台需满铺跳板、设置1.2m防护栏杆并用安全网全封闭。',
      point: '10',
    },
    {
      question: '物料提升机安装完成，必须经相关单位、人员验收合格，并签字后方可投入使用',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，物料提升机需验收合格后使用。',
      explanation: '物料提升机安装后需经相关单位和人员验收合格。',
      point: '10',
    },
    {
      question: '电梯司机要经过专门的培训学习，经考核发证后方可上岗作业，每班作业前都要按规定进行试车检查，交接班时要做好记录。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，电梯司机需培训、试车并做好记录。',
      explanation: '电梯司机需经过专门培训、考核发证并做好试车和交接记录。',
      point: '10',
    },
    {
      question: '为确保安装拆除过程中的安全，必须预先制定安装、拆卸工程专项施工方案，并由经过专门培训且取得相应操作资格证书的人员操作',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '不正确',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，安装拆除需制定专项方案并由合格人员操作。',
      explanation: '安装拆除工程需制定专项施工方案并由持证人员操作。',
      point: '10',
    },
  ],
};

export default quiz;
