const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产管理 - 多选题',
  quizSynopsis: '本测验涵盖建设工程安全生产管理的多选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '73',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，在规定区域内的施工现场应使用预拌制混凝土及预拌砂浆，采用现场搅拌混凝土或砂浆的场所应采取( )措施。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．封闭',
        'B．降尘',
        'C．降温',
        'D．降噪',
        'E．覆盖',
      ],
      correctAnswer: [0, 1, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．封闭、B．降尘、D．降噪。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场场界噪音排放应符合现行国家标准（ ）的规定。施工现场应对场界（ ）进行监测、记录和控制，并应采取降低噪音的措施。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.噪声排放',
        'B．二氧化碳排放',
        'C．《建筑施工场界噪声排放标准》 GB12523',
        'D．《建筑施工场界环境噪声排放标准》 GB12522',
        'E．《建筑施工场界环境噪声排放标准》 GB12523',
      ],
      correctAnswer: [0, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.噪声排放、E．《建筑施工场界环境噪声排放标准》 GB12523。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场宜选用（ ）的设备，强噪音设备宜设置在远离居民区的一侧，并应采用（ ）吸声材料搭设的防护棚或屏障。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．低噪声',
        'B．高功率',
        'C．低振动',
        'D．高噪声',
        'E．隔声',
      ],
      correctAnswer: [0, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．低噪声、C．低振动、E．隔声。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，制作间灶台及周边应采取宜清洁、耐擦洗措施，墙面处理高度大于（ ），地面应做（ ）和（ ），并保持墙面、地面整洁。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．2.0m',
        'B．1.5m',
        'C．硬化',
        'D．防滑处理',
        'E．覆盖',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B．1.5m、C．硬化、D．防滑处理。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，高层建筑施工超过（ ）层时，宜每隔（ ）层设置临时厕所。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．10',
        'B．2',
        'C．5',
        'D．8',
        'E．4',
      ],
      correctAnswer: [3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：D．8、E．4。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，宿舍内应保证必要的生活空间，室内净高不得小于（ ）m ，通道宽度不得小于（ ）m ，宿舍人员人均面积不得小于（ ）m2 ，每间宿舍居住人员不得超过（ ）人。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A． 2.5m、0.9m',
        'B．3.0m、1m',
        'C．2.4㎡、14人',
        'D．2.5㎡、16人',
        'E．2.5㎡、14人',
      ],
      correctAnswer: [0, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A． 2.5m、0.9m、D．2.5㎡、16人。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场环境突发事件是指在施工现场发生的，造成或可能造成（ ）、（ ）、（ ），危及环境公共安全的一种紧急事件。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．环境状况',
        'B．生命健康',
        'C．财产严重损害',
        'D．安全隐患',
        'E．质量隐患',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．环境状况、B．生命健康、C．财产严重损害。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，拆除建筑物或者构筑物时，应采用（ ）等降噪、降尘措施并及时清理废弃物。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A. 覆盖',
        'B．洒水',
        'C．隔离',
        'D．检测',
        'E．维护',
      ],
      correctAnswer: [0],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A. 覆盖。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，劳动防护用品是指施工人员在生产过程中使用的减少（ ）的防护用品。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．职业危害',
        'B．意外伤害',
        'C．经济',
        'D．适用',
        'E．保护人身安全与健康',
      ],
      correctAnswer: [0, 1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．职业危害、B．意外伤害、E．保护人身安全与健康。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑施工厂界环境噪声排放标准》GB12523的规定，建筑施工现场噪声排放值昼间75dB,夜间55dB。“昼间”是指（ ）的时段，“夜间”是指（ ）的时段。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．6：00-22:00',
        'B．22:00-07:00',
        'C．7:00-22:00',
        'D．22:00-6:00',
        'E．22:00-08:00',
      ],
      correctAnswer: [0, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．6：00-22:00、D．22:00-6:00。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，建筑施工企业严禁使用国家明令淘汰的（ ）、（ ）、（ ）、（ ）和材料。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．技术',
        'B．工艺',
        'C．设备',
        'D．设施',
        'E．工序',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．技术、B．工艺、C．设备、D．设施。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，建筑施工企业新上岗操作工人必须进行岗前教育培训，教育培训应包括（ ）内容。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．事故案例分析',
        'B．安全生产法律法规和规章制度',
        'C．安全操作规程',
        'D．针对性的安全防护措施',
        'E．违章指挥、违章作业、违反劳动纪律产生的后果',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B．安全生产法律法规和规章制度、C．安全操作规程、D．针对性的安全防护措施、E．违章指挥、违章作业、违反劳动纪律产生的后果。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，安全生产费用管理应包括资金的（ ）、（ ）、（ ）、支付、使用、统计、分析、审计检查等工作内容。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．提取',
        'B．管理',
        'C．申请',
        'D．交底',
        'E．审核审批',
      ],
      correctAnswer: [0, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．提取、C．申请、E．审核审批。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，安全生产费用应包括安全技术措施、（ ）、（ ）、（ ）等，以及必要的安全评价、监测、检测、论证所需费用。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．安全交底',
        'B．安全教育培训',
        'C．应急准备',
        'D．劳动保护',
        'E．安全检查',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B．安全教育培训、C．应急准备、D．劳动保护。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，建筑施工企业施工设施、设备和劳动保护用品的安全管理应包括购置、租赁、装拆、验收、（ ）、（ ）、（ ）、（ ）、改造和报废等内容。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．检测',
        'B．使用',
        'C．保养',
        'D．维修',
        'E．材质',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．检测、B．使用、C．保养、D．维修。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，施工企业应自行设计或优先选用（ ）、（ ）、（ ）的安全防护设施。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．标准化',
        'B．程序化',
        'C．先进化',
        'D．工具化',
        'E．定型化',
      ],
      correctAnswer: [0, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．标准化、D．工具化、E．定型化。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，分包方安全生产管理应包括分包单位以及供应商的（ ）、（ ）、（ ）等工作内容。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．选择',
        'B．施工过程管理',
        'C．评价',
        'D．总结',
        'E．分析',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．选择、B．施工过程管理、C．评价。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，施工企业对分包（供）单位检查和考核，应包括（ ）内容。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．分包单位安全生产管理机构的设置、人员配备及资格情况。',
        'B．分包（供）单位违约、违章情况。',
        'C．安全教育培训情况。',
        'D．安全技术交底情况。',
        'E．分包单位安全生产绩效。',
      ],
      correctAnswer: [0, 1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．分包单位安全生产管理机构的设置、人员配备及资格情况。、B．分包（供）单位违约、违章情况。、E．分包单位安全生产绩效。。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，施工企业应全面掌握企业所属工程项目的安全生产状况，并应作为（）（）的依据。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．隐患治理',
        'B．考核奖惩',
        'C．分析总结',
        'D．安全体系',
        'E．质量管理',
      ],
      correctAnswer: [0, 1],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．隐患治理、B．考核奖惩。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，施工企业应定期对安全生产管理的（ ）、（ ）和（ ）进行评估，应确定改进措施，并对其有效性进行跟踪验证和评价。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．先进性',
        'B．科学性',
        'C．适宜性',
        'D．符合性',
        'E．有效性',
      ],
      correctAnswer: [2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：C．适宜性、D．符合性、E．有效性。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，施工企业安全考核和奖惩管理应包括（ ）、（ ）、（ ）等内容。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．确定对象',
        'B．制订内容及标准',
        'C．实施奖惩',
        'D．编制计划',
        'E．制订目标',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．确定对象、B．制订内容及标准、C．实施奖惩。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，拆除工程施工前，应（ ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.编制施工组织设计',
        'B.编制安全专项施工方案',
        'C.编制生产安全事故应急预案。',
        'D.签订施工合同',
        'E.签订安全生产管理协议',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.编制施工组织设计、B.编制安全专项施工方案、C.编制生产安全事故应急预案。、D.签订施工合同、E.签订安全生产管理协议。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，拆除工程施工作业前,应检查的内容包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.拟拆除物的实际状况',
        'B.周边作业环境',
        'C.安全防护措施',
        'D.施工机具',
        'E.人员培训教育情况',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.拟拆除物的实际状况、B.周边作业环境、C.安全防护措施、D.施工机具、E.人员培训教育情况。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，拆除工程施工作业中,应随时检查的内容包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.作业环境',
        'B.作业机具状况',
        'C.物料堆放情况',
        'D.安全防护措施',
        'F.作业人员数量',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.作业环境、B.作业机具状况、C.物料堆放情况、D.安全防护措施。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，拆除工程施工作业后,应检查的内容包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.场地的安全状况',
        'B.环境保护措施',
        'C.作业人员持证上岗情况',
        'D.作业人员的劳保用品',
        'E.人员培训教育情况',
      ],
      correctAnswer: [0, 1],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.场地的安全状况、B.环境保护措施。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，对拆除工程施工的区域，应设置( )，严禁无关人员进入施工区域。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.作业人员资格证公示牌',
        'B.安全警示标志',
        'C.实名制通道',
        'D.硬质封闭围挡',
        'E.项目情况牌',
      ],
      correctAnswer: [1, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B.安全警示标志、D.硬质封闭围挡。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，当采用牵引方式拆除结构柱时，应沿结构柱（ ）剔凿出钢筋，定向牵引后，保留牵引方向（）的钢筋，切断结构柱其他钢筋后再进行后续作业。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.顶部',
        'B.底部',
        'C.中部',
        'D.同侧',
        'E.相反侧',
      ],
      correctAnswer: [1, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B.底部、D.同侧。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，爆破作业装药前，炮孔的验收参数包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.位置',
        'B.间距',
        'C.排距',
        'D.深度',
        'E.形状',
      ],
      correctAnswer: [0],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.位置。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，爆破拆除不得采用（ ）方法',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.电力起爆网路',
        'B.导爆索网路',
        'C.导火索网路',
        'D.导爆管起爆网路',
        'E.电子雷管起爆网路',
      ],
      correctAnswer: [1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B.导爆索网路、C.导火索网路。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，拆除工程施工应建立安全技术档案，应包括下列主要内容:（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.安全技术交底及记录',
        'B.劳务分包和机械租赁合同',
        'C.安全生产管理协议',
        'D.安全专项施工方案',
        'E.脚手架及安全防护设施检查验收记录',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.安全技术交底及记录、B.劳务分包和机械租赁合同、C.安全生产管理协议、D.安全专项施工方案、E.脚手架及安全防护设施检查验收记录。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑拆除工程安全技术规范》JGJ147-2016的内容，下列关于拆除工程说法错误的是（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.拆除工程施工前，应对作业人员进行岗前安全教育和培训，考核合格后方可上岗作业。',
        'B.拆除工程施工前，必须对施工作业人员进行安全技术交底，可以不留存交底记录。',
        'C.拆除工程安全专项施工方案，应经审批后实施;当施工过程中发生变更情况时，应履行相应的审批和论证程序。',
        'D.拆除工程临时使用的脚于架等安全设施，必须逐项查验，并应有验收记录',
        'E.拆除工程可根据施工环境建立消防管理制度。',
      ],
      correctAnswer: [1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B.拆除工程施工前，必须对施工作业人员进行安全技术交底，可以不留存交底记录。、E.拆除工程可根据施工环境建立消防管理制度。。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，施工企业安全生产条件应按照( )内容进行考核',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．安全生产管理',
        'B．安全技术管理',
        'C．设备和设施管理',
        'D．企业市场行为',
        'E．施工现场安全管理',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．安全生产管理、B．安全技术管理、C．设备和设施管理、D．企业市场行为、E．施工现场安全管理。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，安全生产管理评价对企业安全管理制度的建立和落实情况的考核，下列符合的制度有（ ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．安全生产责任制度',
        'B．安全文明资金保障制度',
        'C．安全检查及隐患排查制度',
        'D．生产安全事故报告处理制度',
        'E．安全生产应急救援制度',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．安全生产责任制度、B．安全文明资金保障制度、C．安全检查及隐患排查制度、D．生产安全事故报告处理制度、E．安全生产应急救援制度。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，安全技术管理评价对企业安全技术管理的考核，下列符合考核项目的有（ ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．法规、标准和操作规程配置',
        'B．施工组织设计',
        'C．专项应急救援预案及施工方案（措施）',
        'D．安全技术交底',
        'E．危险源控制',
      ],
      correctAnswer: [0, 1, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．法规、标准和操作规程配置、B．施工组织设计、D．安全技术交底、E．危险源控制。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，设备和设施管理评价企业设备和设施安全管理工作考核内容包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．设备安全装置',
        'B．设备安全管理',
        'C．设施和防护用品',
        'D．安全标志',
        'E．安全检查测试工具',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B．设备安全管理、C．设施和防护用品、D．安全标志、E．安全检查测试工具。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，下列施工企业设备安全管理制度包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．安、拆',
        'B．检查',
        'C．维修、保养',
        'D．备案',
        'E．检测',
      ],
      correctAnswer: [0, 1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．安、拆、B．检查、C．维修、保养、E．检测。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，施工现场安全管理评价考核的内容包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．安全达标',
        'B．安全策划',
        'C．安全文明资金保障',
        'D．资质和资格管理',
        'E．安全方案',
      ],
      correctAnswer: [0, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．安全达标、C．安全文明资金保障、D．资质和资格管理。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，企业市场行为评价考核内容包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．安全生产资质',
        'B．安全生产许可证',
        'C．安全生产文明施工',
        'D．安全质量标准化达标',
        'E．人员管理制度',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B．安全生产许可证、C．安全生产文明施工、D．安全质量标准化达标。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，企业市场行为评价考核安全生产许可证考核分别对那些人员进行考核。（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．企业主要负责人',
        'B．项目负责人',
        'C．企业技术负责人',
        'D．项目技术负责人',
        'E．专职安全管理人员',
      ],
      correctAnswer: [0, 1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．企业主要负责人、B．项目负责人、E．专职安全管理人员。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《施工企业安全生产评价标准》(JGJ/T77-2010)的内容，根据施工企业设备管理制度对在建项目设备哪些内容（ ）进考核。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．管理台账',
        'B．技术档案',
        'C．制度落实',
        'D．人员配备',
        'E．设备使用情况',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．管理台账、B．技术档案、C．制度落实、D．人员配备。',
      explanation: '',
      point: '2',
    },
    {
      question: '施工企业安全标志管理内容包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．安全警示',
        'B．警示标识',
        'C．标志使用',
        'D．区域布置',
        'E．警示区域',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．安全警示、B．警示标识、C．标志使用。',
      explanation: '',
      point: '2',
    },
    {
      question: '建筑施工企业应当加强对本企业和承建工程安全生产条件的日常动态检查，发现不符合法定安全生产条件的，应当( );',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．立即进行整改',
        'B．做好自查和整改记录',
        'C．停止施工',
        'D．向监理单位报告',
        'E．在项目竣工后系统整改',
      ],
      correctAnswer: [0, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．立即进行整改、C．停止施工。',
      explanation: '',
      point: '2',
    },
    {
      question: '建设工程施工现场场容场貌方面主要包括( )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．道路畅通',
        'B．排水沟．排水设施畅通',
        'C．工地地面硬化处理',
        'D．绿化',
        'E．材料堆放',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．道路畅通、B．排水沟．排水设施畅通、C．工地地面硬化处理、D．绿化。',
      explanation: '',
      point: '2',
    },
    {
      question: '下面属于超过一定规模的危险性较大工程的有：( )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．搭设高度50米的落地式钢管脚手架工程',
        'B．开挖深度超过5m(含5m)的基坑工程',
        'C．开挖深度超过5m的基坑支护工程',
        'D．跨度42m的网架结构安装工程',
        'E．开挖深度10m的人工挖孔桩工程',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．搭设高度50米的落地式钢管脚手架工程、B．开挖深度超过5m(含5m)的基坑工程、C．开挖深度超过5m的基坑支护工程。',
      explanation: '',
      point: '2',
    },
    {
      question: '建筑施工现场所涉及的机械设备种类繁多，对于机械设备证件要求各不相同，普通的机械设备主要查验其产品合格证和使用说明书，特种设备主要查验其( )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.特种设备许可证',
        'B.产品合格证',
        'C.特种设备制造监督证明',
        'D.备案证明',
        'E.安装使用说明书和自检说明书',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.特种设备许可证、B.产品合格证、C.特种设备制造监督证明、D.备案证明、E.安装使用说明书和自检说明书。',
      explanation: '',
      point: '2',
    },
    {
      question: '安全检查根据检查内容和检查形式可分为( )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．日常安全检查',
        'B、定期安全检查',
        'C．专业性安全检查',
        'D．季节性及节假日前后安全检查',
        'E．个人检查和集体复查',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．日常安全检查、B、定期安全检查、C．专业性安全检查、D．季节性及节假日前后安全检查。',
      explanation: '',
      point: '2',
    },
    {
      question: '施工前应逐级进行安全技术交底，交底应包括( )、( )、( )、( )等内容。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.工程概况',
        'B.安全技术要求',
        'C.风险状况',
        'D.控制措施和应急处置措施',
        'E.薪资报酬',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.工程概况、B.安全技术要求、C.风险状况、D.控制措施和应急处置措施。',
      explanation: '',
      point: '2',
    },
    {
      question: '建筑施工企业专职安全生产管理人员，是指在企业专职从事安全生产管理工作的人员，包括( )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．企业法定代表人',
        'B．企业分管安全生产工作的副经理',
        'C．经理',
        'D．企业安全生产管理机构的负责人及其工作人员',
        'E．施工现场专职安全生产管理人员',
      ],
      correctAnswer: [3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：D．企业安全生产管理机构的负责人及其工作人员、E．施工现场专职安全生产管理人员。',
      explanation: '',
      point: '2',
    },
    {
      question: '事故的分析处理要遵守“四不放过原则”是( )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．事故原因没有查清不放过',
        'B．事故责任者没有严肃处理不放过',
        'C．生命和财产损失不公示不放过',
        'D．广大职工没有受到教育不放过',
        'E．防范措施没有落实不放过',
      ],
      correctAnswer: [0, 1, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A．事故原因没有查清不放过、B．事故责任者没有严肃处理不放过、D．广大职工没有受到教育不放过、E．防范措施没有落实不放过。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建设工程安全生产管理条例》规定，建设工程施工前，施工单位负责项目管理的技术人员应当对有关安全施工的技术要求向施工( )作出详细说明，并由双方签字确认。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A．施工队伍负责人',
        'B．施工队伍安全员',
        'C．作业班组',
        'D．现场安全员',
        'E．作业人员',
      ],
      correctAnswer: [2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：C．作业班组、E．作业人员。',
      explanation: '',
      point: '2',
    },
    {
      question: '拆除工程应当具备下列哪些要求( )',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.当拆除作业遇有易燃易爆材料时，应采取有效的防火防爆措施。',
        'B.拆除工程应根据施工现场作业环境，制定相应的消防安全措施。',
        'C.拆除工程使用的脚手架安全网必须由专业人员按专项施工方案搭设，经验收合格后方可使用。',
        'D.拆除工程施工必须按施工组织设计安全专项施工方案实施',
        'E.在拆除施工现场划定危险区域，设置警戒线和相关的安全警示标志，并应由专人监护',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.当拆除作业遇有易燃易爆材料时，应采取有效的防火防爆措施。、B.拆除工程应根据施工现场作业环境，制定相应的消防安全措施。、C.拆除工程使用的脚手架安全网必须由专业人员按专项施工方案搭设，经验收合格后方可使用。、D.拆除工程施工必须按施工组织设计安全专项施工方案实施、E.在拆除施工现场划定危险区域，设置警戒线和相关的安全警示标志，并应由专人监护。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑施工安全检查标准》JGJ59-2011内容，建筑施工安全检查安全管理检查评定保证项目应包括（ ）、应急救援。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、安全生产责任制',
        'B、施工组织设计及专项施工方案',
        'C、安全技术交底',
        'D、安全检查',
        'E、安全教育',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、安全生产责任制、B、施工组织设计及专项施工方案、C、安全技术交底、D、安全检查、E、安全教育。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑施工安全检查标准》JGJ59-2011内容，建筑施工安全检查安全管理检查评定一般项目应包括（ ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、分包单位安全管理',
        'B、持证上岗',
        'C、生产安全事故处理',
        'D、安全教育',
        'E、安全检查',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、分包单位安全管理、B、持证上岗、C、生产安全事故处理。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑施工安全检查标准》JGJ59-2011内容，安全技术交底应按（ ）分部分项进行。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、施工工序',
        'B、施工时间',
        'C、施工部位',
        'D、施工顺序',
        'E、施工栋号',
      ],
      correctAnswer: [0, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、施工工序、C、施工部位、E、施工栋号。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑施工安全检查标准》JGJ59-2011内容，安全技术交底应结合施工作业场所状况、特点、工序，对（ ）进行交底。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、危险因素',
        'B、施工方案',
        'C、规范标准',
        'D、操作规程',
        'E、应急措施',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、危险因素、B、施工方案、C、规范标准、D、操作规程、E、应急措施。',
      explanation: '',
      point: '2',
    },
    {
      question: '安全技术交底应由（ ）进行签字确认。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、项目负责人',
        'B、项目技术负责人',
        'C、交底人',
        'D、被交底人',
        'E、专职安全员',
      ],
      correctAnswer: [2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：C、交底人、D、被交底人、E、专职安全员。',
      explanation: '',
      point: '2',
    },
    {
      question: '工程项目部应针对工程特点，进行重大危险源的辨识。应制定防触电、( )、防物体打击等主要内容的专项应急救援预案，并对施工现场易发生重大安全事故的部位、环节进行监控。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、防坍塌',
        'B、防食物中毒',
        'C、防高处坠落',
        'D、防起重及机械伤害',
        'E、防火灾',
      ],
      correctAnswer: [0, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、防坍塌、C、防高处坠落、D、防起重及机械伤害、E、防火灾。',
      explanation: '',
      point: '2',
    },
    {
      question: '总包单位应对承揽分包工程的分包单位进行资质、安全生产许可证和相关人员安全生产资格的审查（ ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、单位资质',
        'B、机械设备合格证',
        'C、安全生产许可证',
        'D、相关人员安全生产资格',
        'E、安全生产责任书',
      ],
      correctAnswer: [0, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、单位资质、C、安全生产许可证、D、相关人员安全生产资格。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑施工安全检查标准》JGJ59-2011内容，建筑施工安全检查文明施工评定，保证项目应包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、现场围挡',
        'B、综合治理',
        'C、材料管理',
        'D、现场防火',
        'E、社区服务',
      ],
      correctAnswer: [0, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、现场围挡、C、材料管理、D、现场防火。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《建筑施工安全检查标准》JGJ59-2011内容，建筑施工安全检查悬挑式钢管脚手架评定保证项目包括（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、架体防护',
        'B、施工方案',
        'C、悬挑钢梁',
        'D、架体稳定',
        'E、交底与验收',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：B、施工方案、C、悬挑钢梁、D、架体稳定、E、交底与验收。',
      explanation: '',
      point: '2',
    },
    {
      question: '施工现场（ ）应设置相应的安全警示标志牌',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A、入口处',
        'B、办公区',
        'C、生活区',
        'D、施工区域',
        'E、危险部位',
      ],
      correctAnswer: [0, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A、入口处、D、施工区域、E、危险部位。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系的组织适用于（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.个体经营者',
        'B.公司、集团、企事业单位',
        'C.行政管理机构',
        'D.慈善机构与社会机构',
        'E.不包含某些组织内的某些职能部门或者组合',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.个体经营者、B.公司、集团、企事业单位、C.行政管理机构、D.慈善机构与社会机构。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，管理体系是指组织用于建立方针和目标以及实现这些目标的过程的一组相互关联或相互作用的要素。体系要素包括（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.组织的结构、角色和职责',
        'B.策划、运行',
        'C.绩效评价和改进',
        'D.考核',
        'E.目标修订与更新',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.组织的结构、角色和职责、B.策划、运行、C.绩效评价和改进。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，最高管理者需要对其在职业健康安全管理体系方面作出承诺，保证其领导作用发挥效力。具体包含（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.对防止与工作相关的伤害和健康损害以及提供健康安全的工作场所和活动全面负责并承担责任；',
        'B.确保职业健康安全方针和相关职业健康安全目标得以建立，并与组织战略方向相一致；',
        'C.确保可获得建立、实施、保持和改进职业健康安全管理体系所需的资源；',
        'D.就有效的职业健康安全管理和符合职业健康安全管理体系要求的重要性进行沟通；',
        'E.指导并支持人员为职业健康安全管理体系的有效性做出贡献；',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.对防止与工作相关的伤害和健康损害以及提供健康安全的工作场所和活动全面负责并承担责任；、B.确保职业健康安全方针和相关职业健康安全目标得以建立，并与组织战略方向相一致；、C.确保可获得建立、实施、保持和改进职业健康安全管理体系所需的资源；、D.就有效的职业健康安全管理和符合职业健康安全管理体系要求的重要性进行沟通；、E.指导并支持人员为职业健康安全管理体系的有效性做出贡献；。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，最高管理者需要对其在职业健康安全管理体系方面作出承诺，保证其领导作用发挥效力。具体包含（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.确保职业健康安全管理体系实现其预期结果；',
        'B.保护工作人员不因报告事件、危险源、风险和机遇而遭受报复；',
        'C.确保组织建立和实施工作人员的协商和参与的过程支持健康安全委员会的建立和运行',
        'D.确保将职业健康安全管理体系要求融入组织业务过程之中；',
        'E.确保体系有效建立并促进持续改进',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.确保职业健康安全管理体系实现其预期结果；、B.保护工作人员不因报告事件、危险源、风险和机遇而遭受报复；、C.确保组织建立和实施工作人员的协商和参与的过程支持健康安全委员会的建立和运行、D.确保将职业健康安全管理体系要求融入组织业务过程之中；、E.确保体系有效建立并促进持续改进。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全方针应（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.包括为防止与工作相关的伤害和健康损害而提供安全和健康的工作条件的承诺，并适合于组织的宗旨和规模、组织所处的环境，以及组织的职业健康安全风险和职业健康安全机遇的特性；',
        'B.为制定职业健康安全目标提供框架;',
        'C.包括满足法律法规要求和其他要求的承诺',
        'D.包括消除危险源和降低职业健康安全风险的承诺,包括持续改进职业健康安全管理体系的承诺',
        'E.包括工作人员及其代表（若有）的协商和参与的承诺',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.包括为防止与工作相关的伤害和健康损害而提供安全和健康的工作条件的承诺，并适合于组织的宗旨和规模、组织所处的环境，以及组织的职业健康安全风险和职业健康安全机遇的特性；、B.为制定职业健康安全目标提供框架;、C.包括满足法律法规要求和其他要求的承诺、D.包括消除危险源和降低职业健康安全风险的承诺,包括持续改进职业健康安全管理体系的承诺、E.包括工作人员及其代表（若有）的协商和参与的承诺。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，在体系的策划过程中，组织应充分考虑法律法规要求和其他要求，做到以下事项（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.组织应建立、实施和保持过程，以确定并获取最新的适用于组织的危险源、职业健康安全风险和职业健康安全管理体系的法律法规要求和其他要求',
        'B.组织应建立、实施和保持过程，确定如何将这些法律法规要求和其他要求应用于组织，以及所需沟通的内容',
        'C.组织应建立、实施和保持过程，在建立、实施、保持和持续改进其职业健康安全管理体系时，必须考虑这些法律法规要求和其他要求',
        'D.组织应保持和保留有关法律法规要求和其他要求的文件化信息，并确保及时更新以反映任何变化。',
        'E.组织应建立、实施、保持过程，确定法律法规和其它要求所涉及的绩效评价与评审的内容，进行评审实施与策划',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.组织应建立、实施和保持过程，以确定并获取最新的适用于组织的危险源、职业健康安全风险和职业健康安全管理体系的法律法规要求和其他要求、B.组织应建立、实施和保持过程，确定如何将这些法律法规要求和其他要求应用于组织，以及所需沟通的内容、C.组织应建立、实施和保持过程，在建立、实施、保持和持续改进其职业健康安全管理体系时，必须考虑这些法律法规要求和其他要求、D.组织应保持和保留有关法律法规要求和其他要求的文件化信息，并确保及时更新以反映任何变化。。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，创建和更新文件化信息时，组织应确保适当的（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.标识和说明（如标题、日期、作者或文件编号）',
        'B.形式（如语言文字、软件版本、图表）与载体（如纸质载体、电子载体）',
        'C.评审和批准，以确保适宜性和充分性',
        'D.证实满足法律法规要求和其他要求的需要',
        'E.建立系统的规则',
      ],
      correctAnswer: [0, 1, 2],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.标识和说明（如标题、日期、作者或文件编号）、B.形式（如语言文字、软件版本、图表）与载体（如纸质载体、电子载体）、C.评审和批准，以确保适宜性和充分性。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应该对危险源辨识出的潜在紧急情况进行应急准备并做出响应，建立、实施和保持所需的过程。包括的情形有（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.针对紧急情况建立所策划的响应，包括提供急救',
        'B.为所策划的响应提供培训',
        'C.定期测试和演练所策划的响应能力',
        'D.与承包方、访问者、应急响应服务机构、政府部门、当地社区（适当时）沟通相关信息',
        'E.邀请第三方团队来进行服务于指导',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.针对紧急情况建立所策划的响应，包括提供急救、B.为所策划的响应提供培训、C.定期测试和演练所策划的响应能力、D.与承包方、访问者、应急响应服务机构、政府部门、当地社区（适当时）沟通相关信息。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应该对危险源辨识出的潜在紧急情况进行应急准备并做出响应，建立、实施和保持所需的过程。包括的情形有（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A. 与所有工作人员沟通并提供与其义务和职责有关的信息',
        'B. 评价绩效，必要时（包括在测试之后，尤其是在紧急情况发生之后）修订所策划的响应',
        'C. 必须考虑所有有关相关方的需求和能力，适当时确保其参与制定所策划的响应',
        'D.组织应保持和保留关于响应潜在紧急情况的过程和计划的文件化信息',
        'E.邀请第三方团队来进行服务于指导',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A. 与所有工作人员沟通并提供与其义务和职责有关的信息、B. 评价绩效，必要时（包括在测试之后，尤其是在紧急情况发生之后）修订所策划的响应、C. 必须考虑所有有关相关方的需求和能力，适当时确保其参与制定所策划的响应、D.组织应保持和保留关于响应潜在紧急情况的过程和计划的文件化信息。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织对体系的监视和测量，所包含的内容有（）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A. 满足法律法规要求和其他要求的程度',
        'B.与所辨识的危险源、风险和机遇相关的活动和运行',
        'C.实现组织职业健康安全目标的进展情况',
        'D.运行控制的有效性',
        'E.发布监视和测量的准则',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A. 满足法律法规要求和其他要求的程度、B.与所辨识的危险源、风险和机遇相关的活动和运行、C.实现组织职业健康安全目标的进展情况、D.运行控制的有效性。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应建立、实施和保持用于对法律法规要求和其他要求的合规性进行评价的过程，具体有（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.确定实施合规性评价的频次和方法',
        'B.评价合规性，并在需要时采取措施',
        'C.保持对其关于法律法规要求和其他要求的合规状况的认识和理解',
        'D.保留合规性评价结果的文件化信息',
        'E.做好合规性评价的协商与沟通',
      ],
      correctAnswer: [0, 1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.确定实施合规性评价的频次和方法、B.评价合规性，并在需要时采取措施、C.保持对其关于法律法规要求和其他要求的合规状况的认识和理解、D.保留合规性评价结果的文件化信息。',
      explanation: '',
      point: '2',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系可以通过以下哪些方式进行持续改进（ ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'A.提升职业健康安全绩效',
        'B.促进支持职业健康安全管理体系的文化',
        'C.促进工作人员参与职业健康安全管理体系持续改进措施的实施',
        'D.就有关持续改进的结果与工作人员及其代表进行沟通',
        'E.保持和保留文件化信息作为持续改进的证据',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案包括：A.提升职业健康安全绩效、B.促进支持职业健康安全管理体系的文化、C.促进工作人员参与职业健康安全管理体系持续改进措施的实施、D.就有关持续改进的结果与工作人员及其代表进行沟通、E.保持和保留文件化信息作为持续改进的证据。',
      explanation: '根据相关规范',
      point: '2',
    },
  ],
};

export default quiz;
