const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产管理 - 案例题',
  quizSynopsis: '本测验涵盖建设工程安全生产管理的案例题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '77',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '张某在县城某工地，从事后期修补工作。项目部因后期现场条件受限，宿舍及办公区设置于在建商铺内。工人宿舍设置在商铺一层采用通铺，每间商铺内住20人。职工食堂紧靠厕所，无隔油池及油烟净化装置，食堂操作人员非专业厨师，上岗作业期间未佩戴口罩，服装不整洁。 宿舍及办公区允许设置在建商铺内。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '张某在县城某工地，从事后期修补工作。项目部因后期现场条件受限，宿舍及办公区设置于在建商铺内。工人宿舍设置在商铺一层采用通铺，每间商铺内住20人。职工食堂紧靠厕所，无隔油池及油烟净化装置，食堂操作人员非专业厨师，上岗作业期间未佩戴口罩，服装不整洁。 施工现场生活区宿舍，每间房内最多允许住（ ）人。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．20',
        'B．16',
        'C. 12',
        'D.8',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．16。',
      explanation: '',
      point: '1',
    },
    {
      question: '张某在县城某工地，从事后期修补工作。项目部因后期现场条件受限，宿舍及办公区设置于在建商铺内。工人宿舍设置在商铺一层采用通铺，每间商铺内住20人。职工食堂紧靠厕所，无隔油池及油烟净化装置，食堂操作人员非专业厨师，上岗作业期间未佩戴口罩，服装不整洁。 食堂未设置隔油池及油烟净化装置，不符合相关规定要求。( ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '张某在县城某工地，从事后期修补工作。项目部因后期现场条件受限，宿舍及办公区设置于在建商铺内。工人宿舍设置在商铺一层采用通铺，每间商铺内住20人。职工食堂紧靠厕所，无隔油池及油烟净化装置，食堂操作人员非专业厨师，上岗作业期间未佩戴口罩，服装不整洁。 食堂操作人员上岗期间应佩戴口罩、穿着整洁。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某市一建设项目，因施工工艺要求，分为昼夜连续施工，夜间进行施工过程中，施工现场内车辆鸣笛高速行驶，导致路面扬尘。靠近居民区一边噪音值为75dB，远离居民区一边噪音值为103dB。现场材料装卸过程中，由车辆自卸产生较大噪音。周围居民多次进行投诉，建设项目仍未采取相关措施。 车辆在施工现场不允许鸣笛高速行驶。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某市一建设项目，因施工工艺要求，分为昼夜连续施工，夜间进行施工过程中，施工现场内车辆鸣笛高速行驶，导致路面扬尘。靠近居民区一边噪音值为75dB，远离居民区一边噪音值为103dB。现场材料装卸过程中，由车辆自卸产生较大噪音。周围居民多次进行投诉，建设项目仍未采取相关措施。 靠近居民区噪音值75dB在噪音排放标准内。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某市一建设项目，因施工工艺要求，分为昼夜连续施工，夜间进行施工过程中，施工现场内车辆鸣笛高速行驶，导致路面扬尘。靠近居民区一边噪音值为75dB，远离居民区一边噪音值为103dB。现场材料装卸过程中，由车辆自卸产生较大噪音。周围居民多次进行投诉，建设项目仍未采取相关措施。 材料装卸过程中应该轻拿轻放，避免产生较大噪音。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某市一建设项目，因施工工艺要求，分为昼夜连续施工，夜间进行施工过程中，施工现场内车辆鸣笛高速行驶，导致路面扬尘。靠近居民区一边噪音值为75dB，远离居民区一边噪音值为103dB。现场材料装卸过程中，由车辆自卸产生较大噪音。周围居民多次进行投诉，建设项目仍未采取相关措施。 施工现场裸露的场地和堆放的土方应采取（ ）、固化或绿化等措施。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．覆盖',
        'B．洒水',
        'C. 隔离',
        'D. 清扫',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．覆盖。',
      explanation: '',
      point: '1',
    },
    {
      question: '某采石场地的作业场所存在大量的白云石粉和大理石粉，为防止粉尘飞扬，降低作业场所粉尘浓度，有效防范职业危害，采取了局部送风和排风净化除尘的措施。 该采石场主要采取的控制技术措施有效。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某采石场地的作业场所存在大量的白云石粉和大理石粉，为防止粉尘飞扬，降低作业场所粉尘浓度，有效防范职业危害，采取了局部送风和排风净化除尘的措施。 该采石场采取的控制技术措施无效，应采用湿式作业和密闭抽风除尘措施。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某采石场地的作业场所存在大量的白云石粉和大理石粉，为防止粉尘飞扬，降低作业场所粉尘浓度，有效防范职业危害，采取了局部送风和排风净化除尘的措施。 长期在采石场工作的作业人员发生职业病并经鉴定与该工作环境有直接关系的可以提出相关职业病赔偿。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某生态旅游风景区建设项目，发生一起火灾事故，事故造成1人死亡、2人重伤。事故发生后，现场有关人员立即如实向本企业负责人报告，并逐级上报事故。事故调查中发现该项目部未编制消防应急救援预案，未开展消防应急演练。根据以上内容，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011），企业负责人按规定应在（ ）内如实向事故发生地县级以上人民政府建设主管部门和有关部门报告。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．0.5h',
        'B．1.5h',
        'C．1h',
        'D．2h',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C．1h。',
      explanation: '',
      point: '1',
    },
    {
      question: '某生态旅游风景区建设项目，发生一起火灾事故，事故造成1人死亡、2人重伤。事故发生后，现场有关人员立即如实向本企业负责人报告，并逐级上报事故。事故调查中发现该项目部未编制消防应急救援预案，未开展消防应急演练。根据以上内容，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011），施工企业生产安全事故报告应包括导致事故发生的主要原因分析。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某生态旅游风景区建设项目，发生一起火灾事故，事故造成1人死亡、2人重伤。事故发生后，现场有关人员立即如实向本企业负责人报告，并逐级上报事故。事故调查中发现该项目部未编制消防应急救援预案，未开展消防应急演练。根据以上内容，回答下列问题： 该事故造成1人死亡、2人重伤，属于较大事故。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.对',
        'B.错',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.错。',
      explanation: '',
      point: '1',
    },
    {
      question: '某生态旅游风景区建设项目，发生一起火灾事故，事故造成1人死亡、2人重伤。事故发生后，现场有关人员立即如实向本企业负责人报告，并逐级上报事故。事故调查中发现该项目部未编制消防应急救援预案，未开展消防应急演练。根据以上内容，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011），项目部应组织对现场管理人员进行应急救援预案的培训和交底，定期组织专项应急演练。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.对',
        'B.错',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.对。',
      explanation: '',
      point: '1',
    },
    {
      question: 'A 公司委托具有相应资质的 K 企业承接 3 厂房顶棚夹芯彩钢板更换工程。K 企业作业人员进入现场施工，搭建了移动式脚手架，施工作业过程中，K 企业临时雇佣 5 名作业人员参与现场作业时，移动式脚手架踏板与脚手架之间的挂钩突然脱开，导致踏板脱落，随即脚手架倒塌，造成脚手架上 3 名作业人员坠落地面，地面 10 名作业人员被脱落的踏板、倒塌的脚手架砸伤。事故导致 10 人重伤、3 人轻伤。事故调查中发现，施工单位未对临时雇佣的 5 名作业人员进行安全培训和安全技术交底；作业过程中，移动式脚手架滑轮未锁定；现场安全管理人员未及时发现隐患。根据以上场景，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011）和《生产安全事故报告和调查处理条例》，该起事故的等级为。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.重大事故',
        'B.一般事故',
        'C.较大事故',
        'D.特大事故',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C.较大事故。',
      explanation: '',
      point: '1',
    },
    {
      question: 'A 公司委托具有相应资质的 K 企业承接 3 厂房顶棚夹芯彩钢板更换工程。K 企业作业人员进入现场施工，搭建了移动式脚手架，施工作业过程中，K 企业临时雇佣 5 名作业人员参与现场作业时，移动式脚手架踏板与脚手架之间的挂钩突然脱开，导致踏板脱落，随即脚手架倒塌，造成脚手架上 3 名作业人员坠落地面，地面 10 名作业人员被脱落的踏板、倒塌的脚手架砸伤。事故导致 10 人重伤、3 人轻伤。事故调查中发现，施工单位未对临时雇佣的 5 名作业人员进行安全培训和安全技术交底；作业过程中，移动式脚手架滑轮未锁定；现场安全管理人员未及时发现隐患。根据以上场景，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011）施工企业通过（ ）掌握安全生产管理活动运行的动态，发现并纠正安全生产管理活动或结果的偏差，并为确定和采取纠正措施或预防措施提供信息。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.安全教育',
        'B.安全检查',
        'C.安全交底',
        'D.安全例会',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.安全检查。',
      explanation: '',
      point: '1',
    },
    {
      question: 'A 公司委托具有相应资质的 K 企业承接 3 厂房顶棚夹芯彩钢板更换工程。K 企业作业人员进入现场施工，搭建了移动式脚手架，施工作业过程中，K 企业临时雇佣 5 名作业人员参与现场作业时，移动式脚手架踏板与脚手架之间的挂钩突然脱开，导致踏板脱落，随即脚手架倒塌，造成脚手架上 3 名作业人员坠落地面，地面 10 名作业人员被脱落的踏板、倒塌的脚手架砸伤。事故导致 10 人重伤、3 人轻伤。事故调查中发现，施工单位未对临时雇佣的 5 名作业人员进行安全培训和安全技术交底；作业过程中，移动式脚手架滑轮未锁定；现场安全管理人员未及时发现隐患。根据以上场景，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011），K 企业应该对临时雇佣的 5 名作业人员进行岗前安全教育培训。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.对',
        'B.错',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.对。',
      explanation: '',
      point: '1',
    },
    {
      question: 'A 公司委托具有相应资质的 K 企业承接 3 厂房顶棚夹芯彩钢板更换工程。K 企业作业人员进入现场施工，搭建了移动式脚手架，施工作业过程中，K 企业临时雇佣 5 名作业人员参与现场作业时，移动式脚手架踏板与脚手架之间的挂钩突然脱开，导致踏板脱落，随即脚手架倒塌，造成脚手架上 3 名作业人员坠落地面，地面 10 名作业人员被脱落的踏板、倒塌的脚手架砸伤。事故导致 10 人重伤、3 人轻伤。事故调查中发现，施工单位未对临时雇佣的 5 名作业人员进行安全培训和安全技术交底；作业过程中，移动式脚手架滑轮未锁定；现场安全管理人员未及时发现隐患。根据以上场景，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011）,为有效预防此类事故再次发生，应采取的安全技术措施包括搭设有效可靠的脚手架、踏板满铺，不使用单板、浮板和探头板和设置符合标准的防护栏杆。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.对',
        'B.错',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.对。',
      explanation: '',
      point: '1',
    },
    {
      question: '某施工单位具有房屋建筑工程施工总承包特级资质，在某城市承接了装配式住宅小区工程，建筑面积 170000㎡，单体工程设计高度为 68m。工程处于主体结构施工阶段。 现场情况包括：基坑降水（开挖深度 7.80m）、落地式扣件钢管脚手架（搭设高度 25m）、悬挑式脚手架、型钢悬挑卸料平台、施工升降机、装配式建筑混凝土预制构件安装和混凝土模板支撑体系（搭设高度 4m、跨度 20m）。根据以上场景，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011），该施工单位应设置安全生产管理机构，配备专职安全生产管理人员至少应为（ ）。 【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.4 人',
        'B.5 人',
        'C.6 人',
        'D.7人',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C.6 人。',
      explanation: '',
      point: '1',
    },
    {
      question: '某施工单位具有房屋建筑工程施工总承包特级资质，在某城市承接了装配式住宅小区工程，建筑面积 170000㎡，单体工程设计高度为 68m。工程处于主体结构施工阶段。 现场情况包括：基坑降水（开挖深度 7.80m）、落地式扣件钢管脚手架（搭设高度 25m）、悬挑式脚手架、型钢悬挑卸料平台、施工升降机、装配式建筑混凝土预制构件安装和混凝土模板支撑体系（搭设高度 4m、跨度 20m）。根据以上场景，回答下列问题： 2. 根据根据《施工企业安全生产管理规范》（GB50656-2011），施工企业应根据施工组织设计、专项安全施工方案（措施）编制和审批权限的设置，分级进行安全技术交底，编制人员应参与安全技术交底、验收和检查。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.对',
        'B.错',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.对。',
      explanation: '',
      point: '1',
    },
    {
      question: '某施工单位具有房屋建筑工程施工总承包特级资质，在某城市承接了装配式住宅小区工程，建筑面积 170000㎡，单体工程设计高度为 68m。工程处于主体结构施工阶段。 现场情况包括：基坑降水（开挖深度 7.80m）、落地式扣件钢管脚手架（搭设高度 25m）、悬挑式脚手架、型钢悬挑卸料平台、施工升降机、装配式建筑混凝土预制构件安装和混凝土模板支撑体系（搭设高度 4m、跨度 20m）。根据以上场景，回答下列问题： 根据《施工企业安全生产管理规范》（GB50656-2011），工程项目部在组织装配式建筑混凝土预制构件安全施工时，项目技术负责人向现场管理人员进行方案交底，在施工现场显著位置公告危险性较大的分部分项工程名称、施工时间和责任人员，项目专职安全生产管理人员组织模板支撑体系验收。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.对',
        'B.错',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.错。',
      explanation: '',
      point: '1',
    },
    {
      question: '某施工单位具有房屋建筑工程施工总承包特级资质，在某城市承接了装配式住宅小区工程，建筑面积 170000㎡，单体工程设计高度为 68m。工程处于主体结构施工阶段。 现场情况包括：基坑降水（开挖深度 7.80m）、落地式扣件钢管脚手架（搭设高度 25m）、悬挑式脚手架、型钢悬挑卸料平台、施工升降机、装配式建筑混凝土预制构件安装和混凝土模板支撑体系（搭设高度 4m、跨度 20m）。根据以上场景，回答下列问题： 落地式扣件钢管脚手架（搭设高度 25m）属于危险性较大的分部分项工程，型钢悬挑卸料平台不属于危险性较大的分部分项工程。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.对',
        'B.错',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.错。',
      explanation: '',
      point: '1',
    },
    {
      question: '甲公司将某四层现浇混凝土结构的房屋拆除项目委托给乙公司，由于工程量小，工期短，甲乙双方未签订承包合同和安全管理协议。乙公司组织相关技术和安全人员现场实地查看后，认为拆除工程简单，直接找到丙施工队，由丙具体负责拆除施工；拆除至三层西墙体时，作业人员用大锤对墙下1米处先凿洞、再掏空，最后砸断四周柱脚，致使墙柱突然垮塌，导致3人死亡、2人受伤。根据以上场景，回答下列问题： 甲乙双方未签订承包合同和安全管理协议的做法是否正确。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.正确',
        'B.错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '甲公司将某四层现浇混凝土结构的房屋拆除项目委托给乙公司，由于工程量小，工期短，甲乙双方未签订承包合同和安全管理协议。乙公司组织相关技术和安全人员现场实地查看后，认为拆除工程简单，直接找到丙施工队，由丙具体负责拆除施工；拆除至三层西墙体时，作业人员用大锤对墙下1米处先凿洞、再掏空，最后砸断四周柱脚，致使墙柱突然垮塌，导致3人死亡、2人受伤。根据以上场景，回答下列问题： 下列的说法错误的是（ ）【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.乙公司应编制拆除工程安全专项施工方案，并履行相应的审批和论证程序。',
        'B.丙施工队应组织对作业人员进行安全技术交底',
        'C.乙公司应组织对作业人员进行安全技术交底',
        'D.乙公司和丙施工队不需要签订安全生产协议',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D.乙公司和丙施工队不需要签订安全生产协议。',
      explanation: '',
      point: '1',
    },
    {
      question: '甲公司将某四层现浇混凝土结构的房屋拆除项目委托给乙公司，由于工程量小，工期短，甲乙双方未签订承包合同和安全管理协议。乙公司组织相关技术和安全人员现场实地查看后，认为拆除工程简单，直接找到丙施工队，由丙具体负责拆除施工；拆除至三层西墙体时，作业人员用大锤对墙下1米处先凿洞、再掏空，最后砸断四周柱脚，致使墙柱突然垮塌，导致3人死亡、2人受伤。根据以上场景，回答下列问题： 乙公司应安全专职安全员现场旁站监督，及时制止施工队的违章行为',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.正确',
        'B.错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '甲公司将某四层现浇混凝土结构的房屋拆除项目委托给乙公司，由于工程量小，工期短，甲乙双方未签订承包合同和安全管理协议。乙公司组织相关技术和安全人员现场实地查看后，认为拆除工程简单，直接找到丙施工队，由丙具体负责拆除施工；拆除至三层西墙体时，作业人员用大锤对墙下1米处先凿洞、再掏空，最后砸断四周柱脚，致使墙柱突然垮塌，导致3人死亡、2人受伤。根据以上场景，回答下列问题： 施工队的拆除顺序是否正确',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.正确',
        'B.错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某改造工程，用爆破法拆除一栋四层砖混住宅楼时，爆破队现场负责人为减少爆破装药量，不按爆破方案实施，擅自更改方案，组织工人用大锤将楼房底部承重墙每隔0.5-0.8米凿开若干孔洞，承重墙面积减至原有的1/4左右，造成底层墙体承载力严重不足，楼房整体坍塌，造成2人死亡，10人重伤。根据以上场景，回答下列问题： 拆除方案变更后应重新进行报审报批，经审批通过后方可实施。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.正确',
        'B.错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某改造工程，用爆破法拆除一栋四层砖混住宅楼时，爆破队现场负责人为减少爆破装药量，不按爆破方案实施，擅自更改方案，组织工人用大锤将楼房底部承重墙每隔0.5-0.8米凿开若干孔洞，承重墙面积减至原有的1/4左右，造成底层墙体承载力严重不足，楼房整体坍塌，造成2人死亡，10人重伤。根据以上场景，回答下列问题： 拆除作业前，现场安全员应对作业人员进行详细的安全技术交底。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.正确',
        'B.错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某改造工程，用爆破法拆除一栋四层砖混住宅楼时，爆破队现场负责人为减少爆破装药量，不按爆破方案实施，擅自更改方案，组织工人用大锤将楼房底部承重墙每隔0.5-0.8米凿开若干孔洞，承重墙面积减至原有的1/4左右，造成底层墙体承载力严重不足，楼房整体坍塌，造成2人死亡，10人重伤。根据以上场景，回答下列问题： 爆破队作业人员实际采用的拆除方法为（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.人工拆除',
        'B.机械拆除',
        'C.爆破拆除',
        'D.静力破碎拆除',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.人工拆除。',
      explanation: '',
      point: '1',
    },
    {
      question: '某改造工程，用爆破法拆除一栋四层砖混住宅楼时，爆破队现场负责人为减少爆破装药量，不按爆破方案实施，擅自更改方案，组织工人用大锤将楼房底部承重墙每隔0.5-0.8米凿开若干孔洞，承重墙面积减至原有的1/4左右，造成底层墙体承载力严重不足，楼房整体坍塌，造成2人死亡，10人重伤。根据以上场景，回答下列问题： “工人用大锤将楼房底部承重墙每隔0.5-0.8米凿开若干孔洞”的拆除顺序是正确的。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.正确',
        'B.错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某改造工程，用爆破法拆除一栋四层砖混住宅楼时，爆破队现场负责人为减少爆破装药量，不按爆破方案实施，擅自更改方案，组织工人用大锤将楼房底部承重墙每隔0.5-0.8米凿开若干孔洞，承重墙面积减至原有的1/4左右，造成底层墙体承载力严重不足，楼房整体坍塌，造成2人死亡，10人重伤。根据以上场景，回答下列问题： 按照安全生产事故等级划分标准，此次坍塌事故的等级为（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.一般事故',
        'B.较大事故',
        'C.重大事故',
        'D.特别重大事故',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.较大事故。',
      explanation: '',
      point: '1',
    },
    {
      question: '某建筑企业公司在建项目，在应对施工企业安全生产考核时，各项制度的落实，及资料的整编均不符合要求，并在资料检查过程中发现有安全事故发生，评定考核不合格，则该项目被下发停工令，限期整改，并上报复检。根据以上内容，回答下列问题： 根据《施工企业安全生产评价标准》，下列不属于施工现场安全管理评价评定项目的是（ ）【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．安全生产责任制度',
        'B．安全文明资金保障制度',
        'C．安全教育培训制度',
        'D．施工组织设计',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D．施工组织设计。',
      explanation: '',
      point: '1',
    },
    {
      question: '某建筑企业公司在建项目，在应对施工企业安全生产考核时，各项制度的落实，及资料的整编均不符合要求，并在资料检查过程中发现有安全事故发生，评定考核不合格，则该项目被下发停工令，限期整改，并上报复检。根据以上内容，回答下列问题： 施工企业安全生产条件单项评价的内容包括（ ）分项。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．2',
        'B．3',
        'C．4',
        'D．5',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C．4。',
      explanation: '',
      point: '1',
    },
    {
      question: '某建筑企业公司在建项目，在应对施工企业安全生产考核时，各项制度的落实，及资料的整编均不符合要求，并在资料检查过程中发现有安全事故发生，评定考核不合格，则该项目被下发停工令，限期整改，并上报复检。根据以上内容，回答下列问题： 施工企业安全生产业绩单项评价的内容应（ ）个分项。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．2',
        'B．3',
        'C．4',
        'D．5',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C．4。',
      explanation: '',
      point: '1',
    },
    {
      question: '某建筑企业公司在建项目，在应对施工企业安全生产考核时，各项制度的落实，及资料的整编均不符合要求，并在资料检查过程中发现有安全事故发生，评定考核不合格，则该项目被下发停工令，限期整改，并上报复检。根据以上内容，回答下列问题： 安全防护措施和（ ）不符合安全色与安全标志规定要求，扣5分。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．警示、警告标识',
        'B．安全设施',
        'C．安全记录',
        'D．安全标志',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．警示、警告标识。',
      explanation: '',
      point: '1',
    },
    {
      question: '某建筑企业公司在建项目，在应对施工企业安全生产考核时，各项制度的落实，及资料的整编均不符合要求，并在资料检查过程中发现有安全事故发生，评定考核不合格，则该项目被下发停工令，限期整改，并上报复检。根据以上内容，回答下列问题： 施工企业安全生产评价标准评定为基本合格的的前提条件是：如果造成安全事故造成死亡人数累计超过（ ）人，或直接造成经济损失累计（ ）万元以上，则评定为不合格。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．2 30',
        'B．3 30',
        'C．2 50',
        'D．5 50',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．3 30。',
      explanation: '',
      point: '1',
    },
    {
      question: '上海某项目应总承包及分包主要管理人员未持证在岗履职，检查过程中发现各项评定工作未按要求开展实施，并且过程中签字弄虚作假，与要求不匹配；相关人员也未进行安全教育，保险未办理。根据以上内容，回答下列问题： 建筑施工企业应进行年度安全生产自我评价，评价人员不应少于（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．3',
        'B．4',
        'C．5',
        'D．6',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．3。',
      explanation: '',
      point: '1',
    },
    {
      question: '上海某项目应总承包及分包主要管理人员未持证在岗履职，检查过程中发现各项评定工作未按要求开展实施，并且过程中签字弄虚作假，与要求不匹配；相关人员也未进行安全教育，保险未办理。根据以上内容，回答下列问题： 建筑施工企业安全生产管理人员安全生产考核合格证书有效期为（ ）年，证书在全馆范围内有效。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．2',
        'B．3',
        'C．5',
        'D．6',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．3。',
      explanation: '',
      point: '1',
    },
    {
      question: '上海某项目应总承包及分包主要管理人员未持证在岗履职，检查过程中发现各项评定工作未按要求开展实施，并且过程中签字弄虚作假，与要求不匹配；相关人员也未进行安全教育，保险未办理。根据以上内容，回答下列问题： 总承包的施工项目，从事危险作业人员的意外伤害保险费由（ ）支付。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．建设单位',
        'B．总承包单位',
        'C．分包单位',
        'D．企业',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．总承包单位。',
      explanation: '',
      point: '1',
    },
    {
      question: '上海某项目应总承包及分包主要管理人员未持证在岗履职，检查过程中发现各项评定工作未按要求开展实施，并且过程中签字弄虚作假，与要求不匹配；相关人员也未进行安全教育，保险未办理。根据以上内容，回答下列问题： ( )的特种设备的目录由国务院负责特种设备安全监督管理的部门制定，报国务院批准后执行。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．涉及生命安全、危险性较大',
        'B．涉及有使用风险',
        'C．涉及工程建设',
        'D．涉及工程施工危险管控',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．涉及生命安全、危险性较大。',
      explanation: '',
      point: '1',
    },
    {
      question: '上海某项目应总承包及分包主要管理人员未持证在岗履职，检查过程中发现各项评定工作未按要求开展实施，并且过程中签字弄虚作假，与要求不匹配；相关人员也未进行安全教育，保险未办理。根据以上内容，回答下列问题： 生产经营单位对重大危险源应当( )进行定期检测、评估、监控，并制定应急预案，告知从业人员和相关人员在紧急情况下应当采取的应急措施。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．坚决弃置',
        'B．登记建档',
        'C．保安安全',
        'D．专人管理',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．登记建档。',
      explanation: '',
      point: '1',
    },
    {
      question: '廊坊建筑公司承建市政府办公楼项目，由具有相应资质的廊坊二建承担在施工现场安装、拆卸施工起重机械和整体提升脚手架、模板等自升式架设设施的任务，整个工程由廊坊市建筑设计院设计，远达监理公司监理，部分工程分包给原北二建、原北四建。根据以上场景，回答下列问题： 为赶工期，廊坊建筑公司可以和原北二建共同在施工现场安装、拆卸施工起重机械。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '廊坊建筑公司承建市政府办公楼项目，由具有相应资质的廊坊二建承担在施工现场安装、拆卸施工起重机械和整体提升脚手架、模板等自升式架设设施的任务，整个工程由廊坊市建筑设计院设计，远达监理公司监理，部分工程分包给原北二建、原北四建。根据以上场景，回答下列问题： 因为原北二建经常安装、拆卸施工起重机械和整体提升脚手架、模板等自升式架设设施，所以对此项目不必单独编制拆装方案、制定安全施工措施。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '廊坊建筑公司承建市政府办公楼项目，由具有相应资质的廊坊二建承担在施工现场安装、拆卸施工起重机械和整体提升脚手架、模板等自升式架设设施的任务，整个工程由廊坊市建筑设计院设计，远达监理公司监理，部分工程分包给原北二建、原北四建。根据以上场景，回答下列问题： 施工起重机械和整体提升脚手架、模板等自升式架设设施安装完毕后，原北二建应当自检，出具自检合格证明，并向廊坊建筑公司进行安全使用说明，办理验收手续并签字。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '廊坊建筑公司承建市政府办公楼项目，由具有相应资质的廊坊二建承担在施工现场安装、拆卸施工起重机械和整体提升脚手架、模板等自升式架设设施的任务，整个工程由廊坊市建筑设计院设计，远达监理公司监理，部分工程分包给原北二建、原北四建。根据以上场景，回答下列问题： 远达监理公司监理时应偏向廊坊建筑公司。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '廊坊建筑公司承建市政府办公楼项目，由具有相应资质的廊坊二建承担在施工现场安装、拆卸施工起重机械和整体提升脚手架、模板等自升式架设设施的任务，整个工程由廊坊市建筑设计院设计，远达监理公司监理，部分工程分包给原北二建、原北四建。根据以上场景，回答下列问题： 廊坊建筑公司是建筑施工企业，单位主要负责人是张三，该公司现承建市政府办公楼项目，由李四担任项目经理，王五担任项目副经理，赵六是廊坊建筑公司的安全生产部门经理，（ ）对本单位的安全生产工作全面负责。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．张三',
        'B．李四',
        'C、王五',
        'D．赵六',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．张三。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，搭设悬挑式外防护脚手架，下方有钢筋绑扎人员在进行钢筋绑扎作业。项目部安全员刘某在现场巡查过程中发现此处存在垂直交叉作业，在联系劳务经理文某后离开，文某在收到通知后未及时处理。外架工何某在作业时扳手掉落至钢筋制作人员徐某砸伤。请判断下列事故原因分析的对错： 悬挑架中悬挑钢梁的固定端长度是悬挑段长度的( )倍。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．1.0',
        'B．1.1',
        'C．1.5',
        'D．1.25',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D．1.25。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，搭设悬挑式外防护脚手架，下方有钢筋绑扎人员在进行钢筋绑扎作业。项目部安全员刘某在现场巡查过程中发现此处存在垂直交叉作业，在联系劳务经理文某后离开，文某在收到通知后未及时处理。外架工何某在作业时扳手掉落至钢筋制作人员徐某砸伤。请判断下列事故原因分析的对错： 外架工的证件是（ ）年有效期，每（ ）年进行复审。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．6 2',
        'B．6 3',
        'B．3 1',
        'B．3 2',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．6     3。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，搭设悬挑式外防护脚手架，下方有钢筋绑扎人员在进行钢筋绑扎作业。项目部安全员刘某在现场巡查过程中发现此处存在垂直交叉作业，在联系劳务经理文某后离开，文某在收到通知后未及时处理。外架工何某在作业时扳手掉落至钢筋制作人员徐某砸伤。请判断下列事故原因分析的对错： 本次事故属于物体打击。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，搭设悬挑式外防护脚手架，下方有钢筋绑扎人员在进行钢筋绑扎作业。项目部安全员刘某在现场巡查过程中发现此处存在垂直交叉作业，在联系劳务经理文某后离开，文某在收到通知后未及时处理。外架工何某在作业时扳手掉落至钢筋制作人员徐某砸伤。请判断下列事故原因分析的对错： 外架作业人员必须佩戴安全带。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，搭设悬挑式外防护脚手架，下方有钢筋绑扎人员在进行钢筋绑扎作业。项目部安全员刘某在现场巡查过程中发现此处存在垂直交叉作业，在联系劳务经理文某后离开，文某在收到通知后未及时处理。外架工何某在作业时扳手掉落至钢筋制作人员徐某砸伤。请判断下列事故原因分析的对错： 安全员刘某在发现垂直交叉作业后，可以通知及相关人员后先行离开。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，A楼浇筑混凝土时因混凝土供应不及时发生堵管，混凝土班组长张某发现后私自联系A、B塔吊进行双塔抬吊拆卸布料机与泵管，在指挥李某确认绑扎好后清除吊装区域作业人员，起勾后因两个塔吊起勾速度不一致，导致泵管弹飞，撞向指挥李某，导致李某重伤。请判断下列事故原因分析是否正确。 使用双机抬吊时，起重量不得超过两机在工况允许起重量的（ ）%，单机起重量的（ ）%。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．75 80',
        'B．80 75',
        'C．75 75',
        'D．80 80',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．75     80。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，A楼浇筑混凝土时因混凝土供应不及时发生堵管，混凝土班组长张某发现后私自联系A、B塔吊进行双塔抬吊拆卸布料机与泵管，在指挥李某确认绑扎好后清除吊装区域作业人员，起勾后因两个塔吊起勾速度不一致，导致泵管弹飞，撞向指挥李某，导致李某重伤。请判断下列事故原因分析是否正确。 超过（ ）级以上大风不得进行起重吊装作业。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．4',
        'B．5',
        'C．6',
        'D．7',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．4。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，A楼浇筑混凝土时因混凝土供应不及时发生堵管，混凝土班组长张某发现后私自联系A、B塔吊进行双塔抬吊拆卸布料机与泵管，在指挥李某确认绑扎好后清除吊装区域作业人员，起勾后因两个塔吊起勾速度不一致，导致泵管弹飞，撞向指挥李某，导致李某重伤。请判断下列事故原因分析是否正确。 吊装区域未有效管控。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A．正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，A楼浇筑混凝土时因混凝土供应不及时发生堵管，混凝土班组长张某发现后私自联系A、B塔吊进行双塔抬吊拆卸布料机与泵管，在指挥李某确认绑扎好后清除吊装区域作业人员，起勾后因两个塔吊起勾速度不一致，导致泵管弹飞，撞向指挥李某，导致李某重伤。请判断下列事故原因分析是否正确。 两个塔吊吊装同一吊装物，吊装信号不一致对吊装安全不影响。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某工地，在主体施工阶段，A楼浇筑混凝土时因混凝土供应不及时发生堵管，混凝土班组长张某发现后私自联系A、B塔吊进行双塔抬吊拆卸布料机与泵管，在指挥李某确认绑扎好后清除吊装区域作业人员，起勾后因两个塔吊起勾速度不一致，导致泵管弹飞，撞向指挥李某，导致李某重伤。请判断下列事故原因分析是否正确。 起重吊装作业是，相关人员可以不进行旁站监督。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B．错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某在建项目建筑面积约2万平方米，项目配备项目负责人、施工员、资料员、材料员共4名管理人员，相关部门在检查过程中发现项目安全管理体系不健全、无施工方案、人员管理混乱、防护设施随意搭设、机械设备等存在重大隐患；按照《建筑施工安全检查评分标准》该项目整体评分结果为不合格项目，要求立即停工限期整改。根据以上内容，回答下列问题。 该项目建筑面积约2万平方米，未按规定配备专职安全员扣10分（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某在建项目建筑面积约2万平方米，项目配备项目负责人、施工员、资料员、材料员共4名管理人员，相关部门在检查过程中发现项目安全管理体系不健全、无施工方案、人员管理混乱、防护设施随意搭设、机械设备等存在重大隐患；按照《建筑施工安全检查评分标准》该项目整体评分结果为不合格项目，要求立即停工限期整改。根据以上内容，回答下列问题。 该项目未按规定配备项目技术人员，施工组织设计、专项方案未编制审批扣5分（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某在建项目建筑面积约2万平方米，项目配备项目负责人、施工员、资料员、材料员共4名管理人员，相关部门在检查过程中发现项目安全管理体系不健全、无施工方案、人员管理混乱、防护设施随意搭设、机械设备等存在重大隐患；按照《建筑施工安全检查评分标准》该项目整体评分结果为不合格项目，要求立即停工限期整改。根据以上内容，回答下列问题。 当施工人员入场时，工程项目部应组织进行以国家安全法律法规、企业安全制度、施工现场安全管理规定及各工种安全技术操作规程为主要内容的三级安全教育培训和考核（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '某在建项目建筑面积约2万平方米，项目配备项目负责人、施工员、资料员、材料员共4名管理人员，相关部门在检查过程中发现项目安全管理体系不健全、无施工方案、人员管理混乱、防护设施随意搭设、机械设备等存在重大隐患；按照《建筑施工安全检查评分标准》该项目整体评分结果为不合格项目，要求立即停工限期整改。根据以上内容，回答下列问题。 该项目塔式起重机未制定安装、拆卸专项方案根据建筑施工安全检查标准扣10分，基础未设置排水措施扣4分，该项在评分中得分86分',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某在建项目建筑面积约2万平方米，项目配备项目负责人、施工员、资料员、材料员共4名管理人员，相关部门在检查过程中发现项目安全管理体系不健全、无施工方案、人员管理混乱、防护设施随意搭设、机械设备等存在重大隐患；按照《建筑施工安全检查评分标准》该项目整体评分结果为不合格项目，要求立即停工限期整改。根据以上内容，回答下列问题。 该项目在检查过程中施工机具检查评分表总得分为79分，在建筑施工安全检查评分汇总表中施工机具应得（ ）分。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、7.9',
        'B、7.5',
        'C、3.95',
        'D、3.96',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C、3.95。',
      explanation: '',
      point: '1',
    },
    {
      question: '某在建项目建筑面积约2万平方米，项目配备项目负责人、施工员、资料员、材料员共4名管理人员，相关部门在检查过程中发现项目安全管理体系不健全、无施工方案、人员管理混乱、防护设施随意搭设、机械设备等存在重大隐患；按照《建筑施工安全检查评分标准》该项目整体评分结果为不合格项目，要求立即停工限期整改。根据以上内容，回答下列问题。 如果该项目基坑工程已施工完成，基坑工程在汇总表中为缺项，其他各分项检查在汇总表中实得分为56分，计算该项目汇总表实得分为（ ）分。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、61.8',
        'B、62.2',
        'C、70.5',
        'D、70.3',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、62.2。',
      explanation: '',
      point: '1',
    },
    {
      question: '某县在建工地在申报XX省级年度建筑施工安全标准化工地申报过程中，依据建筑施工安全检查表评分，该项目总体评定为优良，但未能通过XX省级标准化工地，分析原因如： 该项目在申报标准化工地资料直接报送至XX市住房和城乡建设厅（ ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '某县在建工地在申报XX省级年度建筑施工安全标准化工地申报过程中，依据建筑施工安全检查表评分，该项目总体评定为优良，但未能通过XX省级标准化工地，分析原因如： 该项目申报资料中《建筑施工安全检查评分表》应按（ ）进行评分申报。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、每月',
        'B、每季度',
        'C、每半年',
        'D、施工阶段',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A、每月。',
      explanation: '',
      point: '1',
    },
    {
      question: '某县在建工地在申报XX省级年度建筑施工安全标准化工地申报过程中，依据建筑施工安全检查表评分，该项目总体评定为优良，但未能通过XX省级标准化工地，分析原因如： 省级标准化工地总体评分最低应为（ )分。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、90分以上',
        'B、80分以上',
        'C、75分以上',
        'D、70分以上',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、80分以上。',
      explanation: '',
      point: '1',
    },
    {
      question: '某县在建工地在申报XX省级年度建筑施工安全标准化工地申报过程中，依据建筑施工安全检查表评分，该项目总体评定为优良，但未能通过XX省级标准化工地，分析原因如： 申报省级标准化工地该项目监理总监过程中有变更，变更手续不需要与申报资料一同上报（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B、错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '天地建设工程有限公司在董事长的安排下，由小李负责牵头，对公司职业健康安全管理体系进行修订，在修订过程中，就实现体系长期有效的运行与持续改进，遇到了一些问题，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答以下问题： 公司现有的职业安全管理目标是3年前制定的，小李认为需要结合实际需要对目标进行修订，公司安全目标的确定不应该考虑以下哪些因素。（ ）【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．应该与新的职业健康安全方针保持一致',
        'B．目标应该能量化',
        'C．制定目标的同时，小李应该组织相关部门与人员进行讨论',
        'D．新的目标编写时，首先要考虑现状能实现管理目标',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D．新的目标编写时，首先要考虑现状能实现管理目标。',
      explanation: '',
      point: '1',
    },
    {
      question: '天地建设工程有限公司在董事长的安排下，由小李负责牵头，对公司职业健康安全管理体系进行修订，在修订过程中，就实现体系长期有效的运行与持续改进，遇到了一些问题，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答以下问题： 本次修订时，不应该考虑（）因素。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．外部法律法规的要求变化',
        'B．公司生产工艺、生产组织、生产条件的变化',
        'C．新工艺、新技术的发展',
        'D．公司近年来的荣誉',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D．公司近年来的荣誉。',
      explanation: '',
      point: '1',
    },
    {
      question: '天地建设工程有限公司在董事长的安排下，由小李负责牵头，对公司职业健康安全管理体系进行修订，在修订过程中，就实现体系长期有效的运行与持续改进，遇到了一些问题，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答以下问题： 本次修订前，应该先对体系进行内部评审和管理评审，说法不正确的有（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.需要考虑与体系相关的内外部议题的变化，包括新的需求与期望',
        'B.需要考虑与内外部相关的法律法规的变化',
        'C.需要考虑内外部变化的风险和机遇',
        'D.董事长组织做内部评审，考虑目标和方针的实现程度',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.需要考虑与体系相关的内外部议题的变化，包括新的需求与期望。',
      explanation: '',
      point: '1',
    },
    {
      question: '天地建设工程有限公司在董事长的安排下，由小李负责牵头，对公司职业健康安全管理体系进行修订，在修订过程中，就实现体系长期有效的运行与持续改进，遇到了一些问题，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答以下问题： 为了实现管理体系的持续改进，小李收集了一些文件信息，和管理体系持续改进有密切关系的有（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.危险源识别清单',
        'B.管理体系策划',
        'C.体系的变更和适应的记录',
        'D.与工作人员进行沟通的记录',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D.与工作人员进行沟通的记录。',
      explanation: '',
      point: '1',
    },
    {
      question: '天地建设工程有限公司在董事长的安排下，由小李负责牵头，对公司职业健康安全管理体系进行修订，在修订过程中，就实现体系长期有效的运行与持续改进，遇到了一些问题，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答以下问题： 体系进行更新后，组织应包含哪些必要因素，不需要采取以下哪一项（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.确定评审的规则与方案',
        'B.更新危险源识别与风险评价',
        'C.应该满足法律法规和相关方的管理要求',
        'D.应该组织对相关工作人员进行培训和针对性考核',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C.应该满足法律法规和相关方的管理要求。',
      explanation: '',
      point: '1',
    },
    {
      question: '天地建设工程有限公司在董事长的安排下，由小李负责牵头，对公司职业健康安全管理体系进行修订，在修订过程中，就实现体系长期有效的运行与持续改进，遇到了一些问题，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答以下问题： 集团内部，董事长对管理体系应负责的事项有哪些（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.董事长应该定期对管理体系进行内部评审，并形成文件化信息',
        'B.董事长应定期对管理体系进行管理评审，并形成适应的文件化信息',
        'C.董事长应组织工作人员进行必要的协商',
        'D.董事长应打破工作人员协商和参与之间的障碍和壁垒',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：B.董事长应定期对管理体系进行管理评审，并形成适应的文件化信息。',
      explanation: '',
      point: '1',
    },
    {
      question: '芜湖建筑施工与装饰装修工程有限公司刚刚成立，需要制定企业职业健康安全管理体系，目前正在进行管理体系策划，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答下面的问题。 在进行管理体系策划时，不需要考虑哪些因素，来确定需要应对的风险与机遇。（ ）【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.考虑组织及其所处的环境',
        'B.考虑职业健康安全管理体系范围',
        'C.考虑相关方所提及的要求',
        'D.考虑工程项目特点的要求',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：D.考虑工程项目特点的要求。',
      explanation: '',
      point: '1',
    },
    {
      question: '芜湖建筑施工与装饰装修工程有限公司刚刚成立，需要制定企业职业健康安全管理体系，目前正在进行管理体系策划，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答下面的问题。 在进行管理组织策划时，为了确定与体系及与其有关的风险和机遇，组织不应该（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.考虑危险源',
        'B.考虑职业健康安全风险和其他风险',
        'C.考虑职业健康安全体系的沟通与协调机制的建立',
        'D.考虑所涉及的法律法规的要求',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C.考虑职业健康安全体系的沟通与协调机制的建立。',
      explanation: '',
      point: '1',
    },
    {
      question: '芜湖建筑施工与装饰装修工程有限公司刚刚成立，需要制定企业职业健康安全管理体系，目前正在进行管理体系策划，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答下面的问题。 在策划过程中，组织应结合组织及其过程或职业健康安全管理体系的变更来确定和评价与职业健康安全管理体系预期结果有关的风险和机遇。对于所策划的变更，无论是永久性的还是临时性的，这种评价均应在变更实施前进行。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.正确',
        'B.错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：A.正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '芜湖建筑施工与装饰装修工程有限公司刚刚成立，需要制定企业职业健康安全管理体系，目前正在进行管理体系策划，请根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，回答下面的问题。 在进行措施的策划时，所应考虑的措施中，不正确的是（ ）。【单选】',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A.如何在其职业健康安全管理体系过程中或其他业务过程中融入并实施这些措施',
        'B.如何评价这些措施的有效性',
        'C.在策划措施时，控制的层级和职业健康安全管理体系的输出由最高管理者来确定',
        'D.在策划措施时，组织还应考虑最佳实践、可选技术方案以及财务、运行和经营等要求',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：C.在策划措施时，控制的层级和职业健康安全管理体系的输出由最高管理者来确定。',
      explanation: '',
      point: '1',
    },
  ],
};

export default quiz;
