const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产管理 - 判断题',
  quizSynopsis: '本测验涵盖建设工程安全生产管理的判断题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '150',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '《建设工程施工现场环境与卫生标准》JGJ146-2004，于2014年6月1日废止，同时执行新行业标准《建设工程施工现场环境与卫生标准》JGJ146-2013。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '建设工程施工总承包单位应对施工现场的环境与卫生负总责，分包单位无需服从总承包单位管理。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工人员的教育培训、考核不需要包括环境与卫生等有关内容。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场应实行封闭管理，并应才用硬质围挡。市区主要路段的施工现场围挡高地不应低于1.8m，一般路段围挡高度不应低于2.5m。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《中华人民共和国食品安全法》的有关规定，施工现场保留食品、原料采购台账和原始单据，达到可追溯性要求。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场主要道路应进行硬化，裸露的场地无需管理。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '现场使用预拌砂浆可以不采用封闭、降尘、降噪措施。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场生活区宿舍、休息室必须设置可开启式外窗，床铺可以使用通铺。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业发生的未遂事故，无需按照“四不放过”原则处理。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '依据《职业病分类和目录》（国卫疾控发【2012】48号），白内障不属于职业性眼病。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全生产监督部门是作业场所职业危害预防控制的责任主体。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '化学因素，包括生产性粉尘和化学有毒物质。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '职业病，指企业、事业单位和个体经济组织的劳动者在职业活动中，因接触粉尘、放射性物质和其他有毒有害因素而引起的疾病。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场应设置排水沟及沉淀池，施工用水经沉淀可直接排入市政污水管网。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '食堂应配备必要的排风和冷藏设施，宜设置通风天窗和油烟净化装置，油烟净化装置应定期清洗。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '彩钢板活动房是一种以型钢为骨架，以夹芯板为墙板材料的经济型临建房屋，安装限流器后可以使用大功率电器。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '生活区、办公区的通道、楼梯应设置应急疏散、逃生知识标识和应急照明灯。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '土方和建筑垃圾的清运可选用任意车辆进清运，施工现场出口处设置车辆清洗设备。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '吸烟嗜好者往往能抵御烟尘的危害。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '进入施工现场的车辆严禁鸣笛。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工单位视情况决定是否设立安全生产管理机构，配备专职安全生产管理人员。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '项目经理负责对安全生产进行现场监督检查。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业各管理层及相关职能部门和岗位应根据分解的安全管理目标，配置相应的资源，并应有效管理。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '《施工企业安全生产管理规范》GB50656制定的目的是促进施工企业安全生产管理的标准化、规范化和科学化。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '《施工企业安全生产管理规范》GB50656是对施工企业安全生产管理行为提出的基本要求。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '境外施工企业在我国境内承包工程时可不按照《施工企业安全生产管理规范》GB50656执行。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全生产以及文明施工管理目标应为企业安全生产标准化管理及文明施工基础工作要求的组合。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '工会组织的安全生产职责有对侵害职工在安全生产方面的合法权益的问题进行调查，代表职工与企业进行交涉。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业安全生产教育培训应贯穿于生产经营的全过程。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业要及时为农民工办理参加工伤保险手续。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工单位应当向作业人员提供安全防护用具和安全防护服装，并口头或书面告知危险岗位的操作规程和违章操作的危害。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业宜通过信息化技术，辅助安全生产管理。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业应依据企业的总体发展规划，制订企业年度及中长期安全管理目标。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业可建立安全生产组织体系，明确企业安全生产的决策、管理、实施的机构或岗位。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业安全生产管理制度，应随有关法律法规以及企业生产经营、管理体制的变化，适时更新、修订完善。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '实行施工总承包的建设工程，由建设单位负责上报事故。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工单位对分包（供）单位检查和考核，无需考核分包单位安全生产绩效。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '工程项目部应接受企业各管理层职能部门和岗位的安全生产管理。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业的安全生产管理体系应根据企业安全管理目标、施工生产特点和规模建立完善，并应有效运行。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '隐患是指可能导致职业伤害或疾病、财产损失、工作环境破坏或这些情况组合的根源或状态。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '对危险性较大的拆除工程专项施工方案，应按相关规定组织专家论证。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除工程施工可配备兼职安全生产管理人员，对各项安全技术措施进行监督、检查。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除工程施工应先切断电源、水源和气源，再拆除设备管线设施及主体结构。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '主体结构拆除宜先拆除非承重结构及附属设施，再拆除承重结构。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除工程施工根据实际施工条件,可以进行立体交叉作业，但应做好安全防护措施。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除工程施工中，应对拟拆除物的稳定状态进行监测；当发现事故隐患时，必须停止作业。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '对局部拆除影响结构安全的，应先加固后再拆除。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除地下物，应采取保证基坑边坡及周边建筑物、构筑物的安全与稳定的措施。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除工程作业中，发现不明物体时应及时上报有关部门，施工时应采取相应的应急措施。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '对有限空间拆除施工，应遵循先检测，后通风，再作业。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '当进入有限空间拆除作业时,应采取强制性定期通风措施，保持空气流通。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '当进入有限空间拆除作业时,可采用纯氧通风换气。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '对储存危险品的拟拆除物，拆除前作业人员穿戴好相应劳动防护用品即可进行作业。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '对生产危险品的拟拆除物，拆除施工前应先进行残留物的检测和处理，合格后方可进行施工。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '对拆除工程施工的区域,应设置警戒带进行封闭管理，并设置安全警示标志。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除工程施工前，应进行现场勘查，调查了解地上、地下建筑物及设施和毗邻建筑物、构筑物等分布情况。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除工程施工前，应对影响施工的管线进行迁移或保护，作业前还应进行复查。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除工程所用的施工机具，只要是新购的合格产品，施工前可以不进行进场验收。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '当拟拆除物与毗邻建筑及道路的安全距离不能满足要求时，作业前做详细安全技术交底后可以施工。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '人工拆除施工应从上至下逐层拆除，并应分段进行，不得垂直交叉作业。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '未取得安全生产施工许可证的可以承接施工任务。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业安全生产评价时无在建工程项目，应在企业有在建工程项目时，再次进行跟踪评价。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全技术交底是针对性较强的分部、分项施工安全的作业指导书。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场加强安全检查和隐患排查，发现和消除安全隐患，制定施工组织设计，是控制事故的有效手段。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业应建立制度对所属的施工现场、后方场站、基地等组织定期和不定期的安全检查。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业应建立以企业法人为核心分级负责的各部门及各类人员的安全生产责任制。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '事故没有一定的偶然性，所以抽查项目数考虑有一定的自由度。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业安全生产评价，只需执行《施工企业安全生产评价标准》的规定，可不考虑现行的其他国家标准。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场工作环境是指施工作业场所内的场地、道路、工况、水文、地质、气候等客观条件。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '风险是指某一特定危险情况发生的可能性和后果的组合。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全制度、质量和操作规程的配备是施工企业实施安全生产管理工作的前提。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工组织设计是施工企业项目施工的指导性文件。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '《施工企业安全生产评价标准》适用于对施工企业进行安全生产条件和能力的评价。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '对评价方法仅有初评结论的企业，各地建设行政主管部门可制定相应的管理措施。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业可以不用根据企业规模建立自身安全管理组织体系。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场是不容易发生事故的场所。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '专项施工方案是针对危险性较大的分部、分项工程编制的作业指导书。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场不得使用不符合国家现行标准规范的设备、设施。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工企业安全设施和个人防护用品的合理配置，可以最大限度保护施工现场作业人员，防止工伤事故的发生，减轻事故造成的损失。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '项目安全员不参加事故的调查分析和重大事故的处理。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '基层单位安全总监不参与项目月度安全考评。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '基层单位负责人（经理及书记）必须每年组织两次安全专题会议。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '项目级安全教育培训由项目经理部组织实施。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '由专职安全管理人员结合分项工程施工实际和项目季节性施工方案，向所管理的作业班组进行安全技术交底。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场是容易发生事故的场所，所以企业的每个施工现场必须按照规范标准要去达到合格。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工组织设计和危险性较大的分部分项工程专项施工方案的交底由项目负责人组织，由安全总监向项目经理部的专业工长、技术员等施工管理人员进行方案交底。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '加强对施工危险源的监管和公示、告知，是切实消除安全隐患，杜绝工伤事故发生的有效手段。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '分部分项工程无需编制专项施工方案，安全技术措施是针对分部分项工程施工安全的重要保障。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '提高企业员工安全防范技能，企业必须要建立事故应急救援预案。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全生产责任是搞好安全工作的根本要求。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '进入施工现场的作业人员应逐级进行入场安全教育及岗位能力培训，经考核合格后方可上岗。特种作业人员应符合从业准人条件，持证上岗。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '工程项目的工期根据工程质量、施工安全确定，可以改变工期。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '各种安全防护棚上严禁堆放物料，使用期间棚顶可以上人作业。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '在高处作业时，严禁往上、下抛掷任何物品，拆下的材料，应及时清理运送到指定的地点。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '脚手架使用过程中，严禁任意拆除连墙件。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '拆除作业过程中，当架体的自由端高度大于3步时，应增设临时拉结件。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '附着式升降脚手架应设置安全可靠的具有防倾覆、防坠落和同步升降控制功能的结构装置。升降时应设专人对脚手架作业区域进行监护，每提升一次都应经验收合格后方可作业。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '国家对扣件式钢管脚手架使用的扣件实行生产许可证制度。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '提升架操作平台、料台和吊脚手架应具有足够的承载力和刚度。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '在浇筑混凝土作业时，支撑架下部范围内严禁人员作业，可以行走或停留。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '围挡宜选用彩钢板等轻质材料，围挡外侧为街道或行人通道时，可以不用加固措施。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '爆破拆除工程的预拆除施工中，不应拆除影响结构稳定的构件。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '栏杆下部应设置高度不小于180mm的挡脚板。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '作业时工人将安全带挂在吊篮升降用的钢丝绳上。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场油漆作业与焊接作业可同时在同一区域内进行。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '电梯井口应设置防护门，其高度不应小于15m，防护门底端距地面高度不应大于50mm，并应设置高度不小于180mm的挡脚板。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '电梯井内的施工层上部，可不用设置隔离防护设施。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '密目式安全立网可以代替安全平网使用。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全绳有效长度不应大于2m，有两根安全绳的安全带单根绳的有效长度不应大于1.2m;( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '当采用坡道代替梯道时，应加设间距不大于400mm的防滑条等防滑措施。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场安全管理检查评分表中未按规定配备专职安全员应扣10分。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工现场应建立安全生产责任制、责任目标考核制度。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '危险性较大的分部分项工程未经专家论证不得按照方案组织实施。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '分部分项工程未经安全员进行安全技术交底不得施工。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '安全隐患整改应做到定人、定时间、定措施进行整改。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '施工管理人员、专职安全员每季度应进行安全教育培训和考核。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑材料、构件、料具应按施工现场布局进行码放。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '在《建筑施工安全检查标准》中，表示严格，在正常情况下均应该这样做的；正面词采用 “应”。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '夜间施工前，必须经批准后方可进行施工。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '在《建筑施工安全检查标准》中，表示严格，在正常情况下均应该这样做的；反面词采用 “不应”或“不得”。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工安全检查除应符合《建筑施工安全检查标准》外，尚应符合国家现行有关标准的规定。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '在《建筑施工安全检查标准》中，表示有选择，在一定条件下可以这样做的，采用“可”。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '在《建筑施工安全检查标准》中，高处作业检查评分表中分为保证项目和一般项目。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工安全检查评定，当汇总表得分值70分时，评定为不合格。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '在《建筑施工安全检查标准》中，施工现场配电系统应同时采用两种保护系统给以加分。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: 'JGJ59-2011建筑施工安全检查标准是国家标准。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '在《建筑施工安全检查标准》中，深度在2.5米以内的基层施工采取警戒隔离的符合规范要求，不扣分。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '《建筑施工安全检查标准》检查评定等级分为，优良，合格，不合格。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '建筑施工安全检查评定中当有一分项检查评分表得零分时,评定等级划分为合格。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '当按分项检查评分表评分时，保证项目小计得分不足40分，此分项检查评分表不应得分。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A、正确',
        'B、错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，管理人员具备与其相关的危险源、职业健康安全风险和所确定的措施的能力，属于组织中职业健康安全管理体系的能力。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系中，为了保证组织具备一定的能力，工作人员需要有适当的教育或者培训经历。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，进行职业健康安全管理沟通时，应确保所沟通的职业健康安全信息与职业健康安全管理体系内所形成的信息一致且可靠。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，对职业健康安全体系来说，工作人员的意识是必要的，工作人员必须意识到体系的方针和目标，以及提升职业健康安全年纪绩效的益处、不符合职业健康安全管理体系要求的影响和潜在后果等。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系的有效运行需要资源、意识、能力、沟通、文件化信息的支持。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，危险源包括物理的、化学的、生物的、心理的、机械的五大类。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，危险源辨识有助于组织认识和理解工作场所中的危险源及其对工作人员的危害，以便评价、优先排序并消除危险源或降低职业健康安全风险。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系中的职责和权限可以被分配，但最高管理者仍应为职业健康安全管理体系的运行承担最终责任。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全目标是组织为实现与职业健康安全方针相一致的特定结果而制定的目标。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系中的组织指的是为实现目标，由职责、权限和相互关系构成自身功能的一个人或一组人。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系应该进行绩效评价，主要有合规性评价、内部审核、外部审核。 ( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理目标是由工作人员制定的，一旦制定就不能改变。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，制定职业健康安全目标时，只需要进行绩效评价，让目标可测量即可。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，在职业健康安全管理体系中，目标策划时要充分考虑将实现目标的措施融入业务过程。( )',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，慈善机构也可以应用职业健康安全管理体系指导工作开展。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系中的工作人员指在组织安排下，有偿开展工作的固定人员。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全目标只需要与职业健康安全方针保持一致即可。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，适用于职业健康安全管理体系的组织只能是企事业单位或者企业。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系可以指导有关产品安全与环境影响方面的事项。（ ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：错误。',
      explanation: '',
      point: '1',
    },
    {
      question: 'GB/T 45001-2020 职业健康安全管理体系 要求及使用指南适用于任何规模、类型和活动的组织。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'A．正确',
        'B．错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案是：正确。',
      explanation: '根据相关规范',
      point: '1',
    },
  ],
};

export default quiz;
