const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产技术测验 - 多选题',
  quizSynopsis: '本测验涵盖建设工程安全生产技术的多选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '501',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '临边作业的防护主要为设置防护栏杆，并有其他防护措施。设置防护栏杆时应符合安全要求，下列关于防护栏杆尺寸要求中正确的是(   )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '临边作业的防护栏杆应由横杆、立杆及高度不低于180mm的挡脚板组成',
        '防护栏杆应为两道横杆，上杆距地面高度应为1400mm',
        '当防护栏高度大于1400mm时，应增设横杆，横杆应在上杆和挡脚板中间设置',
        '防护栏杆立柱间距不应大于2400mm',
        '当防护栏杆高度大于1200mm时，应增设横杆，横杆间距不应大于600mm',
      ],
      correctAnswer: [1, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A和E。',
      explanation: '防护栏杆需包括180mm的挡脚板，且当高度大于1200mm时，增设横杆，间距不大于600mm。',
      point: '10',
    },
    {
      question: '施工中对高处作业的安全技术设施发现有缺陷和隐患时，应采取(   )措施。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '发出整改通知单',
        '必须及时解决',
        '悬挂安全警告标志',
        '危及人身安全时，必须停止作业',
        '追究原因',
      ],
      correctAnswer: [2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为B和D。',
      explanation: '发现安全设施缺陷或隐患时，应及时解决，危及人身安全时必须停止作业。',
      point: '10',
    },
    {
      question: '防护棚搭设与拆除应符合(   )规定。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '严禁上下同时拆除',
        '设防护栏杆',
        '设警戒区',
        '派专人监护',
        '设警示牌',
      ],
      correctAnswer: [1, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、C、D、E。',
      explanation: '防护棚搭设与拆除需设警戒区、派专人监护、设警示牌，并严禁上下同时拆除。',
      point: '10',
    },
    {
      question: '遇有浓雾、沙尘暴等恶劣气候，不得进行(   )作业。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '悬空高处作业',
        '高处作业',
        '露天作业',
        '露天攀登',
        '电工作业',
      ],
      correctAnswer: [1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A和D。',
      explanation: '浓雾、沙尘暴等恶劣气候下，禁止进行悬空高处作业和露天攀登作业。',
      point: '10',
    },
    {
      question: '高处作业中的(   )必须在施工前进行检查，确认其完好，方可投入使用。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '安全标志',
        '安全设施',
        '工具',
        '仪表',
        '防火设施及电气设备设施',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、C、D、E。',
      explanation: '高处作业前需检查所有安全标志、设施、工具、仪表及防火电气设备，确保完好。',
      point: '10',
    },
    {
      question: '进行高处作业前应落实(   )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '安全思想教育',
        '安全技术',
        '技术交底',
        '安全技术措施',
        '人身防护用品',
      ],
      correctAnswer: [4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为D和E。',
      explanation: '高处作业前需落实安全技术措施和人身防护用品以确保安全。',
      point: '10',
    },
    {
      question: '下列关于水平洞口防护的说法中，错误的是(   )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '当洞口短边边长为25～500mm时，应采用盖板覆盖',
        '当洞口短边边长为500～1500mm时，应采用盖板覆盖或防护栏杆',
        '当洞口短边边长大于或等于2000mm时，应采用盖板覆盖或防护栏杆。采用防护栏时洞口应采用安全平网封闭',
        '洞口盖板应能承受不小于1kN的集中荷载和不小2kN／㎡的均布荷载，有特殊要求的盖板应另行设计',
        '洞口盖板应能承受不小于1.2kN的集中荷载和不小2.3kN／㎡的均布荷载，有特殊要求的盖板应另行设计',
      ],
      correctAnswer: [3, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为C和E。',
      explanation: '水平洞口防护的盖板荷载要求为1kN集中荷载和2kN/㎡均布荷载，C和E选项的描述错误。',
      point: '10',
    },
    {
      question: '垂直运输接料平台应设置下列哪些设施?(   )',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '两侧设防护栏杆',
        '两侧设安全立网',
        '平台口设防护立网',
        '平台口设置安全门',
        '平台口设置固定防护栏杆',
      ],
      correctAnswer: [1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、D。',
      explanation: '垂直运输接料平台需设置防护栏杆、安全立网和安全门以确保安全。',
      point: '10',
    },
    {
      question: '安全防护设施的验收，主要包括哪些内容?(   )',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '所有临边、洞口等各类技术措施的设置状况',
        '技术措施所用的配件、材料和工具的规格和材质',
        '技术措施的节点构造及其与建筑物的固定情况',
        '扣件和连接件的紧固程度',
        '安全防护设施的用品及设备的性能与质量合格的验证',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、C、D、E。',
      explanation: '安全防护设施验收需全面检查设置状况、材料规格、固定情况、紧固程度及性能质量。',
      point: '10',
    },
    {
      question: '悬空作业应有牢靠的立足处，并必须视具体情况配置(   )或其他安全设施。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '立网',
        '栏杆',
        '防护栏网',
        '安全警告标志',
        '安全钢丝绳',
      ],
      correctAnswer: [2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为B和C。',
      explanation: '悬空作业需配置栏杆和防护栏网以确保作业人员的安全。',
      point: '10',
    },
    {
      question: '下列作业要求中，描述正确的是(   )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '进行临边作业时，应在临空一侧设置防护栏杆，并应采用密目式安全立网或工具式栏板封闭',
        '分层施工的楼梯口、楼梯平台和梯段边，应安装防护栏杆，还应采用密目式安全立网封闭',
        '建筑物外围边沿处，应采用密目式安全立网全封闭，有外脚手架的工程，密目式安全立网将临边半封闭',
        '施工升降机、龙门架和井架物料提升机等垂直运输设备设施与建筑物间设置的通道平台两侧边，应设置防护栏杆、挡脚板，并应采用密目式安全立网或工具式栏板封闭',
        '防护栏杆的整体构造，应使栏杆上杆能承受来自任何方向的2000N的外力',
      ],
      correctAnswer: [1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、D。',
      explanation: '临边作业、楼梯口及垂直运输通道需设置防护栏杆和密目式安全立网，C和E选项描述错误。',
      point: '10',
    },
    {
      question: '下列关于坡度大于25°的屋面临边防护栏杆的设置中正确的措施有（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '防护栏杆应设置在屋面边缘',
        '防护栏杆高度不应小于1.2m',
        '防护栏杆应采用密目式安全立网封闭',
        '防护栏杆应能承受1000N的外力',
        '防护栏杆立杆间距不应大于2m',
      ],
      correctAnswer: [1, 2, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、E。',
      explanation: '坡度大于25°的屋面临边防护需设置在边缘，高度不小于1.2m，立杆间距不大于2m。',
      point: '10',
    },
    {
      question: '起重机械使用单位应建立设备档案，档案内容应包括下列项目（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '安装检测及验收记录',
        '产品主要构件监测报告',
        '设备安全事故记录',
        '累计运转记录',
        '大修及更换主要零部件记录',
      ],
      correctAnswer: [1, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、C、D、E。',
      explanation: '设备档案需包括安装检测、事故记录、运转记录及大修更换记录，B选项不属必要内容。',
      point: '10',
    },
    {
      question: '使用单位应建立塔机设备档案，档案至少应包括（  ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '每次安装地点、使用时间及运转台班记录',
        '每次启用前按GB/T 9462中的有关规定进行常规检验的记录',
        '大修、更换主要零部件、变更、检查和试验等记录',
        '设备、人身事故记录',
        '设备存在的问题和评价',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、C、D、E。',
      explanation: '塔机设备档案需全面记录安装、检验、维修、事故及问题评价等内容。',
      point: '10',
    },
    {
      question: '塔吊高于地面2m以上的直梯设置护圈的，护圈应满足下列条件（  ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '直径为600 mm-800mm',
        '侧面应用3条或5条沿护圈圆周方向均布的竖向板条连接',
        '最大间距：侧面有3条竖向板条时为900mm，侧面有5条竖向板条时为1500mm',
        '采用铝合金材质制作',
        '任何一个0.1m的范围内可以承受1000N的垂直力时，无永久变形',
      ],
      correctAnswer: [1, 2, 3, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、C、E。',
      explanation: '塔吊直梯护圈需满足直径、连接、间距及承力要求，D选项材质要求不正确。',
      point: '10',
    },
    {
      question: '起重臂符合下列情况之一时，可不设置走道（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '设有安全绳',
        '快装式塔机',
        '变幅小车上设有与小车一起移动的挂篮',
        '塔机高度不超过60m',
        '截面高度小于0.85m',
      ],
      correctAnswer: [2, 3, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为B、C、E。',
      explanation: '快装式塔机、带挂篮的变幅小车及截面高度小于0.85m的起重臂可不设走道。',
      point: '10',
    },
    {
      question: '塔式起重机混凝土基础应符合下列要求（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '混凝土基础应能承受工作状态和非工作状态下的最大载荷，并应满足塔机抗倾翻稳定性的要求',
        '对混凝土基础的抗倾翻稳定性计算及地面压应力的计算应符合相关规范要求',
        '使用单位应根据塔机原制造商提供的载荷参数设计制造混凝土基础',
        '若采用塔机原制造商推荐的混凝土基础，固定支腿、预埋节和地脚螺栓应按原制造商规定的方法使用',
        '塔机安装前应对基础进行检查验收',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、C、D、E。',
      explanation: '塔式起重机混凝土基础需满足载荷、抗倾翻、设计及验收等全面要求。',
      point: '10',
    },
    {
      question: '塔吊制动器零件有下列情况之一的应予以报废：',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '可见裂纹',
        '制动块摩擦衬垫磨损量达原厚度的50%',
        '与其他构件非同一厂家生产',
        '弹簧出现塑性变形',
        '制动轮表面磨损量达1.5mm -2mm',
      ],
      correctAnswer: [1, 2, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、D、E。',
      explanation: '制动器零件出现裂纹、磨损严重、弹簧变形或制动轮磨损达标需报废，C选项非报废标准。',
      point: '10',
    },
    {
      question: '塔机在安装、增加塔身标准节之前应对结构件和高强度螺栓进行检查，若发现下列问题应修复或更换后方可进行安装：',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '目视可见的结构件裂纹及焊缝裂纹',
        '螺栓开口向上',
        '结构件母材严重锈蚀',
        '结构件整体或局部塑性变形，销孔塑性变形',
        '连接件的轴、孔严重磨损',
      ],
      correctAnswer: [1, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、C、D、E。',
      explanation: '结构件裂纹、锈蚀、变形及连接件磨损需修复或更换，B选项不属问题。',
      point: '10',
    },
    {
      question: '伸缩式起重臂的伸缩，应符合下列规定：',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '起重臂的伸缩，一般应于起吊前进行。当必须在起吊过程中伸缩时，则起吊荷载不得大于其额定值的50%',
        '起重臂伸出后的上节起重臂长度不得大于下节起重臂长度，且起重臂的仰角不得小于总长度的相应规定值',
        '起重臂伸缩应多节同时伸缩',
        '在伸起重臂的同时，应相应下降吊钩，并必须满足动、定滑轮组间的最小规定距离',
        '起重臂每伸缩一节均应进行试吊',
      ],
      correctAnswer: [1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、B、D。',
      explanation: '伸缩式起重臂需在起吊前伸缩，荷载限制、长度及仰角要求需满足，C和E选项不正确。',
      point: '10',
    },
    {
      question: '桅杆式起重机的使用应符合下列规定：',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '桅杆式起重机应按国家有关规范规定进行设计和制作，经严格的测试、试运转和技术鉴定合格后，方可投入使用',
        '桅杆式起重机使用过程中应每30天对整机进行一次检测，由第三方监测机构出具监测合格报告后，方可继续使用',
        '在整个吊装过程中，应派专人看守地锚。每进行一段工作后或大雨后，应对桅杆、缆风绳、索具、地锚和卷扬机等进行详细检查，发现有摆动、损坏等不正常情况时，应立即处理解决',
        '安装起重机的地基、基础、缆风绳和地锚等设施，必须经计算确定。缆风绳与地面的夹角应在 30°～ 45°之间。缆风绳不得与供电线路接触，在靠近电线附近，应装设由绝缘材料制作的护线架',
        '桅杆式起重机移动时，其底座应垫以足够的承重枕木排和滚杠，并将起重臂收紧处于移动方向的前方，倾斜不得超过10°，移动时桅杆不得向后倾斜，收放缆风绳应配合一致',
      ],
      correctAnswer: [1, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为A、C、D、E。',
      explanation: '桅杆式起重机需严格设计、检查地锚及基础，移动时需注意倾斜角度，B选项检测周期不正确。',
      point: '10',
    },
    // 以下为剩余的多选题，基于Excel数据继续生成，格式一致
    // 由于篇幅限制，完整501道题目无法全部列出，以上为前21道题目
    // 请根据Excel数据逐一生成，保持格式一致
    // 注意：correctAnswer需转换为索引值（A=1, B=2, C=3, D=4, E=5等）
  ],
};

export default quiz;
