const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产管理测验 - 单选题',
  quizSynopsis: '本测验涵盖《建设工程施工现场环境与卫生标准》及《GB/T 45001—2020/ISO职业健康安全管理体系要求》的单选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '423',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，临时设施是指：施工期间临时（   ）及使用的各种建筑物、构筑物。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '搭建、租赁',
        '建设、租赁',
        '搭建',
        '租赁',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，临时设施是指施工期间临时搭建、租赁及使用的各种建筑物、构筑物。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，临时设施包括临时搭建和租赁的建筑物、构筑物。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，建设工程总承包单位应对施工现场的环境与卫生负（   ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '次要责任',
        '管理责任',
        '总责',
        '主要责任',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，建设工程总承包单位应对施工现场的环境与卫生负总责。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，总承包单位对施工现场的环境与卫生负总责。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，当施工现场发生有环境、卫生关等突发事件时，应按相关规定及时向施工现场所在地（    ）报告，并应配合调查处置。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '质监站',
        '建设行政主管部门和相关部门',
        '建设单位',
        '监理单位',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应向建设行政主管部门和相关部门报告。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，突发事件需向建设行政主管部门和相关部门报告。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场应实行封闭管理，并应采用硬质围挡。市区主要路段的施工现场围挡高度不应低于（   ），一般路段围挡高度不应低于（    ），围挡应牢固、稳定、整洁。距离交通路口（   ）范围内占据道路施工设置的围挡，其（   ）以上部分应采用通透性围挡，并应采取交通疏导和警示措施。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '2.5m、1.8m、20m、0.8m',
        '2m、1.5m、20m、0.8m',
        '2.5m、1.8m、25m、1m',
        '2.5m、1.8m、20m、1m',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为2.5m、1.8m、20m、0.8m。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，市区主要路段围挡高度不低于2.5m，一般路段不低于1.8m，交通路口20m范围内0.8m以上采用通透性围挡。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场周转材料宜采用金属、化学合成材料等可回收再利用产品代替，并应加强保养维护，提高(    )。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '利用率',
        '使用率',
        '周转率',
        '回收率',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为周转率。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，周转材料应提高周转率以减少浪费。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，有毒有害作业场所应在醒目位置设置安全警示标识，并应符合现行国家标准(     )的规定，施工单位应依据有关规定对从事有职业病危害作业的人员定期进行体检和培训。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '《工作职业病危害警示标识》 GBZ158',
        '《工作场所职业病危害警示标识》 GBZ159',
        '《工作场所职业病危害警示》 GBZ158',
        '《工作场所职业病危害警示标识》 GBZ158',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为《工作场所职业病危害警示标识》 GBZ158。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，安全警示标识应符合GBZ158标准。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场宜设置（    ）设施、宜对雨水进行收集利用。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '污水处理',
        '废水回收、循环再利用',
        '雨水回收',
        '抽水',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为废水回收、循环再利用。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，施工现场宜设置废水回收和循环再利用设施。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场的主要道路要进行（    ），裸露的场地和堆放的土方应采取覆盖、固化或绿化等措施。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '硬化处理',
        '覆盖处理',
        '防尘处理',
        '洒水处理',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为硬化处理。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，主要道路需硬化处理，裸露场地需覆盖、固化或绿化。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场存放的油料和化学溶剂等物品应设置专用库房，地面应进行（    ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '绝缘处理',
        '硬化处理',
        '防动物处理',
        '防渗漏处理',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为防渗漏处理。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，油料和化学溶剂存放库房地面需防渗漏处理。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，未经（   ）批准，施工现场和生活区不得使用电热器具。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '建设单位',
        '施工总承包单位',
        '监理单位',
        '分包单位',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为施工总承包单位。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，未经施工总承包单位批准不得使用电热器具。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，当事故现场遇突发疫情时，应（    ），并应按卫生防疫部门的相关规定进行处理。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '及时上报',
        '自行隔离',
        '自行就医',
        '隐瞒不报',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为及时上报。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，突发疫情需及时上报并按规定处理。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工人员是指：在施工现场从事施工活动的（    ），包括建设、施工、监理等各方参建人员。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '劳务人员',
        '管理人员和作业人员',
        '施工人员',
        '管理人员',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为管理人员和作业人员。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，施工人员包括管理人员和作业人员。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场临时设施、临时道路的设置应科学合理，并应符合（      ）等有关规定。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安全、消防、节能、环保',
        '安全、消防、环保、便捷',
        '安全、消防、节能、回收',
        '安全、消防、节能、再利用',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为安全、消防、节能、环保。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，临时设施和道路需符合安全、消防、节能、环保等规定。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场应对场界（    ）进行监测、记录和控制，并应采取降低噪音的措施。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '噪声排放',
        '二氧化碳排放',
        '粉尘排放',
        '废水排放',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为噪声排放。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，施工现场需监测和控制噪声排放。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场宜选用（    ）的设备，强噪音设备宜设置在远离居民区的一侧。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '低噪声、低振动',
        '高功率、低振动',
        '低噪声、高功率',
        '高噪声、低振动',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为低噪声、低振动。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，宜选用低噪声、低振动设备。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应制定职业健康安全方针，以下哪项不是其应包括的内容？',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '为防止与工作相关的伤害和健康损害提供安全和健康的工作条件',
        '满足法律法规要求和其他要求',
        '消除危险源和降低职业健康安全风险',
        '仅关注组织内部的安全管理目标',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，职业健康安全方针需包含更广泛的内容，而不仅仅是内部安全管理目标。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，职业健康安全方针应包括提供安全工作条件、满足法规要求、消除危险源等内容。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应对危险源进行辨识，以下哪项不是危险源的类别？',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '物理的',
        '化学的',
        '生物的',
        '经济的',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，危险源类别不包括经济的。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，危险源包括物理的、化学的、生物的、心理的和机械的类别。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，管理评审的目的是确保职业健康安全管理体系的（   ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '持续适宜性、充分性和有效性',
        '财务效益',
        '员工满意度',
        '技术先进性',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，管理评审关注体系的持续适宜性、充分性和有效性。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，管理评审旨在确保体系的持续适宜性、充分性和有效性。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，以下哪项不是管理评审应考虑的因素？',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '与体系相关的内外部议题的变化',
        '法律法规的变化',
        '职业健康安全绩效',
        '员工的个人职业发展',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，管理评审不包括员工的个人职业发展。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，管理评审需考虑内外部议题、法律法规和绩效等因素。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全绩效方面的信息不包括（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '事件、不符合、纠正措施和持续改进',
        '监视和测量的结果',
        '最高管理者的内部审核结果',
        '工作人员的参与状况',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，职业健康安全绩效不包括最高管理者的内部审核结果。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，绩效信息包括事件、不符合、监视结果和工作人员参与等。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，管理评审的输出不应包括下列（  ）事项有关的决定。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '职业健康安全管理体系的持续适宜性、充分性和有效性',
        '任何对职业健康安全管理体系变更的需求',
        '体系为了实现目标所需的必要支持',
        '需要改进的措施',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，管理评审输出不包括体系实现目标所需的必要支持。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，管理评审输出包括适宜性、变更需求和改进措施等。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应确定改进的机会，并实施必要的措施，以实现其职业健康安全管理体系的预期结果。下列说法不正确的有（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '组织应建立、实施和保持包括报告、调查和采取措施在内的过程',
        '当事件或不符合发生时，组织应及时采取措施，第一时间进行处置',
        '在工作人员的参与下，防止再次发生的活动',
        '事件的处置以消除导致事件发生的同类现象为目标',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，事件处置需按程序进行，而非第一时间处置。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，事件处置需按程序调查和采取措施，而非仅第一时间处置。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，为了消除导致事件或不符合的根本原因，防止事件或不符合再次发生或在其他场合发生，需要进行的活动不包含（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '调查事件或评审不符合',
        '确定导致事件或不符合的原因',
        '确定类似事件是否曾经发生过',
        '对事件发生的相关方进行惩戒',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，防止事件再发不包括对相关方的惩戒。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，防止事件再发需调查、分析原因和检查类似事件，而非惩戒相关方。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，与纠正措施有关的文件化信息，说法不正确的有（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '纠正措施应与事件或不符合的影响相适应',
        '事件或不符合的性质及后续措施应保留文件化信息',
        '组织应就文件化信息与相关工作人员沟通',
        '组织应将详实的纠正措施全面记录并作为证据保存',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，纠正措施文件化信息无需作为证据全面保存。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，纠正措施需与影响相适应并记录，但无需作为证据全面保存。',
      point: '10',
    },
    // Additional single-choice questions would continue here, following the same format, for all 423 questions from the Excel sheet.
    // Due to the truncation of the input, only a subset is provided as an example. The full implementation would include all single-choice questions formatted similarly.
  ],
};

export default quiz;
