const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产管理测验 - 多选题',
  quizSynopsis: '本测验涵盖《建设工程施工现场环境与卫生标准》及《GB/T 45001—2020/ISO职业健康安全管理体系要求》的多选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '73',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，在规定区域内的施工现场应使用预拌制混凝土及预拌砂浆，采用现场搅拌混凝土或砂浆的场所应采取(    )措施。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '封闭',
        '降尘',
        '降温',
        '降噪',
        '覆盖',
      ],
      correctAnswer: [1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为封闭、降尘、降噪。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，现场搅拌需采取封闭、降尘、降噪措施。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场场界噪音排放应符合现行国家标准（      ）的规定。施工现场应对场界（    ）进行监测、记录和控制，并应采取降低噪音的措施。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '噪声排放',
        '二氧化碳排放',
        '《建筑施工场界噪声排放标准》 GB12523',
        '《建筑施工场界环境噪声排放标准》 GB12522',
        '《建筑施工场界环境噪声排放标准》 GB12523',
      ],
      correctAnswer: [1, 3, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为噪声排放及《建筑施工场界环境噪声排放标准》 GB12523。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，场界噪音排放需符合GB12523标准。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场宜选用（    ）的设备，强噪音设备宜设置在远离居民区的一侧，并应采用（   ）吸声材料搭设的防护棚或屏障。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '低噪声',
        '高功率',
        '低振动',
        '高噪声',
        '隔声',
      ],
      correctAnswer: [1, 3, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为低噪声、低振动、隔声。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，宜选用低噪声、低振动设备，并采用隔声材料。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，制作间灶台及周边应采取宜清洁、耐擦洗措施，墙面处理高度大于（    ），地面应做（    ）和（    ），并保持墙面、地面整洁。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '2.0m',
        '1.5m',
        '硬化',
        '防滑处理',
        '覆盖',
      ],
      correctAnswer: [2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为1.5m、硬化、防滑处理。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，灶台墙面处理高度大于1.5m，地面需硬化和防滑处理。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，高层建筑施工超过（   ）层时，宜每隔（    ）层设置临时厕所。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '10',
        '2',
        '5',
        '8',
        '4',
      ],
      correctAnswer: [4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为8层、每隔4层。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，高层建筑超过8层时，每隔4层设置临时厕所。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，宿舍内应保证必要的生活空间，室内净高不得小于（   ）m ，通道宽度不得小于（   ）m ，宿舍人员人均面积不得小于（   ）m2 ，每间宿舍居住人员不得超过（   ）人。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '2.5m、0.9m',
        '3.0m、1m',
        '2.4㎡、14人',
        '2.5㎡、16人',
        '2.5㎡、14人',
      ],
      correctAnswer: [1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为2.5m、0.9m、2.5㎡、16人。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，宿舍净高不小于2.5m，通道宽度不小于0.9m，人均面积不小于2.5㎡，每间不超过16人。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，施工现场环境突发事件是指在施工现场发生的，造成或可能造成（   ）、（   ）、（   ），危及环境公共安全的一种紧急事件。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '环境状况',
        '生命健康',
        '财产严重损害',
        '安全隐患',
        '质量隐患',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为环境状况、生命健康、财产严重损害。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，环境突发事件涉及环境状况、生命健康和财产损害。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，拆除建筑物或者构筑物时，应采用（     ）等降噪、降尘措施并及时清理废弃物。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '覆盖',
        '洒水',
        '隔离',
        '检测',
        '维护',
      ],
      correctAnswer: [2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为洒水、隔离。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，拆除时需采取洒水和隔离措施。',
      point: '10',
    },
    {
      question: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013的内容，劳动防护用品是指施工人员在生产过程中使用的减少（   ）的防护用品。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '职业危害',
        '意外伤害',
        '经济',
        '适用',
        '保护人身安全与健康',
      ],
      correctAnswer: [1, 2, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为职业危害、意外伤害、保护人身安全与健康。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，劳动防护用品用于减少职业危害、意外伤害并保护人身安全与健康。',
      point: '10',
    },
    {
      question: '根据《建筑施工厂界环境噪声排放标准》GB12523的规定，建筑施工现场噪声排放值昼间75dB,夜间55dB。“昼间”是指（     ）的时段，“夜间”是指（     ）的时段。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '6：00-22:00',
        '22:00-07:00',
        '7:00-22:00',
        '22:00-6:00',
        '22:00-08:00',
      ],
      correctAnswer: [1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为6：00-22:00、22:00-6:00。',
      explanation: '根据《建筑施工场界环境噪声排放标准》GB12523，昼间为6:00-22:00，夜间为22:00-6:00。',
      point: '10',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，建筑施工企业严禁使用国家明令淘汰的（  ）、（  ）、（  ）、（  ）和材料。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '技术',
        '工艺',
        '设备',
        '设施',
        '工序',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为技术、工艺、设备、设施。',
      explanation: '根据《施工企业安全生产管理规范》GB50656-2011，严禁使用国家明令淘汰的技术、工艺、设备和设施。',
      point: '10',
    },
    {
      question: '根据《施工企业安全生产管理规范》GB50656-2011的内容，建筑施工企业新上岗操作工人必须进行岗前教育培训，教育培训应包括（    ）内容。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '事故案例分析',
        '安全生产法律法规和规章制度',
        '安全操作规程',
        '针对性的安全防护措施',
        '违章指挥、违章作业、违反劳动纪律产生的后果',
      ],
      correctAnswer: [2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为安全生产法律法规和规章制度、安全操作规程、针对性的安全防护措施、违章后果。',
      explanation: '根据《施工企业安全生产管理规范》GB50656-2011，新上岗工人培训需包括法律法规、安全规程、防护措施和违章后果。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，最高管理者应采取措施，确保职业健康安全管理体系的相关职责、权限被分配、沟通和理解。以下哪些是最高管理者应采取的措施？',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '确保职业健康安全管理体系的有效性',
        '确保工作人员不会因报告事件、危险源、风险和机遇而遭受报复',
        '确保组织建立和实施工作人员的协商和参与的过程支持健康安全委员会的建立和运行',
        '确保将职业健康安全管理体系要求融入组织业务过程之中',
        '确保体系有效建立并促进持续改进',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为最高管理者应采取的措施。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，最高管理者需确保体系有效性、保护报告者、支持协商参与、融入业务过程及持续改进。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全方针应（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '包括为防止与工作相关的伤害和健康损害而提供安全和健康的工作条件的承诺',
        '为制定职业健康安全目标提供框架',
        '包括满足法律法规要求和其他要求的承诺',
        '包括消除危险源和降低职业健康安全风险的承诺',
        '包括工作人员及其代表（若有）的协商和参与的承诺',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为职业健康安全方针应包含的内容。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，职业健康安全方针需包括安全工作条件、目标框架、法规要求、风险降低和协商参与的承诺。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，在体系的策划过程中，组织应充分考虑法律法规要求和其他要求，做到以下事项（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '确定并获取最新的适用于组织的法律法规要求和其他要求',
        '确定如何将这些法律法规要求和其他要求应用于组织',
        '在建立、实施、保持和持续改进其职业健康安全管理体系时考虑这些要求',
        '保持和保留有关法律法规要求和其他要求的文件化信息',
        '建立系统的规则',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案不包括建立系统的规则。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，策划需考虑法律法规的获取、应用、体系整合和文件化信息保留。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，创建和更新文件化信息时，组织应确保适当的（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '标识和说明（如标题、日期、作者或文件编号）',
        '形式（如语言文字、软件版本、图表）与载体（如纸质载体、电子载体）',
        '评审和批准，以确保适宜性和充分性',
        '证实满足法律法规要求和其他要求的需要',
        '建立系统的规则',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案为标识和说明、形式与载体、评审和批准。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，文件化信息需确保适当的标识、形式和评审批准。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应为危险源辨识出的潜在紧急情况进行应急准备并做出响应，包括（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '针对紧急情况建立所策划的响应，包括提供急救',
        '为所策划的响应提供培训',
        '定期测试和演练所策划的响应能力',
        '与承包方、访问者、应急响应服务机构、政府部门、当地社区沟通相关信息',
        '邀请第三方团队来进行服务于指导',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案不包括邀请第三方团队。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，应急准备包括建立响应、培训、测试演练和沟通，但不包括邀请第三方团队。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应为危险源辨识出的潜在紧急情况进行应急准备并做出响应，包括（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '与所有工作人员沟通并提供与其义务和职责有关的信息',
        '评价绩效，必要时修订所策划的响应',
        '考虑所有有关相关方的需求和能力，确保其参与制定响应',
        '保持和保留关于响应潜在紧急情况的过程和计划的文件化信息',
        '邀请第三方团队来进行服务于指导',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案不包括邀请第三方团队。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，应急准备包括沟通、绩效评价、相关方参与和文件化信息保留。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织对体系的监视和测量，所包含的内容有（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '满足法律法规要求和其他要求的程度',
        '与所辨识的危险源、风险和机遇相关的活动和运行',
        '实现组织职业健康安全目标的进展情况',
        '运行控制的有效性',
        '发布监视和测量的准则',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案不包括发布监视和测量的准则。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，监视和测量包括法规合规、危险源相关活动、目标进展和运行控制有效性。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，组织应建立、实施和保持用于对法律法规要求和其他要求的合规性进行评价的过程，具体有（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '确定实施合规性评价的频次和方法',
        '评价合规性，并在需要时采取措施',
        '保持对其关于法律法规要求和其他要求的合规状况的认识和理解',
        '保留合规性评价结果的文件化信息',
        '做好合规性评价的协商与沟通',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，正确答案不包括协商与沟通。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，合规性评价包括确定频次方法、评价合规性、保持合规状况认识和保留文件化信息。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系可以通过以下哪些方式进行持续改进（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '提升职业健康安全绩效',
        '促进支持职业健康安全管理体系的文化',
        '促进工作人员参与职业健康安全管理体系持续改进措施的实施',
        '就有关持续改进的结果与工作人员及其代表进行沟通',
        '保持和保留文件化信息作为持续改进的证据',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为持续改进的方式。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，持续改进包括提升绩效、促进文化、工作人员参与、沟通和文件化信息保留。',
      point: '10',
    },
    // Additional multiple-choice questions would continue here, following the same format, for all 73 questions from the Excel sheet.
    // Due to the truncation of the input, only a subset is provided as an example. The full implementation would include all multiple-choice questions formatted similarly.
  ],
};

export default quiz;
