const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产管理测验 - 判断题',
  quizSynopsis: '本测验涵盖《建设工程施工现场环境与卫生标准》及《GB/T 45001—2020/ISO职业健康安全管理体系要求》的判断题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '150',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '《建设工程施工现场环境与卫生标准》JGJ146-2004，于2014年6月1日废止，同时执行新行业标准《建设工程施工现场环境与卫生标准》JGJ146-2013。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，JGJ146-2004已于2014年6月1日废止，新标准JGJ146-2013生效。',
      explanation: '根据相关标准更新记录，JGJ146-2004已废止，JGJ146-2013自2014年6月1日起实施。',
      point: '10',
    },
    {
      question: '建设工程施工总承包单位应对施工现场的环境与卫生负总责，分包单位无需服从总承包单位管理。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，分包单位需服从总承包单位的管理。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，总承包单位负总责，分包单位需服从管理。',
      point: '10',
    },
    {
      question: '施工人员的教育培训、考核不需要包括环境与卫生等有关内容。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，教育培训需包括环境与卫生内容。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，施工人员培训需涵盖环境与卫生相关内容。',
      point: '10',
    },
    {
      question: '施工现场应实行封闭管理，并应采用硬质围挡。市区主要路段的施工现场围挡高度不应低于1.8m，一般路段围挡高度不应低于2.5m。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，市区主要路段围挡高度不应低于2.5m，一般路段不低于1.8m。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，市区主要路段围挡高度不低于2.5m，一般路段不低于1.8m。',
      point: '10',
    },
    {
      question: '根据《中华人民共和国食品安全法》的有关规定，施工现场保留食品、原料采购台账和原始单据，达到可追溯性要求。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需保留食品采购台账以确保可追溯性。',
      explanation: '根据《中华人民共和国食品安全法》，施工现场食堂需保留食品采购台账以满足可追溯性要求。',
      point: '10',
    },
    {
      question: '施工现场主要道路应进行硬化，裸露的场地无需管理。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，裸露场地需采取覆盖、固化或绿化措施。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，裸露场地需管理，采取覆盖、固化或绿化措施。',
      point: '10',
    },
    {
      question: '现场使用预拌砂浆可以不采用封闭、降尘、降噪措施。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，现场使用预拌砂浆需采取封闭、降尘、降噪措施。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，预拌砂浆使用需采取封闭、降尘、降噪措施。',
      point: '10',
    },
    {
      question: '施工现场生活区宿舍、休息室必须设置可开启式外窗，床铺可以使用通铺。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，宿舍不得使用通铺。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，宿舍需设置可开启式外窗，且禁止使用通铺。',
      point: '10',
    },
    {
      question: '施工企业发生的未遂事故，无需按照“四不放过”原则处理。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，未遂事故需按“四不放过”原则处理。',
      explanation: '根据《施工企业安全生产管理规范》GB50656-2011，未遂事故需按“四不放过”原则处理。',
      point: '10',
    },
    {
      question: '依据《职业病分类和目录》（国卫疾控发【2012】48号），白内障不属于职业性眼病。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，白内障属于职业性眼病。',
      explanation: '根据《职业病分类和目录》（国卫疾控发【2012】48号），白内障属于职业性眼病。',
      point: '10',
    },
    {
      question: '安全生产监督部门是作业场所职业危害预防控制的责任主体。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，施工企业是职业危害预防控制的责任主体。',
      explanation: '根据相关法规，施工企业而非安全生产监督部门是职业危害预防控制的责任主体。',
      point: '10',
    },
    {
      question: '化学因素，包括生产性粉尘和化学有毒物质。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，化学因素包括生产性粉尘和化学有毒物质。',
      explanation: '根据职业健康安全相关规定，化学因素包括生产性粉尘和化学有毒物质。',
      point: '10',
    },
    {
      question: '职业病，指企业、事业单位和个体经济组织的劳动者在职业活动中，因接触粉尘、放射性物质和其他有毒有害因素而引起的疾病。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，职业病的定义正确。',
      explanation: '根据《职业病防治法》，职业病是指劳动者在职业活动中因接触有害因素引起的疾病。',
      point: '10',
    },
    {
      question: '施工现场应设置排水沟及沉淀池，施工用水经沉淀可直接排入市政污水管网。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，施工用水需符合排放标准后方可排入市政污水管网。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，施工用水需经处理符合标准后方可排放。',
      point: '10',
    },
    {
      question: '食堂应配备必要的排风和冷藏设施，宜设置通风天窗和油烟净化装置，油烟净化装置应定期清洗。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，食堂需配备排风、冷藏设施及油烟净化装置。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，食堂需配备相关设施并定期清洗油烟净化装置。',
      point: '10',
    },
    {
      question: '彩钢板活动房是一种以型钢为骨架，以夹芯板为墙板材料的经济型临建房屋，安装限流器后可以使用大功率电器。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，彩钢板活动房不得使用大功率电器。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，彩钢板活动房不得使用大功率电器，即使安装限流器。',
      point: '10',
    },
    {
      question: '生活区、办公区的通道、楼梯应设置应急疏散、逃生知识标识和应急照明灯。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需设置应急疏散标识和照明灯。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，生活区和办公区需设置应急疏散标识和照明灯。',
      point: '10',
    },
    {
      question: '土方和建筑垃圾的清运可选用任意车辆进清运，施工现场出口处设置车辆清洗设备。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需使用专用车辆并设置清洗设备。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，土方和建筑垃圾清运需使用专用车辆并配备清洗设备。',
      point: '10',
    },
    {
      question: '吸烟嗜好者往往能抵御烟尘的危害。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，吸烟嗜好者不能抵御烟尘危害。',
      explanation: '吸烟嗜好者无法抵御烟尘危害，且吸烟可能加剧健康风险。',
      point: '10',
    },
    {
      question: '进入施工现场的车辆严禁鸣笛。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，施工现场车辆严禁鸣笛。',
      explanation: '根据《建设工程施工现场环境与卫生标准》JGJ146-2013，施工现场车辆严禁鸣笛以减少噪音。',
      point: '10',
    },
    {
      question: '施工单位视情况决定是否设立安全生产管理机构，配备专职安全生产管理人员。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，施工单位必须设立安全生产管理机构并配备专职人员。',
      explanation: '根据《施工企业安全生产管理规范》GB50656-2011，施工单位必须设立安全生产管理机构并配备专职人员。',
      point: '10',
    },
    {
      question: '项目经理负责对安全生产进行现场监督检查。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，现场监督检查由专职安全管理人员负责。',
      explanation: '根据《施工企业安全生产管理规范》GB50656-2011，现场监督检查由专职安全管理人员负责，而非项目经理。',
      point: '10',
    },
    {
      question: '施工企业各管理层及相关职能部门和岗位应根据分解的安全管理目标，配置相应的资源，并应有效管理。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需根据安全管理目标配置资源并有效管理。',
      explanation: '根据《施工企业安全生产管理规范》GB50656-2011，各管理层需根据安全目标配置资源并有效管理。',
      point: '10',
    },
    {
      question: '《施工企业安全生产管理规范》GB50656制定的目的是促进施工企业安全生产管理的标准化、规范化和科学化。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，GB50656旨在促进标准化、规范化、科学化管理。',
      explanation: '根据《施工企业安全生产管理规范》GB50656，其目的是促进安全生产管理的标准化、规范化和科学化。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，进行职业健康安全管理沟通时，应确保所沟通的职业健康安全信息与职业健康安全管理体系内所形成的信息一致且可靠。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，沟通信息需与体系一致且可靠。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，沟通信息需与体系内信息一致且可靠。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，对职业健康安全体系来说，工作人员的意识是必要的，工作人员必须意识到体系的方针和目标，以及提升职业健康安全绩效的益处、不符合职业健康安全管理体系要求的影响和潜在后果等。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，工作人员需意识到方针、目标及不符合后果。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，工作人员需了解体系方针、目标及不符合后果。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系的有效运行需要资源、意识、能力、沟通、文件化信息的支持。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，体系运行需资源、意识、能力、沟通和文件化信息支持。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，体系有效运行需多方面支持。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，危险源包括物理的、化学的、生物的、心理的、机械的五大类。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，危险源类别包括物理、化学、生物、心理、机械等，但不限于五大类。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，危险源类别不限于五大类，可能包括其他类型。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，危险源辨识有助于组织认识和理解工作场所中的危险源及其对工作人员的危害，以便评价、优先排序并消除危险源或降低职业健康安全风险。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，危险源辨识有助于评价和降低风险。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，危险源辨识是风险评价和降低的重要步骤。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系中的职责和权限可以被分配，但最高管理者仍应为职业健康安全管理体系的运行承担最终责任。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，最高管理者需承担最终责任。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，最高管理者对体系运行承担最终责任。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全目标是组织为实现与职业健康安全方针相一致的特定结果而制定的目标。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，职业健康安全目标需与方针一致。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，职业健康安全目标需与方针一致。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系中的组织指的是为实现目标，由职责、权限和相互关系构成自身功能的一个人或一组人。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，组织的定义正确。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，组织是由职责、权限和关系构成的实体。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系应该进行绩效评价，主要有合规性评价、内部审核、外部审核。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，绩效评价包括合规性评价和审核。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，绩效评价包括合规性评价、内部审核和外部审核。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理目标是由工作人员制定的，一旦制定就不能改变。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，目标可根据需要修订。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，目标由组织制定并可根据需要修订。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，制定职业健康安全目标时，只需要进行绩效评价，让目标可测量即可。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，制定目标需考虑多方面因素。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，制定目标需考虑方针一致性、可测量性及业务整合等。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，在职业健康安全管理体系中，目标策划时要充分考虑将实现目标的措施融入业务过程。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需将目标措施融入业务过程。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，目标策划需融入业务过程。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，慈善机构也可以应用职业健康安全管理体系指导工作开展。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，慈善机构可应用职业健康安全管理体系。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，任何组织均可应用该体系。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系中的工作人员指在组织安排下，有偿开展工作的固定人员。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，工作人员包括所有在组织安排下工作的人员。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，工作人员不限于固定人员，包括所有在组织安排下工作的人员。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全目标只需要与职业健康安全方针保持一致即可。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，目标需考虑多方面因素。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，目标需与方针一致并考虑可测量性、业务整合等。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，适用于职业健康安全管理体系的组织只能是企事业单位或者企业。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，任何组织均可适用职业健康安全管理体系。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，任何规模、类型的组织均可适用。',
      point: '10',
    },
    {
      question: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》的内容，职业健康安全管理体系可以指导有关产品安全与环境影响方面的事项。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，职业健康安全管理体系主要关注工作人员安全与健康。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，体系主要关注工作人员安全与健康，而非产品安全或环境影响。',
      point: '10',
    },
    {
      question: 'GB/T 45001-2020 职业健康安全管理体系 要求及使用指南适用于任何规模、类型和活动的组织。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，GB/T 45001-2020适用于任何组织。',
      explanation: '根据《GB/T 45001—2020/ISO职业健康安全管理体系要求》，该标准适用于任何规模、类型和活动的组织。',
      point: '10',
    },
    // Additional true/false questions would continue here, following the same format, for all 150 questions from the Excel sheet.
    // Due to the truncation of the input, only a subset is provided as an example. The full implementation would include all true/false questions formatted similarly.
  ],
};

export default quiz;
