const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产法律法规单选题测验',
  quizSynopsis: '本测验涵盖建设工程安全生产法律法规的单选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '576',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '下列建筑施工人员属于特种作业的是（   ）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '油漆工',
        '高处作业吊篮安装拆卸工',
        '混凝土工',
        '钢筋工',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，高处作业吊篮安装拆卸工属于特种作业。',
      explanation: '根据《建筑施工特种作业人员管理规定》，高处作业吊篮安装拆卸工需取得特种作业资格证书。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员必须经（   ）考核合格，取得建筑施工特种作业人员操作资格证书，方可上岗从事相应作业。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '省级人民政府',
        '当地人民政府',
        '建设主管部门',
        '行政主管部门',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，建设主管部门负责特种作业人员的考核。',
      explanation: '根据相关法规，建设主管部门负责特种作业人员的资格考核和发证。',
      point: '10',
    },
    {
      question: '下列条件中（   ）是申请从事建筑施工特种作业的人员应当具备的基本条件之一。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '年满18周岁且符合相关工种规定的年龄要求',
        '具有丰富特种作业工作经验',
        '经企业年度安全生产教育培训合格',
        '必须具有高中及以上学历',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，年龄要求是特种作业人员的基本条件之一。',
      explanation: '根据规定，申请特种作业需年满18周岁并符合工种年龄要求。',
      point: '10',
    },
    {
      question: '特种作业考核发证机关应当自收到申请人提交的申请材料之日起（   ）个工作日内依法作出受理或者不予受理决定。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '10',
        '7',
        '3',
        '5',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应当在5个工作日内作出决定。',
      explanation: '根据《建筑施工特种作业人员管理规定》，考核发证机关需在5个工作日内作出受理决定。',
      point: '10',
    },
    {
      question: '特种作业考核发证机关应当自考核结束之日起（  ）个工作日内公布考核成绩。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '10',
        '5',
        '7',
        '3',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应当在10个工作日内公布成绩。',
      explanation: '根据规定，考核成绩需在考核结束后10个工作日内公布。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员应当参加年度安全教育培训或者继续教育，每年不得少于(   )学时。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '36',
        '24',
        '20',
        '12',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，每年培训不得少于24学时。',
      explanation: '根据相关法规，特种作业人员需每年接受不少于24学时的安全教育培训。',
      point: '10',
    },
    {
      question: '特种作业人员资格证书有效期为（   ）年。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '2',
        '3',
        '6',
        '1',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，资格证书有效期为6年。',
      explanation: '根据规定，特种作业人员资格证书有效期为6年。',
      point: '10',
    },
    {
      question: '特种作业人员资格证书有效期满需要延期的，建筑施工特种作业人员应当于期满前（   ）个月内向原考核发证机关申请办理延期复核手续。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '2',
        '3',
        '1',
        '6',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需在期满前3个月申请延期。',
      explanation: '根据《建筑施工特种作业人员管理规定》，延期复核需在证书到期前3个月申请。',
      point: '10',
    },
    {
      question: '特种作业人员资格证书延期复核合格的，资格证书有效期延期（   ）年。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '3',
        '1',
        '6',
        '2',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，延期后有效期为6年。',
      explanation: '复核合格的特种作业资格证书有效期延长6年。',
      point: '10',
    },
    {
      question: '县级以上地方人民政府建设主管部门应当监督检查建设施工特种作业人员从业活动，查处违章作业行为应（）',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '记录在档',
        '书信通知',
        '网络通知',
        '电话通知',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，违章行为需记录在档。',
      explanation: '根据法规，违章作业行为需记录存档以便监督管理。',
      point: '10',
    },
    {
      question: '建筑施工企业应当依法设置安全生产管理机构，在企业（     ）的领导下开展本企业的安全生产管理工作。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安全部部长',
        '监理工程师',
        '主要负责人',
        '技术负责人',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，由主要负责人领导安全生产管理。',
      explanation: '根据《安全生产法》，企业主要负责人对安全生产工作全面负责。',
      point: '10',
    },
    {
      question: '分包单位配备项目专职安全生产管理人员应当满足一定的要求，下列论述不正确的是（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '专业承包单位应当配置至少2人，并根据所承担的分部分项工程的工程量和施工危险程度增加',
        '劳务分包单位施工人员在50人以下的，应当配备1名专职安全生产管理人员',
        '劳务分包单位施工人员在50～200人的，应当配备2名专职安全生产管理人员',
        '劳务分包单位施工人员在200人以上的，应当配备3名专职安全生产管理人员',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，专业承包单位应至少配置1人。',
      explanation: '根据相关规定，专业承包单位应至少配备1名专职安全生产管理人员，而非2人。',
      point: '10',
    },
    {
      question: '企业负责人带班检查是指由建筑施工企业（  ）带队实施对工程项目质量安全生产状况及项目负责人带班生产情况的检查。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安全部部长',
        '项目负责人',
        '负责人',
        '专职安全生产管理人员',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，由企业负责人带队检查。',
      explanation: '企业负责人带班检查需由企业负责人亲自带队。',
      point: '10',
    },
    {
      question: '建筑施工企业（    ）是落实企业负责人及项目负责人施工现场带班制度的第一责任人，对落实带班制度全面负责。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '主管质量安全和生产工作的副总经理',
        '总工程师',
        '总经理',
        '法定代表人',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，法定代表人是第一责任人。',
      explanation: '根据法规，法定代表人对落实带班制度负首要责任。',
      point: '10',
    },
    {
      question: '建筑施工企业负责人要定期带班检查，每月检查时间不少于其工作日的（   ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '20%',
        '30%',
        '35%',
        '25%',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查时间不少于工作日的25%。',
      explanation: '根据规定，企业负责人带班检查时间需占工作日的25%以上。',
      point: '10',
    },
    {
      question: '项目负责人是工程项目质量安全管理的（   ），应对工程项目落实带班制度负责。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '最终责任人',
        '直接责任人',
        '第一责任人',
        '以上答案都不对',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，项目负责人是第一责任人。',
      explanation: '项目负责人是工程项目质量安全管理的第一责任人。',
      point: '10',
    },
    {
      question: '项目负责人每月带班生产时间不得少于本月施工时间的（   ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '60%',
        '80%',
        '50%',
        '70%',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，带班时间不得少于施工时间的80%。',
      explanation: '根据规定，项目负责人每月带班生产时间需占施工时间的80%以上。',
      point: '10',
    },
    {
      question: '从业人员发现直接危及人身安全的紧急情况时，（   ）撤离作业场所。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '立即',
        '向项目管理人员报告后',
        '采取可能的应急措施后',
        '停止作业或者在采取可能的应急措施后',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应先停止作业或采取应急措施后撤离。',
      explanation: '根据《安全生产法》，从业人员在紧急情况下可停止作业并撤离。',
      point: '10',
    },
    {
      question: '应急管理部门和其他负有安全生产监督管理职责的部门根据（   ），依法开展行政执法工作，对生产经营单位执行有关安全生产法律、法规和国家标准、行业标准或者地方标准的情况进行监督检查。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '行业规范',
        '国家法律法规',
        '安全生产权力清单和责任清单',
        '应急管理部门和其他负有安全生产监督管理职责的部门规章制度',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，依据安全生产权力和责任清单。',
      explanation: '监督检查需依据安全生产权力清单和责任清单进行。',
      point: '10',
    },
    {
      question: '发生重大以上生产安全事故的，应当由事故发生地（   ）统一组织指挥现场处置。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '县级人民政府',
        '设区的市级人民政府',
        '省级人民政府',
        '工程所在地行业主管部门',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，由设区的市级人民政府指挥。',
      explanation: '重大以上事故由设区的市级人民政府组织指挥。',
      point: '10',
    },
    {
      question: '生产经营单位应当具备安全生产条件所必需的资金投入，未提供安全生产所必需的资金投入，致使生产经营单位不具备安全生产条件的，由县级以上应急管理部门责令限期改正；逾期未投入必需的资金，仍不具备安全生产条件的（   ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '由负有安全生产监督管理职责的部门报请县级以上人民政府按照国家规定的权限决定予以关闭',
        '吊销有关资质',
        '责令停产停业整顿',
        '由负有安全生产监督管理职责的部门实施挂牌督办',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应责令停产停业整顿。',
      explanation: '未确保安全生产资金投入的单位将被责令停产整顿。',
      point: '10',
    },
    {
      question: '生产经营单位的安全生产管理人员未履行《陕西省安全生产条例》规定的安全生产管理职责，由县级以上应急管理部门责令限期改正；导致发生生产安全事故的，（   ）；构成犯罪的，依法追究刑事责任。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '5年内不得从事与本行业相关的工作',
        '暂扣或者吊销其与安全生产有关的资格证书',
        '处5万元以上10万元以下罚款',
        '处2万元以上5万元以下罚款',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，将暂扣或吊销资格证书。',
      explanation: '根据《陕西省安全生产条例》，未履行职责导致事故的，需暂扣或吊销资格证书。',
      point: '10',
    },
    {
      question: '生产经营单位委托其他有专业资质的单位进行危险作业的，在作业前与受托方签订（   ），并对受托方安全生产工作统一协调管理。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '委托合同',
        '任务书',
        '安全生产管理协议',
        '目标责任书',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需签订安全生产管理协议。',
      explanation: '危险作业需签订安全生产管理协议以确保安全管理。',
      point: '10',
    },
    {
      question: '生产经营单位在进行爆破、吊装重大危险源作业和动火受限空间、高处作业建筑物和构筑物拆除等危险作业时应配备相应的安全设施、采取安全防范措施、设置作业现场的安全区域以及（   ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安全技术交底',
        '实行作业前审批制度',
        '作业前向有关部门办理备案登记',
        '确定专人现场统一指挥和监督',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需专人现场指挥和监督。',
      explanation: '危险作业需专人现场统一指挥和监督以确保安全。',
      point: '10',
    },
    {
      question: '安全生产工作应当遵循（   ）的原则，坚持安全第一、预防为主、综合治理的方针，落实生产经营单位的主体责任，强化分级负责属地管理、谁主管谁负责的监管责任。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安全发展、生命至上',
        '发展绝不能以牺牲人的生命为代价',
        '以人为本、安全发展',
        '管生产经营必须管安全',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，原则是以人为本、安全发展。',
      explanation: '安全生产工作需遵循以人为本、安全发展的原则。',
      point: '10',
    },
    {
      question: '县级以上人民政府及其有关部门应当采取多种形式，加强安全生产法律、法规和安全生产知识的宣传教育，推进安全文化建设，增强（   ），提高安全防范能力和自救互救能力。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '行政区域内各行业安全生产绩效',
        '全社会的安全生产意识',
        '属地内所有从业人员的安全生产意识',
        '本级人民政府及其有关部门执法人员的安全知识储备',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应增强全社会安全生产意识。',
      explanation: '宣传教育旨在提升全社会的安全生产意识。',
      point: '10',
    },
    {
      question: '生产经营单位应当具备法律、法规和有关国家标准、行业标准、地方标准规定的安全生产条件,不得使用（  ）公布的应当淘汰的危及生产安全的工艺、设备、材料、技术。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '国家',
        '行业',
        '规范',
        '国家和本省',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，禁止使用国家和本省淘汰的工艺设备。',
      explanation: '国家和省级规定淘汰的危及安全的工艺设备不得使用。',
      point: '10',
    },
    {
      question: '生产经营单位应当为从业人员提供符合国家标准或者行业标准的劳动防护用品，并（   ）从业人员正确佩戴、使用，不得以现金或者其他物品替代劳动防护用品的提供。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '教育、督促',
        '监督、检查',
        '规范',
        '强制',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应教育和督促正确使用。',
      explanation: '单位需教育和督促从业人员正确使用防护用品。',
      point: '10',
    },
    {
      question: '宾馆、饭店、体育场（馆）、商场、旅游景区、集贸市场、客运车站候车室、客运码头候船厅、民用机场航站楼、会堂、公共娱乐场所、寺庙等公众聚集场所，不得超过规定或设计的容纳人数，应当设置符合紧急疏散要求、标识明显、保持畅通的安全出口，配备应急广播、照明和（   ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '安保人员',
        '救援设备',
        '安全监控系统',
        '医务室',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需配备安全监控系统。',
      explanation: '公众聚集场所需配备安全监控系统以确保安全。',
      point: '10',
    },
    {
      question: '当企业发生生产安全事故时，企业有关人员的正确做法应该是（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '企业事故现场人员立即报告当地安全监管部门',
        '企业事故现场人员应立即撤离作业场所，并在 2 小时内报告安全监管部门',
        '企业负责人应当迅速组织抢救，减少人员伤亡和财产损失',
        '企业负责人因组织抢救破坏现场的，必须报请安全监管部门批准',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，企业负责人应迅速组织抢救。',
      explanation: '根据《安全生产法》，企业负责人需立即组织抢救以减少损失。',
      point: '10',
    },
    {
      question: '下列关于事故报告和应急预案工作的说法，正确的是（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '危险物品的生产、经营、储存单位都应建立应急救援组织，配备必要的应急救援器材、设备和物资',
        '负有安全监管职责的部门接到事故报告后，应在 3 小时内核实上报事故情况',
        '安全监督部门接到生产安全事故报告后，应在 2 小时内赶赴事故现场',
        '有关地方政府负责人接到生产安全事故报告后，应按要求立即赶到事故现场，组织事故抢救',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，地方政府负责人需立即赶到现场组织抢救。',
      explanation: '地方政府负责人接到事故报告后需迅速组织抢救。',
      point: '10',
    },
    {
      question: '关于该公司事故报告和应急救援的说法，正确的是（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '发生一般及以上生产安全事故时，该公司负责人应当立即组织抢救，并按有关规定立即如实报告有关部门',
        '发生较大及以上生产安全事故时，该公司负责人应当立即组织抢救，一般事故由该公司安全员立即组织抢救',
        '发生重大及以上生产安全事故时，该公司负责人应当立即组织抢救，一般事故和较大事故由该公司安全管理人员立即组织抢救',
        '发生特别重大生产安全事故时，该公司负责人应当立即组织抢救，其他事故由该公司安全管理机构负责人立即组织抢救',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需立即组织抢救并如实报告。',
      explanation: '所有级别事故均需公司负责人立即组织抢救并报告。',
      point: '10',
    },
    {
      question: '关于生产安全事故应急救援与调查处理的说法，正确的是（  ）。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '单位负责人接到事故报告后，除因病重、出国或无法及时赶到现场等原因外，必须迅速采取一切有效措施，组织事故抢救',
        '除尚未查清伤亡人数、财产损失等原因外，必须立即将事故报告当地安全监管部门',
        '除尚末核实事故起因和伤亡人数等原因外，不得迟报事故',
        '在任何情况下均不得故意破坏事故现场和毁灭有关证据',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，负责人需迅速组织抢救。',
      explanation: '单位负责人需迅速采取措施组织事故抢救。',
      point: '10',
    },
    {
      question: '生产经营单位的主要负责人在本单位发生生产安全事故时，不立即组织抢救或者在事故调查处理期间擅离职守或者逃匿的，给予（   ）的处分，并由安全生产监督管理部门处上年年收入百分之六十至百分之一百的罚款。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '记大过',
        '警告',
        '降级、撤职',
        '开除',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，给予降级或撤职处分。',
      explanation: '根据《安全生产法》，不履行职责的主管人员将面临降级或撤职及罚款。',
      point: '10',
    },
  ],
};

export default quiz;
