const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产法律法规多选题测验',
  quizSynopsis: '本测验涵盖建设工程安全生产法律法规的多选题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '354',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '下列建筑施工人员属于特种作业的是(   )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '建筑电工',
        '建筑起重信号司索工',
        '建筑架子工',
        '建筑起重机械安装拆卸工',
        '经省级以上人民政府建设主管部门认定的其他特种作业',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上选项均为特种作业人员。',
      explanation: '根据《建筑施工特种作业人员管理规定》，列出的工种均需特种作业资格证书。',
      point: '10',
    },
    {
      question: '从事建筑施工特种作业的人员，应当具备下列那些基本条件（   ）',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '年满18周岁且符合相关工种规定的年龄要求',
        '经医院体检合格且无妨碍从事相应特种作业的疾病和生理缺陷',
        '年满20周岁且符合相关工种规定的年龄要求',
        '高中及以上学历',
        '初中及以上学历',
      ],
      correctAnswer: [1, 2, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查年龄和学历要求。',
      explanation: '根据规定，特种作业人员需年满18周岁、身体健康、初中及以上学历。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员的考核内容应当包括(   )。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '安全技术理论',
        '安全思想教育',
        '安全技术措施',
        '实际操作',
        '职业卫生考核',
      ],
      correctAnswer: [1, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，考核内容包括安全技术理论和实际操作。',
      explanation: '考核重点为安全技术理论和实际操作能力。',
      point: '10',
    },
    {
      question: '在施工中发生危及人身安全的紧急情况时，建筑施工特种作业人员有权(   )或者（   ），并向施工现场（  ）和（   ）报告。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '立即停止作业',
        '撤离危险区域',
        '项目负责人',
        '专职安全生产管理人员',
        '企业负责人',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需停止作业、撤离并向项目负责人和安全管理人员报告。',
      explanation: '根据《安全生产法》，特种作业人员在紧急情况下可停止作业、撤离并报告相关负责人。',
      point: '10',
    },
    {
      question: '特种作业人员所在用人单位应当履行下列那些职责（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '与持有效资格证书的特种作业人员订立劳动合同',
        '书面告知特种作业人员违章操作的危害',
        '向特种作业人员提供齐全、合格的安全防护用品和安全的作业条件',
        '查处特种作业人员违章行为并记录在档',
        '法律法规及有关规定明确的其他职责',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为用人单位职责。',
      explanation: '根据《建筑施工特种作业人员管理规定》，用人单位需履行上述所有职责。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员申请延期复核，应当提交的材料（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '身份证(原件和复印件)',
        '体检合格证明',
        '年度安全教育培训证明或者继续教育证明',
        '用人单位出具的特种作业人员管理档案记录',
        '考核发证机关规定提交的其他资料',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为延期复核所需材料。',
      explanation: '根据规定，延期复核需提交身份证、体检证明、培训证明等材料。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员在资格证书有效期内，有（  ）情形之一的，延期复核结果为不合格。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '超过相关工种规定年龄要求的',
        '身体健康状况不再适应相应特种作业岗位的',
        '对生产安全事故负有责任的',
        '2年内违章操作记录达2次(含2次)以上的',
        '未按规定参加年度安全教育培训或者继续教育的',
      ],
      correctAnswer: [1, 2, 3, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查不合格情形。',
      explanation: '根据规定，上述情形会导致延期复核不合格，注意违章操作记录达3次以上才适用。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员有（   ）情形之一的，考核发证机关应当撤销其资格证书。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '持证人弄虚作假利用他人办理延期复核手续的',
        '持证人弄虚作假骗取资格证书或者办理延期复核手续的',
        '考核发证机关规定应当撤销资格证书的其他情形',
        '考核发证机关工作人员违法核发资格证书的',
        '持证人逾期未申请办理延期复核手续的',
      ],
      correctAnswer: [2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查撤销资格证书的情形。',
      explanation: '弄虚作假或违法核发证书会导致证书被撤销。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员有（   ）情形之一的，考核发证机关应当注销资格证书。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '依法不予延期的',
        '持证人死亡或者不具有完全民事行为能力的',
        '持证人逾期未申请办理延期复核手续的',
        '考核发证机关规定应当注销的其他情形',
        '考核发证机关工作人员违法核发资格证书的',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查注销资格证书的情形。',
      explanation: '依法不予延期、死亡、逾期未复核等情形会导致证书注销。',
      point: '10',
    },
    {
      question: '建筑施工企业安全生产管理机构具有（   ）职责。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '编制并适时更新安全生产管理制度并监督实施',
        '组织开展安全教育培训与交流',
        '建立企业在建项目安全生产管理档案',
        '协调配备项目专职安全生产管理人员',
        '负责组织危险性较大工程安全专项施工方案专家论证会',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查安全生产管理机构职责。',
      explanation: '安全生产管理机构职责不包括组织专家论证会。',
      point: '10',
    },
    {
      question: '建筑施工企业安全生产管理机构专职安全生产管理人员在施工现场检查过程中具有（   ）职责。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '查阅在建项目安全生产有关资料、核实有关情况',
        '检查危险性较大工程安全专项施工方案落实情况',
        '对发现的安全生产违章违规行为或安全隐患，有权当场予以纠正或作出处理决定',
        '监督作业人员安全防护用品的配备及使用情况',
        '对不符合安全生产条件的设施、设备、器材，有权当场作出查封的处理决定',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为专职安全管理人员职责。',
      explanation: '专职安全管理人员在现场检查中需履行上述所有职责。',
      point: '10',
    },
    {
      question: '建筑施工企业安全生产管理机构专职安全生产管理人员的配备应满足（   ）要求。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '建筑施工总承包一级资质企业应不少于4人',
        '建筑施工专业承包一级资质企业应不少于3人',
        '建筑施工专业承包资一级资质企业应不少于2人',
        '建筑施工劳务分包资质企业应不少于2人',
        '建筑施工一级资质企业应不少于5人',
      ],
      correctAnswer: [1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查配备要求。',
      explanation: '根据规定，总承包一级不少于4人，专业承包一级不少于3人，劳务分包不少于2人。',
      point: '10',
    },
    {
      question: '生产经营单位应对本单位存在的安全生产风险进行分类管理，定期组织（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '日常安全生产巡查',
        '定期进行专项安全生产排查',
        '每月至少进行一次综合安全生产检查',
        '季节性安全检查',
        '节假日前后安全检查',
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需进行日常巡查、专项排查和综合检查。',
      explanation: '生产经营单位需定期开展日常、专项和综合安全检查。',
      point: '10',
    },
    {
      question: '矿山、危险化学品、烟花爆竹、（   ）等高危行业领域、尘肺病等职业病易发企业强制实施安全生产责任保险。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '交通运输',
        '建筑施工',
        '民用爆炸物品',
        '金属冶炼',
        '渔业生产',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为高危行业需强制实施责任保险。',
      explanation: '高危行业领域需强制实施安全生产责任保险。',
      point: '10',
    },
    {
      question: '高瓦斯和煤与瓦斯突出矿井应当执行（   ）的瓦斯治理方针。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '先抽后采',
        '监测监控',
        '以风定产',
        '应抽尽抽',
        '可保尽保',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为瓦斯治理方针。',
      explanation: '高瓦斯矿井需遵循全面的瓦斯治理方针。',
      point: '10',
    },
    {
      question: '水害矿井应当加强水害预报工作，按照（  ）的原则，应当采取“防、堵、疏、排、截”的综合治理措施。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '预测预报',
        '监测监控',
        '有疑必探',
        '先探后掘',
        '先治后采',
      ],
      correctAnswer: [1, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查水害预报原则。',
      explanation: '水害矿井需遵循预测预报、有疑必探、先探后掘、先治后采的原则。',
      point: '10',
    },
    {
      question: '应当按照国家有关规定进行安全评价的建设项目有（  ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '矿山建设项目',
        '金属冶炼建设项目',
        '人员密集场所建设项目',
        '用于生产、储存、装卸危险物品的建设项目',
        '学校建设项目',
      ],
      correctAnswer: [1, 2, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需进行安全评价的项目包括矿山、金属冶炼和危险物品项目。',
      explanation: '根据规定，矿山、金属冶炼和危险物品项目需进行安全评价。',
      point: '10',
    },
    {
      question: '生产经营单位从业人员需履行的义务有（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '遵守本单位的安全生产规章制度和操作、作业规程',
        '正确使用劳动防护用品',
        '接受安全生产教育和培训',
        '及时报告事故隐患和不安全因素',
        '上岗前进行岗位安全检查',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，以上均为从业人员义务。',
      explanation: '从业人员需履行遵守制度、正确使用防护用品、接受培训、报告隐患和安全检查等义务。',
      point: '10',
    },
    {
      question: '负有安全生产监督管理职责的部门应当建立安全生产违法行为信息库，如实记录生产经营单位的安全生产违法行为信息；对违法行为情节严重的生产经营单位，应当向（   ）通报，并向社会公示。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '行业主管部门',
        '投资主管部门',
        '国土资源主管部门',
        '证券监督管理机构',
        '有关金融机构',
      ],
      correctAnswer: [1, 2, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需向以上部门通报并公示。',
      explanation: '严重违法行为需向多个主管部门通报并向社会公示。',
      point: '10',
    },
    {
      question: '生产经营单位的（   ）不良信息，应纳入本省公共信用信息系统。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '发生较大以上生产安全责任事故的',
        '因安全生产违法行为，受到较大数额罚款或者责令停产停业行政处罚的',
        '重大事故隐患在责令整改的期限内未完成整改的',
        '拒不接受安全生产监督检查的',
        '因安全生产条件不达标被媒体曝光的',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查纳入信用系统的条件。',
      explanation: '严重安全违法行为和事故需纳入公共信用信息系统。',
      point: '10',
    },
    {
      question: '城乡规划主管部门在核发（   ）时，应当确保新建、改建、扩建项目与已有生产、经营、储存有毒、有害、危险品的场所的安全距离符合法律、法规的规定。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '建设项目选址意见书',
        '建设项目施工许可证',
        '建设工程规划许可证',
        '乡村建设规划许可证',
        '建设用地规划许可证',
      ],
      correctAnswer: [1, 3, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，施工许可证不涉及安全距离要求。',
      explanation: '城乡规划需确保选址、规划和用地许可符合安全距离要求。',
      point: '10',
    },
    {
      question: '作出（   ）处罚决定的，应当告知当事人有要求举行听证的权利。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '责令停产停业',
        '吊销资质',
        '对单位处十万元以上罚款',
        '对个人处三万元以上罚款',
        '停业整顿',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查需告知听证权的情形。',
      explanation: '重大行政处罚如停产、吊销资质或高额罚款需告知听证权。',
      point: '10',
    },
    {
      question: '陕西省安全生产条例制定的目的是（   ）。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '加强安全生产工作',
        '防止和减少生产安全事故',
        '提高安全生产工作绩效',
        '保障人民群众生命和财产安全',
        '促进经济社会持续健康发展',
      ],
      correctAnswer: [1, 2, 4, 5],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检查条例制定的目的。',
      explanation: '《陕西省安全生产条例》旨在加强安全工作、减少事故、保障安全和促进发展。',
      point: '10',
    },
    {
      question: '生产经营单位是安全生产的责任主体，应当遵守有关安全生产法律、法规，建立健全安全生产责任制和安全生产规章制度，加强安全生产管理，改善安全生产条件，推进安全生产（   ）建设，提高安全生产水平，确保安全生产。',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        '科技化',
        '文明化',
        '标准化',
        '信息化',
        '制度化',
      ],
      correctAnswer: [1, 3, 4],
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需推进科技化、标准化、信息化建设。',
      explanation: '生产经营单位需推进安全生产的科技化、标准化和信息化建设。',
      point: '10',
    },
  ],
};

export default quiz;
