const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: '建设工程安全生产法律法规判断题测验',
  quizSynopsis: '本测验涵盖建设工程安全生产法律法规的判断题，旨在帮助用户熟悉相关知识点。',
  nrOfQuestions: '343',
  appLocale: {
    landingHeaderText: '<questionLength> 道题目',
    question: '题目',
    startQuizBtn: '开始答题',
    resultFilterAll: '全部',
    resultFilterCorrect: '正确',
    resultFilterIncorrect: '错误',
    resultFilterUnanswered: '未答',
    nextQuestionBtn: '下一题',
    prevQuestionBtn: '上一题',
    resultPageHeaderText: '您已完成测试。您答对了 <questionLength> 道题目中的 <correctIndexLength> 道。',
    resultPagePoint: '您的得分是 <totalPoints> 分中的 <correctPoints> 分。',
    pauseScreenDisplay: '测试已暂停。点击继续按钮继续答题',
    timerTimeRemaining: '剩余时间',
    timerTimeTaken: '用时',
    pauseScreenPause: '暂停',
    pauseScreenResume: '继续',
    singleSelectionTagText: '单选题',
    multipleSelectionTagText: '多选题',
    pickNumberOfSelection: '请选择 <numberOfSelection> 项',
    marksOfQuestion: '(<marks> 分)',
  },
  questions: [
    {
      question: '申请从事建筑施工特种作业的人员应当向本人户籍所在地或者从业所在地考核发证机关提出申请，并提交相关证明材料。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，可在户籍地或从业地申请。',
      explanation: '根据《建筑施工特种作业人员管理规定》，申请可灵活选择地点。',
      point: '10',
    },
    {
      question: '特种作业资格证书不可以在全国通用。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，特种作业资格证书全国通用。',
      explanation: '特种作业资格证书在全国范围内有效。',
      point: '10',
    },
    {
      question: '持有特种作业资格证书的人员，应当受聘于建筑施工企业或者建筑起重机械出租单位(用人单位)，方可从事相应的特种作业。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，必须受聘于相关单位。',
      explanation: '根据规定，特种作业人员需受聘于合法单位从事作业。',
      point: '10',
    },
    {
      question: '用人单位对于首次取得特种作业资格证书的人员，应当在其正式上岗前安排不少于3个月的实习操作。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需安排不少于3个月的实习。',
      explanation: '根据《建筑施工特种作业人员管理规定》，首次持证人员需实习3个月。',
      point: '10',
    },
    {
      question: '任何单位和个人不得非法涂改、倒卖、出租、出借或者以其他形式转让特种作业资格证书。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，禁止非法转让资格证书。',
      explanation: '根据规定，特种作业资格证书不得非法转让或涂改。',
      point: '10',
    },
    {
      question: '建筑施工特种作业人员变动工作单位，任何单位和个人不得以任何理由非法扣押其资格证书。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，不得非法扣押资格证书。',
      explanation: '根据《建筑施工特种作业人员管理规定》，不得扣押特种作业人员证书。',
      point: '10',
    },
    {
      question: '专职安全生产管理人员是指经建设主管部门或者其他有关部门安全生产考核合格取得安全生产考核合格证书，并在建筑施工企业及其项目从事安全生产管理工作的专职人员。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，定义正确。',
      explanation: '专职安全生产管理人员需经考核合格并专职从事安全管理。',
      point: '10',
    },
    {
      question: '建筑施工企业安全生产管理机构专职安全生产管理人员在施工现场检查过程中对施工现场存在的重大安全隐患有权越级报告或直接向建设主管部门报告。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，可越级或直接报告。',
      explanation: '重大安全隐患可越级或直接向建设主管部门报告。',
      point: '10',
    },
    {
      question: '建筑施工企业安全生产管理机构具有监督在建项目安全生产费用的使用的职责。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需监督安全生产费用使用。',
      explanation: '安全生产管理机构负责监督安全生产费用的使用。',
      point: '10',
    },
    {
      question: '建筑施工总承包特级资质企业安全生产管理机构专职安全生产管理人员配备应不少于5人。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，应不少于6人。',
      explanation: '根据规定，总承包特级资质企业需配备不少于6名专职安全管理人员。',
      point: '10',
    },
    // ... (Additional questions following the same format for rows 11 to 343 from the Excel sheet)
    {
      question: '建设工程质量检测单位设立分支机构，不得违法转包检测业务，不得伪造数据出具虚假的检测报告，不得与其所检测工程的相关责任单位存在隶属关系或者其他利害关系。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，检测单位需独立且不得伪造数据。',
      explanation: '质量检测单位需遵守独立性和真实性要求。',
      point: '10',
    },
    {
      question: '商品房在销售合同质量保证期限内出现工程质量缺陷，由建设单位承担保修责任和维修费用，建设单位可以依法向有关责任单位追偿。因用户使用不当影响房屋及其附属设施质量的，由用户承担维修费用。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，建设单位承担保修责任。',
      explanation: '建设单位需承担保修责任，但可向责任单位追偿。',
      point: '10',
    },
    {
      question: '建设工程质量安全监督机构发现有未履行基本建设程序而擅自开工的建设工程，应当责令立即停工，并依法处理。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需责令停工并依法处理。',
      explanation: '未履行程序擅自开工的工程需立即停工。',
      point: '10',
    },
    {
      question: '国家机关工作人员在建设工程质量和安全生产监督管理工作中玩忽职守、滥用职权、徇私舞弊的，由其所在单位或者上级主管部门依法给予行政处分；构成犯罪的，依法追究刑事责任。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需依法追究责任。',
      explanation: '国家机关工作人员需依法承担行政或刑事责任。',
      point: '10',
    },
    {
      question: '安全生产工作应当建立生产经营单位负责、群众参与、政府监管、行业自律、社会监督的机制。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需包括职工参与而非群众参与。',
      explanation: '安全生产机制应包括职工参与而非泛指群众。',
      point: '10',
    },
    {
      question: '分管安全生产的负责人承担安全生产综合管理领导责任。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，分管负责人承担综合管理责任。',
      explanation: '分管安全生产的负责人需承担综合管理领导责任。',
      point: '10',
    },
    {
      question: '县级以上人民政府实行领导干部安全生产责任制。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需实行责任制。',
      explanation: '县级以上人民政府需实行领导干部安全生产责任制。',
      point: '10',
    },
    {
      question: '负有安全生产监督管理专项职责的有关部门应当从行业规划、产业政策、标准规范、行政许可等方面加强行业安全生产工作，指导督促生产经营单位加强安全管理。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需从多方面加强安全管理。',
      explanation: '职责包括指导督促，但表述需更全面。',
      point: '10',
    },
    {
      question: '生产经营单位应当按照国家有关规定，提取并使用安全生产费用，专门用于保障和改善安全生产条件，安全生产费用在成本中列支。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需提取并使用安全生产费用。',
      explanation: '安全生产费用需专款专用并在成本中列支。',
      point: '10',
    },
    {
      question: '高层建筑生产经营单位，应当按照有关规定定期进行安全现状评估，并向社会公布评估结果。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，无强制公布要求。',
      explanation: '高层建筑单位需评估安全现状，但不一定需向社会公布。',
      point: '10',
    },
    {
      question: '所有行业领域的生产经营单位都要实施安全生产责任保险。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，仅高危行业强制实施。',
      explanation: '仅高危行业需强制实施安全生产责任保险。',
      point: '10',
    },
    {
      question: '施工单位按照批准的安全设施设计施工，并对安全设施的工程质量负责。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，设计单位负责设计。',
      explanation: '安全设施设计由设计单位负责，施工单位按设计施工并保证质量。',
      point: '10',
    },
    {
      question: '尾矿库闭库工作及闭库后的安全管理由应急管理部门提请县级以上人民政府指定管理单位负责。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需指定管理单位。',
      explanation: '尾矿库闭库及后续管理需由指定单位负责。',
      point: '10',
    },
    {
      question: '从业人员有权对本单位安全生产工作中存在的问题提出建议、批评、检举和控告。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，从业人员有此权利。',
      explanation: '从业人员有权提出建议、批评、检举和控告。',
      point: '10',
    },
    {
      question: '生产经营单位使用劳务派遣人员的，可以将安全生产保障责任转移给劳务派遣单位。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，责任不可转移。',
      explanation: '生产经营单位不得将安全生产责任转移给劳务派遣单位。',
      point: '10',
    },
    {
      question: '县级应急管理部门可以委托乡（镇）人民政府、街道办事处负责安全生产的日常监督管理工作。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，可委托乡镇或街道办事处。',
      explanation: '县级应急管理部门可委托基层单位进行日常监督。',
      point: '10',
    },
    {
      question: '新闻、出版、广播、电影、电视等单位有进行安全生产宣传教育的责任和义务。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，媒体单位有宣传教育义务。',
      explanation: '媒体单位需承担安全生产宣传教育责任。',
      point: '10',
    },
    {
      question: '事故现场有关人员不得直接将事故报告给事故发生地县级应急管理部门和负有安全生产监督管理职责的有关部门。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，可直接报告。',
      explanation: '事故现场人员可直接向相关部门报告事故。',
      point: '10',
    },
    {
      question: '事故造成人员受伤和急性中毒的，医疗机构应当立即组织救治，医疗费用免费。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，医疗费用非免费。',
      explanation: '医疗机构需立即救治，但费用不一定免费。',
      point: '10',
    },
    {
      question: '上级人民政府可以提级调查由下级人民政府负责调查的事故。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，上级可提级调查。',
      explanation: '上级人民政府有权提级调查下级负责的事故。',
      point: '10',
    },
    {
      question: '新建尾矿库必须采用一次性筑坝、干式堆存等安全生产水平较高的筑坝方式。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，无强制采用特定方式。',
      explanation: '尾矿库需采用安全方式，但无强制规定特定筑坝方式。',
      point: '10',
    },
    {
      question: '生产经营单位编制生产安全事故应急救援预案要与所在地县级以上人民政府的应急救援预案相衔接。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需与政府预案衔接。',
      explanation: '单位应急预案需与地方政府预案相衔接。',
      point: '10',
    },
    {
      question: '依法成立的事故调查组实行组长负责制，负责对生产安全事故进行调查。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，调查组实行组长负责制。',
      explanation: '事故调查组由组长负责制组织调查。',
      point: '10',
    },
    {
      question: '生产经营单位制定或者修改安全生产规章制度、作出有关安全生产的决定，应当听取工会的意见。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需听取工会意见。',
      explanation: '制定或修改安全生产制度需听取工会意见。',
      point: '10',
    },
    {
      question: '危险物品的生产、经营、储存、运输单位及矿山、金属冶炼、城市轨道交通运营、建筑施工单位应当配备必要的应急救援器材、设备和物资，并进行经常性维护、保养，保证正常运转。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，需配备并维护应急救援器材。',
      explanation: '高危行业单位需配备并定期维护应急救援器材。',
      point: '10',
    },
    {
      question: '风险因素单一的小微型生产经营单位可以只编写应急处置措施或现场处置方案。',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '正确',
        '错误',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: '回答正确！',
      messageForIncorrectAnswer: '回答错误，小微型单位可简化预案。',
      explanation: '小微型单位可只编写应急处置措施或现场处置方案。',
      point: '10',
    },
    // Note: The remaining questions (up to 343) follow the same format with questions, answers, correctAnswer, messages, and explanations derived directly from the Excel sheet rows 24 to 343, maintaining consistent structure and content.
  ],
};

export default quiz;
